# Generated by Django 5.1.15 on 2026-03-13 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('IT', 'IT'), ('OT', 'OT')], max_length=5)),
                ('criticality', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criticality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dep_type', models.CharField(choices=[('dipende_da', 'Dipende da'), ('connesso_a', 'Connesso a')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('IT', 'IT'), ('OT', 'OT'), ('DMZ', 'DMZ')], max_length=10)),
                ('purdue_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIT',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('fqdn', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('eol_date', models.DateField(blank=True, null=True)),
                ('cve_score_max', models.FloatField(blank=True, null=True)),
                ('internet_exposed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Asset IT',
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='AssetOT',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('purdue_level', models.IntegerField()),
                ('category', models.CharField(choices=[('PLC', 'PLC'), ('SCADA', 'SCADA'), ('HMI', 'HMI'), ('RTU', 'RTU'), ('sensore', 'Sensore'), ('altro', 'Altro')], max_length=20)),
                ('patchable', models.BooleanField(default=False)),
                ('patch_block_reason', models.TextField(blank=True)),
                ('maintenance_window', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Asset OT',
            },
            bases=('assets.asset',),
        ),
    ]
