# Generated by Django 5.1.15 on 2026-03-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('bia', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='plants.plant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='processes',
            field=models.ManyToManyField(blank=True, to='bia.criticalprocess'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='from_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='to_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='networkzone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkzone',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
        migrations.AddField(
            model_name='assetot',
            name='network_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.networkzone'),
        ),
    ]
