# Generated by Django 5.1.15 on 2026-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='change_portal_url',
            field=models.URLField(blank=True, help_text='Link diretto al ticket nel portale change management'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_change_date',
            field=models.DateField(blank=True, help_text="Data dell'ultimo change registrato", null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_change_desc',
            field=models.CharField(blank=True, help_text='Descrizione breve del change', max_length=300),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_change_ref',
            field=models.CharField(blank=True, help_text='Riferimento ticket esterno es. JIRA-1234, SN-5678', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='needs_revaluation',
            field=models.BooleanField(default=False, help_text='True se il change richiede rivalutazione dei controlli e del risk assessment collegati'),
        ),
        migrations.AddField(
            model_name='asset',
            name='needs_revaluation_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
