# Generated by Django 5.1.15 on 2026-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_change_portal_url_asset_last_change_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetit',
            name='data_classification',
            field=models.CharField(blank=True, help_text='Classificazione dati principale (es. internal, confidential, restricted).', max_length=20),
        ),
        migrations.AddField(
            model_name='assetit',
            name='deployment_type',
            field=models.CharField(choices=[('on_prem', 'On-premise'), ('iaas', 'IaaS'), ('paas', 'PaaS'), ('saas', 'SaaS')], default='on_prem', help_text='Modalità di erogazione: on-premise, IaaS, PaaS o SaaS.', max_length=10),
        ),
        migrations.AddField(
            model_name='assetit',
            name='provider',
            field=models.CharField(blank=True, help_text='Cloud/service provider es. Microsoft, AWS, SAP.', max_length=100),
        ),
        migrations.AddField(
            model_name='assetit',
            name='service_name',
            field=models.CharField(blank=True, help_text='Nome del servizio es. Microsoft 365, Salesforce, SAP S/4HANA Cloud.', max_length=150),
        ),
    ]
