# Generated by Django 5.1.15 on 2026-04-10 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetit_data_classification_assetit_deployment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSW',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('approval_status', models.CharField(choices=[('approvato', 'Approvato'), ('in_valutazione', 'In valutazione'), ('deprecato', 'Deprecato'), ('vietato', 'Vietato')], default='in_valutazione', max_length=20)),
                ('license_type', models.CharField(blank=True, choices=[('commerciale', 'Commerciale'), ('open_source', 'Open Source'), ('saas', 'SaaS'), ('freeware', 'Freeware')], max_length=20)),
                ('end_of_support', models.DateField(blank=True, help_text='Data di fine supporto del vendor (EOS). Alla scadenza viene creato un task.', null=True)),
                ('external_ref', models.CharField(blank=True, help_text='Riferimento nel sistema ITAM esterno (es. Lansweeper ID 4521, ServiceNow CI-00123).', max_length=200)),
            ],
            options={
                'verbose_name': 'Asset SW',
            },
            bases=('assets.asset',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('IT', 'IT'), ('OT', 'OT'), ('SW', 'SW')], max_length=5),
        ),
    ]
