# Generated by Django 5.1.15 on 2026-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_sw'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsw',
            name='vendor_url',
            field=models.URLField(blank=True, help_text='URL del vendor del software — usato dal modulo OSINT per monitoraggio passivo del dominio fornitore.', max_length=500),
        ),
    ]
