# Generated by Django 5.1.15 on 2026-06-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetsw_vendor_url'),
        ('suppliers', '0012_supplier_additional_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maintainer_supplier',
            field=models.ForeignKey(blank=True, help_text='Fornitore che manutiene / ha accesso remoto a questo asset. Usato dal modulo OSINT per escalare gli alert critici dei fornitori con foothold su asset OT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_assets', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='assetot',
            name='fqdn',
            field=models.CharField(blank=True, help_text="Hostname pubblico dell'interfaccia di management/teleassistenza, se esposta.", max_length=255),
        ),
        migrations.AddField(
            model_name='assetot',
            name='internet_exposed',
            field=models.BooleanField(default=False, help_text="L'asset OT è raggiungibile da Internet (condizione di rischio elevato)."),
        ),
        migrations.AddField(
            model_name='assetot',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="IP pubblico dell'interfaccia di management, se esposta.", null=True),
        ),
    ]
