# Generated by Django 5.1.15 on 2026-06-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_maintainer_supplier_assetot_fqdn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdependency',
            options={'ordering': ['from_asset_id', 'to_asset_id']},
        ),
        migrations.AlterModelOptions(
            name='networkzone',
            options={'ordering': ['plant_id', 'name']},
        ),
    ]
