# Generated by Django 5.2.17 on 2026-08-25 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_assetdependency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_result',
            field=models.CharField(blank=True, choices=[('superata', 'Superata'), ('con_riserve', 'Superata con riserve'), ('fallita', 'Fallita')], max_length=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_alert_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_frequency_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Cadenza di manutenzione in mesi; vuoto = nessuna manutenzione programmata (l'asset non entra nello scadenzario).", null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_maintenance_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetFacility',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('category', models.CharField(choices=[('ups', 'UPS / gruppo di continuità'), ('gruppo_elettrogeno', 'Gruppo elettrogeno'), ('antincendio', 'Rilevazione / spegnimento incendi'), ('climatizzazione', 'Climatizzazione sala tecnica'), ('controllo_accessi', 'Controllo accessi fisici'), ('videosorveglianza', 'Videosorveglianza'), ('altro', 'Altro impianto')], db_index=True, max_length=20)),
                ('location', models.CharField(blank=True, help_text='Ubicazione fisica: sala server, cabina elettrica, reparto…', max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('rated_autonomy_minutes', models.PositiveIntegerField(blank=True, help_text='Autonomia nominale dichiarata dal costruttore (UPS/gruppi elettrogeni).', null=True)),
                ('serves_assets', models.ManyToManyField(blank=True, help_text='Asset IT/OT alimentati o protetti da questo impianto.', related_name='supporting_facilities', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Facility',
                'verbose_name_plural': 'Asset Facility',
            },
            bases=('assets.asset',),
        ),
    ]
