# Generated by Django 5.2.17 on 2026-08-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('IT', 'IT'), ('OT', 'OT'), ('SW', 'SW'), ('FAC', 'Impianto')], max_length=5),
        ),
    ]
