# Generated by Django 5.1.15 on 2026-03-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_grc', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalauditortoken',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
        migrations.AddField(
            model_name='externalauditortoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userplantaccess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userplantaccess',
            name='scope_bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.businessunit'),
        ),
        migrations.AddField(
            model_name='userplantaccess',
            name='scope_plants',
            field=models.ManyToManyField(blank=True, to='plants.plant'),
        ),
        migrations.AddField(
            model_name='userplantaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
