# Generated by Django 5.1.15 on 2026-03-15 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_grc', '0002_initial'),
        ('documents', '0002_document_document_type_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCompetencyRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('grc_role', models.CharField(max_length=50)),
                ('competency', models.CharField(max_length=200)),
                ('required_level', models.IntegerField(choices=[(1, '1 — Awareness'), (2, '2 — Practitioner'), (3, '3 — Expert')], default=2)),
                ('evidence_type', models.CharField(choices=[('certification', 'Certificazione'), ('training', 'Training completato'), ('experience', 'Esperienza documentata'), ('assessment', 'Assessment interno')], default='training', max_length=20)),
                ('mandatory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grc_role', 'competency'],
                'unique_together': {('grc_role', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='UserCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competency', models.CharField(max_length=200)),
                ('level', models.IntegerField(choices=[(1, '1 — Awareness'), (2, '2 — Practitioner'), (3, '3 — Expert')], default=1)),
                ('evidence_type', models.CharField(choices=[('certification', 'Certificazione'), ('training', 'Training completato'), ('experience', 'Esperienza documentata'), ('assessment', 'Assessment interno')], default='training', max_length=20)),
                ('certification_body', models.CharField(blank=True, max_length=200)),
                ('obtained_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_evidences', to='documents.evidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_competencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'competency'],
                'unique_together': {('user', 'competency')},
            },
        ),
    ]
