# Generated by Django 5.1.15 on 2026-06-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_grc', '0005_trusteddevice_fingerprint_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalauditortoken',
            options={'ordering': ['-valid_from']},
        ),
        migrations.AlterModelOptions(
            name='userplantaccess',
            options={'ordering': ['user_id', 'role']},
        ),
    ]
