# Generated by Django 5.2.17 on 2026-09-21 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_grc', '0006_alter_externalauditortoken_options_and_more'),
        ('documents', '0006_document_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercompetency',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usercompetency',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'competency'), name='uniq_user_competency_alive'),
        ),
    ]
