# Generated by Django 5.1.15 on 2026-03-15 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsmsKpiSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField(help_text='Monday of the snapshot week')),
                ('framework_code', models.CharField(max_length=50)),
                ('controls_total', models.IntegerField(default=0)),
                ('controls_compliant', models.IntegerField(default=0)),
                ('controls_gap', models.IntegerField(default=0)),
                ('pct_compliant', models.FloatField(default=0.0)),
                ('overall_maturity', models.FloatField(blank=True, help_text='Average maturity_level of ControlInstances', null=True)),
                ('open_risks', models.IntegerField(default=0)),
                ('high_risks', models.IntegerField(default=0)),
                ('open_incidents', models.IntegerField(default=0)),
                ('critical_incidents', models.IntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, help_text='NULL = org-wide snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('plant', 'framework_code', 'week_start')},
            },
        ),
    ]
