# Generated by Django 5.2.17 on 2026-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismskpisnapshot',
            name='method_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
