version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: grc_dev
      POSTGRES_USER: grc
      POSTGRES_PASSWORD: grc
    ports: ["5433:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grc"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes: [redisdata:/data]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9001:9001"]
    volumes: [miniodata:/data]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./manual:/app/manual:ro
      - backupdata:/app/backups
    ports: ["8001:8000"]
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A core worker -l info --concurrency 2
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - backupdata:/app/backups
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: [backend, redis]

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: unless-stopped
    volumes: [./backend:/app]
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: [backend, redis]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes: [./frontend:/app, /app/node_modules]
    ports: ["3001:3000"]
    env_file: .env
    environment:
      - VITE_API_URL=http://localhost:8001

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports: ["1026:1025", "8026:8025"]

volumes:
  pgdata:
  redisdata:
  miniodata:
  backupdata:
