[pytest]
DJANGO_SETTINGS_MODULE = core.settings.test
# --cov-fail-under: target 70% da raggiungere con test su tutti i moduli
addopts = --reuse-db --cov=apps --cov=core --cov-report=term-missing --cov-fail-under=70

