# Generated by Django 5.1.15 on 2026-03-16 11:40

import apps.notifications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Configurazione principale', max_length=100)),
                ('provider', models.CharField(choices=[('office365', 'Microsoft Office 365'), ('gmail', 'Google Gmail / Workspace'), ('smtp_custom', 'SMTP Personalizzato')], default='smtp_custom', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('password', apps.notifications.models.EncryptedCharField(max_length=1024)),
                ('from_email', models.CharField(help_text='Es: GRC Platform <noreply@azienda.com>', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('risk_red', 'Rischio critico (score > soglia)'), ('finding_major', 'Finding Major NC aperto'), ('finding_minor', 'Finding Minor NC aperto'), ('incident_nis2', 'Incidente NIS2 rilevato'), ('incident_closed', 'Incidente chiuso'), ('task_assigned', 'Task assegnato'), ('task_overdue', 'Task scaduto'), ('evidence_expired', 'Evidenza scaduta'), ('document_approval', 'Documento in attesa approvazione'), ('role_expiring', 'Ruolo normativo in scadenza'), ('bcp_test_failed', 'Test BCP fallito'), ('pdca_blocked', 'PDCA bloccato > 30 giorni'), ('management_review', 'Revisione direzione da approvare'), ('supplier_assessment', 'Assessment fornitore completato')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('recipient_roles', models.JSONField(default=list, help_text="Lista ruoli GRC es. ['ciso','risk_manager']")),
                ('scope_type', models.CharField(choices=[('org', "Tutta l'organizzazione"), ('bu', 'Business Unit'), ('plant', 'Sito specifico')], default='org', max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scope_bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='plants.businessunit')),
                ('scope_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='plants.plant')),
            ],
            options={
                'ordering': ['event_type'],
                'unique_together': {('event_type', 'scope_type', 'scope_bu', 'scope_plant')},
            },
        ),
    ]
