# Generated by Django 5.1.15 on 2026-03-16 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailconfiguration_notificationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='recipient_roles',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='NotificationRoleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('grc_role', models.CharField(help_text='Codice ruolo GRC es. ciso, risk_manager', max_length=50, unique=True)),
                ('profile', models.CharField(choices=[('silenzioso', 'Silenzioso'), ('essenziale', 'Essenziale'), ('standard', 'Standard'), ('completo', 'Completo'), ('custom', 'Personalizzato')], default='standard', max_length=20)),
                ('custom_events', models.JSONField(blank=True, default=list, help_text='Lista eventi attivi se profilo = custom')),
                ('enabled', models.BooleanField(default=True, help_text='False = nessuna notifica per questo ruolo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grc_role'],
            },
        ),
    ]
