# Generated by Django 5.1.15 on 2026-03-16 13:32

import apps.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationrule_recipient_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='use_auth',
            field=models.BooleanField(default=True, help_text='Disattiva per relay SMTP senza autenticazione (es. porta 25 interno)'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='password',
            field=apps.notifications.models.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
