# Generated by Django 5.2.17 on 2026-09-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationrule_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('risk_red', 'Rischio critico (score > soglia)'), ('finding_major', 'Finding Major NC aperto'), ('finding_minor', 'Finding Minor NC aperto'), ('incident_nis2', 'Incidente NIS2 rilevato'), ('incident_closed', 'Incidente chiuso'), ('osint_critical', 'Alert OSINT critico (esposizione esterna)'), ('task_assigned', 'Task assegnato'), ('task_overdue', 'Task scaduto'), ('evidence_expired', 'Evidenza scaduta'), ('document_approval', 'Documento in attesa approvazione'), ('role_expiring', 'Ruolo normativo in scadenza'), ('bcp_test_failed', 'Test BCP fallito'), ('pdca_blocked', 'PDCA bloccato > 30 giorni'), ('management_review', 'Revisione direzione da approvare'), ('objective_off_track', 'Obiettivo di sicurezza fuori traiettoria'), ('objective_deadline', 'Obiettivo di sicurezza in scadenza'), ('supplier_assessment', 'Assessment fornitore completato'), ('supplier_concentration_critical', 'Concentrazione fornitura critica (crossing)')], max_length=50),
        ),
    ]
