# Generated by Django 5.1.15 on 2026-03-15 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSchedulePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_policies', to='plants.plant')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('framework', models.CharField(choices=[('ISO27001', 'ISO 27001'), ('NIS2', 'NIS2'), ('TISAX_L2', 'TISAX L2'), ('TISAX_L3', 'TISAX L3')], max_length=20)),
                ('document_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('iso_clause', models.CharField(blank=True, max_length=30)),
                ('mandatory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['framework', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('control_review', 'Revisione controlli'), ('control_audit', 'Audit interno controlli'), ('document_policy', 'Revisione policy'), ('document_procedure', 'Revisione procedura'), ('document_record', 'Aggiornamento registro'), ('risk_assessment', 'Rivalutazione rischi'), ('risk_treatment', 'Revisione piano trattamento'), ('bcp_test', 'Test BCP/DR'), ('bcp_review', 'Revisione piano BCP'), ('incident_review', 'Revisione incidenti chiusi'), ('supplier_assessment', 'Assessment fornitori'), ('supplier_contract_review', 'Revisione contratti fornitori'), ('training_mandatory', 'Formazione obbligatoria'), ('training_refresh', 'Aggiornamento formazione'), ('management_review', 'Revisione della direzione'), ('security_committee', 'Riunione comitato sicurezza'), ('finding_minor', 'Risoluzione non conformità minore'), ('finding_major', 'Risoluzione non conformità maggiore'), ('finding_observation', 'Risoluzione osservazione'), ('pdca_cycle', 'Ciclo PDCA'), ('kpi_review', 'Revisione KPI'), ('isms_review', 'Revisione ISMS annuale')], max_length=50)),
                ('frequency_value', models.PositiveIntegerField()),
                ('frequency_unit', models.CharField(choices=[('days', 'Giorni'), ('weeks', 'Settimane'), ('months', 'Mesi'), ('years', 'Anni')], max_length=10)),
                ('alert_days_before', models.PositiveIntegerField(default=30)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='compliance_schedule.complianceschedulepolicy')),
            ],
            options={
                'unique_together': {('policy', 'rule_type')},
            },
        ),
    ]
