# Generated by Django 5.1.15 on 2026-03-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddocument',
            name='framework',
            field=models.CharField(choices=[('ISO27001', 'ISO 27001'), ('NIS2', 'NIS2'), ('TISAX_L2', 'TISAX L2'), ('TISAX_L3', 'TISAX L3'), ('TISAX_PROTO', 'TISAX Prototype Protection')], max_length=20),
        ),
    ]
