# Generated by Django 5.1.15 on 2026-08-06 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0002_requireddocument_tisax_proto_choice'),
        ('documents', '0006_document_code'),
        ('plants', '0009_alter_plantframework_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocumentFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_fulfillments', to='documents.document')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_fulfillments', to='documents.evidence')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_doc_fulfillments', to='plants.plant')),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='compliance_schedule.requireddocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'required_document'), name='uniq_fulfillment_per_plant_req'), models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('evidence__isnull', True)), models.Q(('document__isnull', True), ('evidence__isnull', False)), _connector='OR'), name='fulfillment_exactly_one_target')],
            },
        ),
    ]
