# Generated by Django 5.2.17 on 2026-09-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_schedule', '0009_supplier_reevaluation_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerule',
            name='rule_type',
            field=models.CharField(choices=[('control_review', 'Revisione controlli'), ('control_audit', 'Audit interno controlli'), ('document_policy', 'Revisione policy'), ('document_procedure', 'Revisione procedura'), ('document_record', 'Aggiornamento registro'), ('risk_assessment', 'Rivalutazione rischi'), ('risk_treatment', 'Revisione piano trattamento'), ('bcp_test', 'Test BCP/DR'), ('bcp_review', 'Revisione piano BCP'), ('incident_review', 'Revisione incidenti chiusi'), ('supplier_assessment', 'Assessment fornitori'), ('supplier_reevaluation', 'Rivalutazione fornitori'), ('asset_maintenance', 'Manutenzione impianti e apparati'), ('training_mandatory', 'Formazione obbligatoria'), ('training_refresh', 'Aggiornamento formazione'), ('management_review', 'Revisione della direzione'), ('security_committee', 'Riunione comitato sicurezza'), ('security_objective', 'Obiettivo di sicurezza'), ('finding_minor', 'Risoluzione non conformità minore'), ('finding_major', 'Risoluzione non conformità maggiore'), ('finding_observation', 'Risoluzione osservazione'), ('pdca_cycle', 'Ciclo PDCA'), ('kpi_review', 'Revisione KPI'), ('isms_review', 'Revisione ISMS annuale')], max_length=50),
        ),
    ]
