# Generated by Django 5.1.15 on 2026-03-13 18:44

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ciso', 'CISO'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('internal_auditor', 'Auditor Interno'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable')], max_length=50)),
                ('scope_type', models.CharField(choices=[('org', 'Org'), ('bu', 'BU'), ('plant', 'Plant')], max_length=20)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('framework_refs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_assignments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityCommittee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('committee_type', models.CharField(choices=[('centrale', 'Centrale'), ('bu', 'BU')], max_length=20)),
                ('frequency', models.CharField(choices=[('mensile', 'Mensile'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale')], max_length=20)),
                ('next_meeting_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.plant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('held_at', models.DateTimeField()),
                ('verbale_doc_id', models.UUIDField(blank=True, null=True)),
                ('delibere', models.JSONField(default=list)),
                ('attendees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='governance.securitycommittee')),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
    ]
