# Generated by Django 5.1.15 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable')], max_length=50),
        ),
    ]
