# Generated by Django 5.1.15 on 2026-03-18 21:49

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_alter_roleassignment_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWorkflowPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(help_text='Tipo documento M07 (es. policy, procedura, manuale, contratto, registro, altro).', max_length=20)),
                ('scope_type', models.CharField(choices=[('org', 'Org'), ('bu', 'BU'), ('plant', 'Plant')], default='org', max_length=10)),
                ('scope_id', models.UUIDField(blank=True, help_text="Per scope_type=bu/plant contiene l'UUID della BU o del Plant.", null=True)),
                ('submit_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable')], max_length=50), blank=True, default=list, help_text='Ruoli che possono creare/inviare in revisione documenti di questo tipo nello scope indicato.', size=None)),
                ('review_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable')], max_length=50), blank=True, default=list, help_text='Ruoli che possono svolgere la revisione.', size=None)),
                ('approve_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable')], max_length=50), blank=True, default=list, help_text='Ruoli che possono approvare/mandare in vigore il documento.', size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document workflow policy',
                'verbose_name_plural': 'Document workflow policies',
                'ordering': ['document_type', 'scope_type'],
            },
        ),
    ]
