# Generated by Django 5.1.15 on 2026-06-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_documentworkflowpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleassignment',
            options={'ordering': ['-valid_from', 'role']},
        ),
        migrations.AlterModelOptions(
            name='securitycommittee',
            options={'ordering': ['name']},
        ),
    ]
