# Generated by Django 5.1.15 on 2026-06-23 20:45

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_alter_roleassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable')], max_length=50)),
                ('scope_level', models.CharField(choices=[('org', 'Org'), ('plant', 'Plant')], default='org', max_length=10)),
                ('applies_to', models.CharField(choices=[('all', 'Tutti i siti'), ('nis2_only', 'Solo siti NIS2')], default='all', help_text='Usato solo per scope_level=plant: a quali siti si applica il requisito.', max_length=20)),
                ('org_covers_sites', models.BooleanField(default=False, help_text="Solo per scope_level=plant: se True un'assegnazione org attiva copre i siti privi di nomina specifica (caso DPO); se False ogni sito va nominato (caso NIS2 Contact).")),
                ('enabled', models.BooleanField(default=True, help_text='Disattiva il requisito senza eliminarlo (escluso dalla matrice).')),
                ('framework_refs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Riferimenti normativi per evidenza audit (es. ISO27001:A.5.2).', size=None)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope_level', 'role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('role', 'scope_level'), name='uniq_active_role_requirement')],
            },
        ),
    ]
