# Generated by Django 5.1.15 on 2026-06-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_seed_role_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequirement',
            name='mandatory',
            field=models.BooleanField(default=True, help_text='Se True il ruolo è obbligatorio: la matrice segnala come lacuna i perimetri scoperti. Se False la riga serve solo a definire la policy del ruolo (es. titolare unico) senza imporne la copertura.'),
        ),
        migrations.AddField(
            model_name='rolerequirement',
            name='single_holder',
            field=models.BooleanField(default=True, help_text='Se True il ruolo ammette un solo titolare attivo per perimetro (la seconda assegnazione è bloccata: usare Sostituisci). Se False sono ammessi più titolari (es. Control Owner, membri comitato).'),
        ),
    ]
