# Generated by Django 5.2.17 on 2026-09-17 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0009_roleassignment_uniq_open_role_assignment'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
        ('tasks', '0015_checklistrun_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Es: OBJ-2026-01', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('origin', models.CharField(choices=[('politica', 'Politica di sicurezza'), ('risk_assessment', 'Valutazione del rischio'), ('audit', 'Esito di audit'), ('requisito', 'Requisito normativo o contrattuale'), ('incidente', 'Incidente'), ('riesame', 'Riesame di direzione'), ('altro', 'Altro')], default='politica', max_length=20)),
                ('source_review_id', models.UUIDField(blank=True, null=True)),
                ('measure_source', models.CharField(choices=[('kpi', 'KPI operativo (M08)'), ('manual', 'Misura manuale')], default='kpi', max_length=10)),
                ('unit', models.CharField(blank=True, help_text='Unità delle misure manuali; con un KPI si usa quella del KPI.', max_length=20)),
                ('start_date', models.DateField(help_text='Inizio del periodo di impegno.')),
                ('baseline_value', models.FloatField(blank=True, help_text='Valore di partenza, da cui si misura il progresso.', null=True)),
                ('target_value', models.FloatField()),
                ('target_direction', models.CharField(choices=[('above', 'Sopra il target = raggiunto'), ('below', 'Sotto il target = raggiunto')], default='above', max_length=5)),
                ('target_date', models.DateField(db_index=True)),
                ('owner_role', models.CharField(blank=True, help_text="Ruolo GRC che risponde dell'obiettivo (risolto via UserPlantAccess).", max_length=50)),
                ('resources', models.TextField(blank=True, help_text='Risorse necessarie (§6.2 e).')),
                ('evaluation_method', models.TextField(blank=True, help_text='Come si valuta il risultato (§6.2 f).')),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('attivo', 'Attivo'), ('raggiunto', 'Raggiunto'), ('non_raggiunto', 'Non raggiunto'), ('sospeso', 'Sospeso'), ('annullato', 'Annullato')], db_index=True, default='bozza', max_length=15)),
                ('communicated_at', models.DateTimeField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_note', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_security_objectives', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kpi_definition', models.ForeignKey(blank=True, help_text='KPI da cui leggere i valori se measure_source=kpi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_objectives', to='tasks.kpidefinition')),
                ('plant', models.ForeignKey(blank=True, help_text="Sito a cui si riferisce l'obiettivo. null = obiettivo di organizzazione, valido per tutti i siti.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_objectives', to='plants.plant')),
            ],
            options={
                'ordering': ['target_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SecurityObjectiveMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('measured_on', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='governance.securityobjective')),
            ],
            options={
                'ordering': ['-measured_on'],
            },
        ),
        migrations.AddIndex(
            model_name='securityobjective',
            index=models.Index(fields=['status', 'target_date'], name='governance__status_f16cc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityobjective',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('plant__isnull', False)), fields=('code', 'plant'), name='uniq_active_objective_code_per_plant'),
        ),
        migrations.AddConstraint(
            model_name='securityobjective',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('plant__isnull', True)), fields=('code',), name='uniq_active_objective_code_global'),
        ),
        migrations.AddConstraint(
            model_name='securityobjectivemeasurement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('objective', 'measured_on'), name='uniq_active_objective_measurement_per_day'),
        ),
    ]
