# Generated by Django 5.2.17 on 2026-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_securityobjective_securityobjectivemeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityobjective',
            name='deadline_notice_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityobjective',
            name='last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityobjective',
            name='last_track',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
