# Generated by Django 5.2.17 on 2026-09-18 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


TYPE_MAP = {"centrale": "comitato", "bu": "comitato"}


def forwards(apps, schema_editor):
    """Da comitato con un sito e riunioni a organo con perimetro e componenti.

    - il sito singolo diventa il perimetro (nessun sito = organizzazione);
    - i vecchi tipi centrale/BU erano entrambi comitati di sicurezza;
    - i presenti all'ultima riunione registrata (unica fonte dei "membri"
      fino a qui) diventano componenti in carica da quella data, così la
      Matrice Accessi non li perde.
    """
    Committee = apps.get_model("governance", "SecurityCommittee")
    Meeting = apps.get_model("governance", "CommitteeMeeting")
    Member = apps.get_model("governance", "CommitteeMember")

    for c in Committee.objects.all():
        if c.plant_id:
            c.plants.add(c.plant_id)
        new_type = TYPE_MAP.get(c.committee_type, c.committee_type)
        if new_type != c.committee_type:
            c.committee_type = new_type
            c.save(update_fields=["committee_type"])
        last = (
            Meeting.objects.filter(committee=c, deleted_at__isnull=True)
            .order_by("-held_at").first()
        )
        if last is None:
            continue
        for u in last.attendees.all():
            Member.objects.create(
                committee=c,
                full_name=(f"{u.first_name} {u.last_name}".strip() or u.email or u.username),
                user=u,
                body_role="membro",
                valid_from=last.held_at.date(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0011_securityobjective_deadline_notice_at_and_more'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycommittee',
            name='description',
            field=models.TextField(blank=True, help_text="Mandato dell'organo rispetto al sistema di gestione."),
        ),
        migrations.AddField(
            model_name='securitycommittee',
            name='plants',
            field=models.ManyToManyField(blank=True, related_name='governing_bodies', to='plants.plant'),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, help_text='Qualifica: es. Amministratore Delegato, CFO.', max_length=200)),
                ('body_role', models.CharField(choices=[('presidente', 'Presidente'), ('membro', 'Membro'), ('segretario', 'Segretario')], default='membro', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='governance.securitycommittee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['committee', 'valid_until'], name='governance__committ_e92c5b_idx'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='securitycommittee',
            name='committee_type',
            field=models.CharField(choices=[('cda', 'Organo di amministrazione (CdA)'), ('comitato', 'Comitato sicurezza'), ('direzione', 'Direzione')], default='comitato', max_length=20),
        ),
        migrations.RemoveField(
            model_name='securitycommittee',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='securitycommittee',
            name='next_meeting_at',
        ),
        migrations.RemoveField(
            model_name='securitycommittee',
            name='plant',
        ),
        migrations.DeleteModel(
            name='CommitteeMeeting',
        ),
    ]
