# Generated by Django 5.2.17 on 2026-09-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_governing_bodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentworkflowpolicy',
            name='approval_body',
            field=models.ForeignKey(blank=True, help_text='Organo competente per la delibera (CdA, comitato, direzione).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_policies', to='governance.securitycommittee'),
        ),
        migrations.AddField(
            model_name='documentworkflowpolicy',
            name='owner_can_approve',
            field=models.BooleanField(default=False, help_text="Il titolare del documento può approvarlo anche senza uno dei ruoli indicati sopra (contratti, NDA, registri a carico dell'owner)."),
        ),
        migrations.AddField(
            model_name='documentworkflowpolicy',
            name='requires_body_resolution',
            field=models.BooleanField(default=False, help_text="Documenti di questo tipo entrano in vigore solo con delibera dell'organo di governo: l'approvazione in applicazione da parte di un singolo è rifiutata."),
        ),
    ]
