# Generated by Django 5.2.17 on 2026-09-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0013_documentworkflowpolicy_approval_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentworkflowpolicy',
            name='require_distinct_reviewer',
            field=models.BooleanField(default=False, help_text="Separazione dei compiti: chi ha redatto il documento o ne ha caricato la versione in esame non può chiuderne la revisione, né approvandolo né respingendolo. La delibera dell'organo non è toccata: è un atto collegiale, non della persona che lo trascrive."),
        ),
    ]
