# Generated by Django 5.2.17 on 2026-10-02 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0014_documentworkflowpolicy_require_distinct_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentworkflowpolicy',
            name='approve_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable'), ('site_risk_manager', 'Risk Manager di sito'), ('it_manager', 'Responsabile IT'), ('hr_manager', 'Responsabile HR'), ('purchasing_manager', 'Responsabile Acquisti'), ('production_manager', 'Responsabile Produzione / Manutenzione'), ('engineering_manager', 'Responsabile Engineering')], max_length=50), blank=True, default=list, help_text='Ruoli che possono approvare/mandare in vigore il documento.', size=None),
        ),
        migrations.AlterField(
            model_name='documentworkflowpolicy',
            name='review_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable'), ('site_risk_manager', 'Risk Manager di sito'), ('it_manager', 'Responsabile IT'), ('hr_manager', 'Responsabile HR'), ('purchasing_manager', 'Responsabile Acquisti'), ('production_manager', 'Responsabile Produzione / Manutenzione'), ('engineering_manager', 'Responsabile Engineering')], max_length=50), blank=True, default=list, help_text='Ruoli che possono svolgere la revisione.', size=None),
        ),
        migrations.AlterField(
            model_name='documentworkflowpolicy',
            name='submit_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable'), ('site_risk_manager', 'Risk Manager di sito'), ('it_manager', 'Responsabile IT'), ('hr_manager', 'Responsabile HR'), ('purchasing_manager', 'Responsabile Acquisti'), ('production_manager', 'Responsabile Produzione / Manutenzione'), ('engineering_manager', 'Responsabile Engineering')], max_length=50), blank=True, default=list, help_text='Ruoli che possono creare/inviare in revisione documenti di questo tipo nello scope indicato.', size=None),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable'), ('site_risk_manager', 'Risk Manager di sito'), ('it_manager', 'Responsabile IT'), ('hr_manager', 'Responsabile HR'), ('purchasing_manager', 'Responsabile Acquisti'), ('production_manager', 'Responsabile Produzione / Manutenzione'), ('engineering_manager', 'Responsabile Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rolerequirement',
            name='role',
            field=models.CharField(choices=[('ciso', 'CISO'), ('compliance_officer', 'Compliance Officer'), ('risk_manager', 'Risk Manager'), ('internal_auditor', 'Auditor Interno'), ('external_auditor', 'Auditor Esterno'), ('plant_manager', 'Plant Manager'), ('control_owner', 'Control Owner'), ('plant_security_officer', 'Plant Security Officer'), ('nis2_contact', 'Contatto NIS2'), ('dpo', 'DPO'), ('isms_manager', 'ISMS Manager'), ('comitato_membro', 'Membro Comitato'), ('bu_referente', 'Referente BU'), ('raci_responsible', 'RACI Responsible'), ('raci_accountable', 'RACI Accountable'), ('site_risk_manager', 'Risk Manager di sito'), ('it_manager', 'Responsabile IT'), ('hr_manager', 'Responsabile HR'), ('purchasing_manager', 'Responsabile Acquisti'), ('production_manager', 'Responsabile Produzione / Manutenzione'), ('engineering_manager', 'Responsabile Engineering')], max_length=50),
        ),
    ]
