# Generated by Django 5.2.17 on 2026-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0015_alter_documentworkflowpolicy_approve_roles_and_more'),
        ('risk', '0019_clear_default_risk_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityobjective',
            name='risks',
            field=models.ManyToManyField(blank=True, help_text="Rischi che l'obiettivo tratta (origine «Valutazione del rischio»)", related_name='security_objectives', to='risk.riskassessment'),
        ),
    ]
