# Generated by Django 5.1.15 on 2026-03-13 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bia', '__first__'),
        ('plants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BcpPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('approvato', 'Approvato'), ('archiviato', 'Archiviato')], default='bozza', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rto_hours', models.IntegerField(blank=True, help_text='Recovery Time Objective in hours', null=True)),
                ('rpo_hours', models.IntegerField(blank=True, help_text='Recovery Point Objective in hours', null=True)),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('next_test_date', models.DateField(blank=True, null=True)),
                ('content', models.JSONField(default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bcps', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('critical_processes', models.ManyToManyField(blank=True, to='bia.criticalprocess')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bcp_plans', to='plants.plant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BcpTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('test_date', models.DateField()),
                ('result', models.CharField(choices=[('superato', 'Superato'), ('parziale', 'Parziale'), ('fallito', 'Fallito')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('lessons_id', models.UUIDField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='bcp.bcpplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
