# Generated by Django 5.1.15 on 2026-03-14 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0001_initial'),
        ('bia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcpplan',
            name='critical_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcp_plans', to='bia.criticalprocess'),
        ),
    ]
