# Generated by Django 5.1.15 on 2026-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0002_bcpplan_critical_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcptest',
            name='objectives',
            field=models.JSONField(default=list, help_text='List of {"text": str, "met": bool} objects'),
        ),
        migrations.AddField(
            model_name='bcptest',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bcptest',
            name='rpo_achieved_hours',
            field=models.IntegerField(blank=True, help_text='Actual RPO achieved during this test (hours)', null=True),
        ),
        migrations.AddField(
            model_name='bcptest',
            name='rto_achieved_hours',
            field=models.IntegerField(blank=True, help_text='Actual RTO achieved during this test (hours)', null=True),
        ),
        migrations.AddField(
            model_name='bcptest',
            name='test_type',
            field=models.CharField(choices=[('tabletop', 'Tabletop / Discussione'), ('drill', 'Drill / Esercitazione parziale'), ('full_interruption', 'Full interruption test'), ('parallel', 'Test parallelo')], default='tabletop', max_length=20),
        ),
    ]
