# Generated by Django 5.1.15 on 2026-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bcp", "0003_bcptest_objectives_bcptest_participants_count_and_more"),
        ("documents", "0003_alter_document_category_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcptest",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                related_name="bcp_tests",
                to="documents.evidence",
            ),
        ),
    ]

