# Generated by Django 5.1.15 on 2026-03-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bcp", "0004_bcp_test_evidences"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcpplan",
            name="test_frequency_value",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bcpplan",
            name="test_frequency_unit",
            field=models.CharField(
                choices=[("days", "Giorni"), ("weeks", "Settimane"), ("months", "Mesi"), ("years", "Anni")],
                default="years",
                max_length=10,
            ),
        ),
    ]

