# Generated by Django 5.1.15 on 2026-06-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0005_bcp_test_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcptest',
            options={'ordering': ['-test_date']},
        ),
    ]
