# Generated by Django 5.1.15 on 2026-04-24 15:12

import apps.notifications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('my_domain', 'Dominio interno'), ('supplier', 'Fornitore'), ('asset', 'Asset')], max_length=20)),
                ('source_module', models.CharField(choices=[('sites', 'Siti'), ('suppliers', 'Fornitori'), ('assets_it', 'Asset IT'), ('assets_ot', 'Asset OT'), ('assets_software', 'Asset Software')], max_length=20)),
                ('source_id', models.UUIDField(help_text="FK UUID all'entità del modulo di origine")),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('is_nis2_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='False se la sorgente è stata eliminata — preserva lo storico')),
                ('scan_frequency', models.CharField(choices=[('weekly', 'Settimanale'), ('monthly', 'Mensile')], default='weekly', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='OsintScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('running', 'In esecuzione'), ('completed', 'Completato'), ('failed', 'Fallito')], default='running', max_length=10)),
                ('ssl_valid', models.BooleanField(blank=True, null=True)),
                ('ssl_expiry_date', models.DateField(blank=True, null=True)),
                ('ssl_days_remaining', models.IntegerField(blank=True, null=True)),
                ('ssl_issuer', models.CharField(blank=True, max_length=255)),
                ('ssl_wildcard', models.BooleanField(default=False)),
                ('spf_present', models.BooleanField(blank=True, null=True)),
                ('spf_policy', models.CharField(blank=True, max_length=50)),
                ('dmarc_present', models.BooleanField(blank=True, null=True)),
                ('dmarc_policy', models.CharField(blank=True, max_length=20)),
                ('mx_present', models.BooleanField(blank=True, null=True)),
                ('dnssec_enabled', models.BooleanField(blank=True, null=True)),
                ('domain_expiry_date', models.DateField(blank=True, null=True)),
                ('domain_registrar', models.CharField(blank=True, max_length=255)),
                ('whois_privacy', models.BooleanField(blank=True, null=True)),
                ('registrar_country', models.CharField(blank=True, max_length=10)),
                ('vt_malicious', models.IntegerField(blank=True, null=True)),
                ('vt_suspicious', models.IntegerField(blank=True, null=True)),
                ('abuseipdb_score', models.IntegerField(blank=True, null=True)),
                ('abuseipdb_reports', models.IntegerField(blank=True, null=True)),
                ('otx_pulses', models.IntegerField(blank=True, null=True)),
                ('gsb_status', models.CharField(blank=True, max_length=20)),
                ('in_blacklist', models.BooleanField(default=False)),
                ('blacklist_sources', models.JSONField(blank=True, default=list)),
                ('hibp_breaches', models.IntegerField(blank=True, null=True)),
                ('hibp_latest_breach', models.DateField(blank=True, null=True)),
                ('hibp_data_types', models.JSONField(blank=True, default=list)),
                ('score_ssl', models.IntegerField(default=0)),
                ('score_dns', models.IntegerField(default=0)),
                ('score_reputation', models.IntegerField(default=0)),
                ('score_grc_context', models.IntegerField(default=0)),
                ('score_total', models.IntegerField(db_index=True, default=0)),
                ('enricher_errors', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='osint.osintentity')),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='OsintAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_type', models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto'), ('blacklist_new', 'Nuovo ingresso in blacklist'), ('dmarc_missing', 'DMARC assente'), ('score_critical', 'Score critico'), ('score_degraded', 'Score peggiorato'), ('new_subdomain', 'Nuovo sottodominio'), ('breach_found', 'Breach rilevata')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critico'), ('warning', 'Avviso'), ('info', 'Informativo')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nuovo'), ('acknowledged', 'Preso in carico'), ('resolved', 'Risolto'), ('pending_escalation', 'In attesa di escalation')], default='new', max_length=20)),
                ('linked_incident_id', models.UUIDField(blank=True, null=True)),
                ('linked_task_id', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='osint.osintentity')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='osint.osintscan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OsintSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score_threshold_critical', models.IntegerField(default=70)),
                ('score_threshold_warning', models.IntegerField(default=50)),
                ('freq_my_domains', models.CharField(choices=[('weekly', 'Settimanale'), ('monthly', 'Mensile')], default='weekly', max_length=10)),
                ('freq_suppliers_critical', models.CharField(choices=[('weekly', 'Settimanale'), ('monthly', 'Mensile')], default='weekly', max_length=10)),
                ('freq_suppliers_other', models.CharField(choices=[('weekly', 'Settimanale'), ('monthly', 'Mensile')], default='monthly', max_length=10)),
                ('subdomain_auto_include', models.CharField(choices=[('yes', 'Sì automatico'), ('no', 'No automatico'), ('ask', 'Chiedi conferma')], default='ask', max_length=5)),
                ('anonymization_enabled', models.BooleanField(default=True)),
                ('hibp_api_key', apps.notifications.models.EncryptedCharField(blank=True, default='', max_length=512)),
                ('virustotal_api_key', apps.notifications.models.EncryptedCharField(blank=True, default='', max_length=512)),
                ('abuseipdb_api_key', apps.notifications.models.EncryptedCharField(blank=True, default='', max_length=512)),
                ('gsb_api_key', apps.notifications.models.EncryptedCharField(blank=True, default='', max_length=512)),
                ('otx_api_key', apps.notifications.models.EncryptedCharField(blank=True, default='', max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OSINT Settings',
                'verbose_name_plural': 'OSINT Settings',
            },
        ),
        migrations.CreateModel(
            name='OsintSubdomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subdomain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('included', 'Incluso'), ('ignored', 'Ignorato')], default='pending', max_length=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='osint.osintentity')),
            ],
            options={
                'ordering': ['subdomain'],
            },
        ),
        migrations.AddIndex(
            model_name='osintentity',
            index=models.Index(fields=['entity_type', 'is_active'], name='osint_osint_entity__bfb050_idx'),
        ),
        migrations.AddIndex(
            model_name='osintentity',
            index=models.Index(fields=['domain'], name='osint_osint_domain_9b9104_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='osintentity',
            unique_together={('source_module', 'source_id', 'domain')},
        ),
        migrations.AddIndex(
            model_name='osintscan',
            index=models.Index(fields=['entity', '-scan_date'], name='osint_osint_entity__71eb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='osintscan',
            index=models.Index(fields=['status'], name='osint_osint_status_f1b0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='osintalert',
            index=models.Index(fields=['entity', 'status'], name='osint_osint_entity__01b7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='osintalert',
            index=models.Index(fields=['alert_type', 'status'], name='osint_osint_alert_t_17e30a_idx'),
        ),
        migrations.AddIndex(
            model_name='osintalert',
            index=models.Index(fields=['severity'], name='osint_osint_severit_b2201d_idx'),
        ),
        migrations.AddIndex(
            model_name='osintsubdomain',
            index=models.Index(fields=['status'], name='osint_osint_status_20ce5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='osintsubdomain',
            unique_together={('entity', 'subdomain')},
        ),
    ]
