# Generated by Django 5.1.15 on 2026-04-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintentity',
            name='active_alerts_count_cached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='osintentity',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='osintentity',
            name='last_score_total',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='osintentity',
            name='prev_score_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
