# Generated by Django 5.1.15 on 2026-04-25 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0002_osintentity_active_alerts_count_cached_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto/non raggiungibile'), ('dmarc_missing', 'DMARC assente'), ('dmarc_none', 'DMARC p=none'), ('spf_missing', 'SPF assente'), ('spf_plus_all', 'SPF +all (insicuro)'), ('dnssec_missing', 'DNSSEC non abilitato'), ('domain_expiry_soon', 'Dominio in scadenza'), ('blacklist', 'Dominio in blacklist'), ('vt_malicious', 'Segnalato da VirusTotal'), ('gsb_unsafe', 'Segnalato da Google Safe Browsing'), ('breach', 'Breach rilevato (HIBP)'), ('headers_missing', 'Header HTTP di sicurezza mancanti'), ('new_subdomain', 'Nuovi sottodomini in attesa'), ('lookalike_domains', 'Domini sosia attivi')], max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Critico'), ('warning', 'Avviso'), ('info', 'Informativo')], max_length=10)),
                ('params', models.JSONField(blank=True, default=dict, help_text="{'days': 12, 'issuer': '...'}")),
                ('status', models.CharField(choices=[('open', 'Aperto'), ('acknowledged', 'Preso in carico'), ('in_progress', 'In risoluzione'), ('resolved', 'Risolto'), ('accepted_risk', 'Rischio accettato')], default='open', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('accepted_risk_until', models.DateField(blank=True, null=True)),
                ('linked_task_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='osint.osintentity')),
                ('scan', models.ForeignKey(blank=True, help_text='Ultimo scan in cui il problema è stato rilevato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='osint.osintscan')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['entity', 'status'], name='osint_osint_entity__66a2eb_idx'), models.Index(fields=['code', 'status'], name='osint_osint_code_4fe272_idx'), models.Index(fields=['severity', 'status'], name='osint_osint_severit_b0d862_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'acknowledged', 'in_progress'])), fields=('entity', 'code'), name='osint_finding_one_open_per_code')],
            },
        ),
    ]
