# Generated by Django 5.1.15 on 2026-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0003_osintfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintscan',
            name='lookalike_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='security_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
