# Generated by Django 5.1.15 on 2026-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0004_osintscan_lookalike_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintsettings',
            name='ssl_expiry_warning_days',
            field=models.PositiveIntegerField(default=60, help_text='Giorni rimanenti SSL sotto i quali lo score SSL sale a 40 (attenzione).'),
        ),
    ]
