# Generated by Django 5.1.15 on 2026-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0005_osintsettings_ssl_expiry_warning_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintscan',
            name='takeover_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='osintalert',
            name='alert_type',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto'), ('blacklist_new', 'Nuovo ingresso in blacklist'), ('dmarc_missing', 'DMARC assente'), ('score_critical', 'Score critico'), ('score_degraded', 'Score peggiorato'), ('new_subdomain', 'Nuovo sottodominio'), ('breach_found', 'Breach rilevata'), ('subdomain_takeover', 'Possibile subdomain takeover')], max_length=30),
        ),
        migrations.AlterField(
            model_name='osintfinding',
            name='code',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto/non raggiungibile'), ('dmarc_missing', 'DMARC assente'), ('dmarc_none', 'DMARC p=none'), ('spf_missing', 'SPF assente'), ('spf_plus_all', 'SPF +all (insicuro)'), ('dnssec_missing', 'DNSSEC non abilitato'), ('domain_expiry_soon', 'Dominio in scadenza'), ('blacklist', 'Dominio in blacklist'), ('vt_malicious', 'Segnalato da VirusTotal'), ('gsb_unsafe', 'Segnalato da Google Safe Browsing'), ('breach', 'Breach rilevato (HIBP)'), ('headers_missing', 'Header HTTP di sicurezza mancanti'), ('new_subdomain', 'Nuovi sottodomini in attesa'), ('lookalike_domains', 'Domini sosia attivi'), ('subdomain_takeover', 'Possibile subdomain takeover')], max_length=40),
        ),
    ]
