# Generated by Django 5.1.15 on 2026-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0006_osintscan_takeover_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintscan',
            name='dkim_present',
            field=models.BooleanField(blank=True, help_text='True se almeno un selettore DKIM comune espone un record v=DKIM1.', null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='dkim_selectors_found',
            field=models.JSONField(blank=True, default=list, help_text="Selettori DKIM trovati tra quelli sondati (es. ['default', 'google'])."),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='mta_sts_present',
            field=models.BooleanField(blank=True, help_text='True se esiste il record TXT _mta-sts (v=STSv1).', null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='tls_rpt_present',
            field=models.BooleanField(blank=True, help_text='True se esiste il record TXT _smtp._tls (v=TLSRPTv1).', null=True),
        ),
        migrations.AlterField(
            model_name='osintfinding',
            name='code',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto/non raggiungibile'), ('dmarc_missing', 'DMARC assente'), ('dmarc_none', 'DMARC p=none'), ('spf_missing', 'SPF assente'), ('spf_plus_all', 'SPF +all (insicuro)'), ('dkim_missing', 'DKIM assente'), ('mta_sts_missing', 'MTA-STS assente'), ('dnssec_missing', 'DNSSEC non abilitato'), ('domain_expiry_soon', 'Dominio in scadenza'), ('blacklist', 'Dominio in blacklist'), ('vt_malicious', 'Segnalato da VirusTotal'), ('gsb_unsafe', 'Segnalato da Google Safe Browsing'), ('breach', 'Breach rilevato (HIBP)'), ('headers_missing', 'Header HTTP di sicurezza mancanti'), ('new_subdomain', 'Nuovi sottodomini in attesa'), ('lookalike_domains', 'Domini sosia attivi'), ('subdomain_takeover', 'Possibile subdomain takeover')], max_length=40),
        ),
    ]
