# Generated by Django 5.1.15 on 2026-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0007_osintscan_dkim_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintsettings',
            name='score_threshold_attention',
            field=models.IntegerField(default=30, help_text="Score ≥ questo valore (ma < warning) → 'attention'. Sotto → 'ok'."),
        ),
        migrations.AddField(
            model_name='osintsettings',
            name='weight_dns',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='osintsettings',
            name='weight_grc',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='osintsettings',
            name='weight_reputation',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='osintsettings',
            name='weight_ssl',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
