# Generated by Django 5.1.15 on 2026-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0009_osintscan_ct_recent_certs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintscan',
            name='whois_source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
