# Generated by Django 5.1.15 on 2026-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0011_osintscan_threatfox_iocs_osintscan_threatfox_malware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintsettings',
            name='enricher_health',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
