# Generated by Django 5.2.17 on 2026-08-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0012_osintsettings_enricher_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintscan',
            name='http_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='https_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osintalert',
            name='alert_type',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto'), ('no_https', 'Sito senza HTTPS'), ('blacklist_new', 'Nuovo ingresso in blacklist'), ('dmarc_missing', 'DMARC assente'), ('score_critical', 'Score critico'), ('score_degraded', 'Score peggiorato'), ('new_subdomain', 'Nuovo sottodominio'), ('breach_found', 'Breach rilevata'), ('subdomain_takeover', 'Possibile subdomain takeover'), ('ct_unexpected_issuer', 'Certificato da CA non attesa (CT)'), ('threatfox_listed', 'IoC malware attivo (abuse.ch ThreatFox)'), ('urlhaus_listed', "URL malware sull'host (abuse.ch URLhaus)")], max_length=30),
        ),
        migrations.AlterField(
            model_name='osintfinding',
            name='code',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto/non raggiungibile'), ('no_https', 'Sito servito in HTTP puro (nessun HTTPS)'), ('dmarc_missing', 'DMARC assente'), ('dmarc_none', 'DMARC p=none'), ('spf_missing', 'SPF assente'), ('spf_plus_all', 'SPF +all (insicuro)'), ('dkim_missing', 'DKIM assente'), ('mta_sts_missing', 'MTA-STS assente'), ('dnssec_missing', 'DNSSEC non abilitato'), ('domain_expiry_soon', 'Dominio in scadenza'), ('blacklist', 'Dominio in blacklist'), ('vt_malicious', 'Segnalato da VirusTotal'), ('gsb_unsafe', 'Segnalato da Google Safe Browsing'), ('breach', 'Breach rilevato (HIBP)'), ('headers_missing', 'Header HTTP di sicurezza mancanti'), ('new_subdomain', 'Nuovi sottodomini in attesa'), ('lookalike_domains', 'Domini sosia attivi'), ('subdomain_takeover', 'Possibile subdomain takeover'), ('ct_unexpected_issuer', 'Certificato da CA non attesa (CT)'), ('threatfox_listed', 'IoC malware attivo (abuse.ch ThreatFox)'), ('urlhaus_listed', "URL malware sull'host (abuse.ch URLhaus)")], max_length=40),
        ),
    ]
