# Generated by Django 5.2.17 on 2026-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0013_osintscan_http_only_osintscan_https_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintentity',
            name='expected_mail',
            field=models.CharField(choices=[('unknown', 'Non dichiarato'), ('yes', 'Atteso'), ('no', 'Non atteso')], default='unknown', help_text='Il dominio è atteso gestire posta? Non dichiarato = si usa ciò che si rileva.', max_length=10),
        ),
        migrations.AddField(
            model_name='osintentity',
            name='expected_web',
            field=models.CharField(choices=[('unknown', 'Non dichiarato'), ('yes', 'Atteso'), ('no', 'Non atteso')], default='unknown', help_text='Il dominio è atteso servire un sito? Non dichiarato = si usa ciò che si rileva.', max_length=10),
        ),
    ]
