# Generated by Django 5.2.17 on 2026-08-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0014_osintentity_expected_mail_osintentity_expected_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintentity',
            name='duplicate_candidate_of',
            field=models.ForeignKey(blank=True, help_text='Entità di cui questa potrebbe essere un alias (www/apex).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_candidates', to='osint.osintentity'),
        ),
        migrations.AddField(
            model_name='osintentity',
            name='duplicate_verified',
            field=models.BooleanField(blank=True, help_text='True = confermato alias, False = verificato distinto, None = da verificare.', null=True),
        ),
    ]
