# Generated by Django 5.2.17 on 2026-09-25 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0015_osintentity_duplicate_candidate_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='osintfinding',
            name='osint_finding_one_open_per_code',
        ),
        migrations.AddField(
            model_name='osintfinding',
            name='report_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='osintfinding',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintfinding',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='osintfinding',
            name='status',
            field=models.CharField(choices=[('open', 'Aperto'), ('acknowledged', 'Preso in carico'), ('in_progress', 'In risoluzione'), ('resolved', 'Risolto'), ('accepted_risk', 'Rischio accettato'), ('reported', 'Segnalato al fornitore')], default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='osintfinding',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'acknowledged', 'in_progress', 'reported'])), fields=('entity', 'code'), name='osint_finding_one_open_per_code'),
        ),
    ]
