# Generated by Django 5.2.17 on 2026-09-25 13:25

from django.db import migrations, models

# Controlli di "facciata" che sui fornitori generavano rumore: da ora
# confluiscono nella dimensione Maturità e non producono problemi. I finding
# ancora aperti su fornitori con questi codici vengono tolti (soft delete).
SUPPLIER_NOISE_CODES = [
    "ssl_expiry", "ssl_expired", "no_https", "headers_missing", "dnssec_missing",
    "mta_sts_missing", "dkim_missing", "dmarc_missing", "dmarc_none", "spf_missing",
    "spf_plus_all", "new_subdomain", "ct_unexpected_issuer",
]


def drop_supplier_noise(apps, schema_editor):
    from django.utils import timezone
    OsintFinding = apps.get_model("osint", "OsintFinding")
    OsintFinding.objects.filter(
        entity__entity_type="supplier", code__in=SUPPLIER_NOISE_CODES,
        status__in=["open", "acknowledged", "in_progress", "reported"], deleted_at__isnull=True,
    ).update(deleted_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0016_finding_reported_to_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintentity',
            name='deep_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osintentity',
            name='service_hosts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='hibp_domain_breaches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='ransomware_hits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='remote_access',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='score_compromise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='score_exposure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='score_impersonation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='score_maturity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='service_checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='osintfinding',
            name='code',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto/non raggiungibile'), ('no_https', 'Sito servito in HTTP puro (nessun HTTPS)'), ('dmarc_missing', 'DMARC assente'), ('dmarc_none', 'DMARC p=none'), ('spf_missing', 'SPF assente'), ('spf_plus_all', 'SPF +all (insicuro)'), ('dkim_missing', 'DKIM assente'), ('mta_sts_missing', 'MTA-STS assente'), ('dnssec_missing', 'DNSSEC non abilitato'), ('domain_expiry_soon', 'Dominio in scadenza'), ('blacklist', 'Dominio in blacklist'), ('vt_malicious', 'Segnalato da VirusTotal'), ('gsb_unsafe', 'Segnalato da Google Safe Browsing'), ('breach', 'Breach rilevato (HIBP)'), ('headers_missing', 'Header HTTP di sicurezza mancanti'), ('new_subdomain', 'Nuovi sottodomini in attesa'), ('lookalike_domains', 'Domini sosia attivi'), ('subdomain_takeover', 'Possibile subdomain takeover'), ('ct_unexpected_issuer', 'Certificato da CA non attesa (CT)'), ('threatfox_listed', 'IoC malware attivo (abuse.ch ThreatFox)'), ('urlhaus_listed', "URL malware sull'host (abuse.ch URLhaus)"), ('domain_spoofable', 'Dominio falsificabile (DMARC non in blocco)'), ('ransomware_victim', 'Vittima di ransomware (leak site)'), ('service_breach', 'Violazione dati del servizio (HIBP)'), ('remote_access_kev', 'Accesso remoto con vulnerabilità sfruttata (CISA KEV)'), ('admin_service_exposed', 'Servizio di amministrazione esposto (RDP/SMB/Telnet)'), ('service_cert', 'Certificato scaduto su un servizio usato')], max_length=40),
        ),
        migrations.CreateModel(
            name='OsintRansomwareVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim', models.CharField(max_length=300)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('discovered', models.DateTimeField(db_index=True)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('name_key', models.CharField(db_index=True, help_text='Nome normalizzato per il confronto', max_length=300)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-discovered'],
                'constraints': [models.UniqueConstraint(fields=('group', 'victim'), name='osint_rw_victim_unique')],
            },
        ),
        migrations.RunPython(drop_supplier_noise, migrations.RunPython.noop),
    ]
