# Generated by Django 5.2.17 on 2026-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0018_osint_kpis_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintscan',
            name='ssl_trusted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osintscan',
            name='ssl_verify_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='osintfinding',
            name='code',
            field=models.CharField(choices=[('ssl_expiry', 'SSL in scadenza'), ('ssl_expired', 'SSL scaduto/non raggiungibile'), ('ssl_untrusted', 'Certificato non verificabile (catena incompleta o CA non riconosciuta)'), ('no_https', 'Sito servito in HTTP puro (nessun HTTPS)'), ('dmarc_missing', 'DMARC assente'), ('dmarc_none', 'DMARC p=none'), ('spf_missing', 'SPF assente'), ('spf_plus_all', 'SPF +all (insicuro)'), ('dkim_missing', 'DKIM assente'), ('mta_sts_missing', 'MTA-STS assente'), ('dnssec_missing', 'DNSSEC non abilitato'), ('domain_expiry_soon', 'Dominio in scadenza'), ('blacklist', 'Dominio in blacklist'), ('vt_malicious', 'Segnalato da VirusTotal'), ('gsb_unsafe', 'Segnalato da Google Safe Browsing'), ('breach', 'Breach rilevato (HIBP)'), ('headers_missing', 'Header HTTP di sicurezza mancanti'), ('new_subdomain', 'Nuovi sottodomini in attesa'), ('lookalike_domains', 'Domini sosia attivi'), ('subdomain_takeover', 'Possibile subdomain takeover'), ('ct_unexpected_issuer', 'Certificato da CA non attesa (CT)'), ('threatfox_listed', 'IoC malware attivo (abuse.ch ThreatFox)'), ('urlhaus_listed', "URL malware sull'host (abuse.ch URLhaus)"), ('domain_spoofable', 'Dominio falsificabile (DMARC non in blocco)'), ('ransomware_victim', 'Vittima di ransomware (leak site)'), ('service_breach', 'Violazione dati del servizio (HIBP)'), ('remote_access_kev', 'Accesso remoto con vulnerabilità sfruttata (CISA KEV)'), ('admin_service_exposed', 'Servizio di amministrazione esposto (RDP/SMB/Telnet)'), ('service_cert', 'Certificato scaduto su un servizio usato')], max_length=40),
        ),
    ]
