# Generated by Django 5.1.15 on 2026-03-14 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0002_initial'),
        ('risk', '0002_risk_scenario_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='critical_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='bia.criticalprocess'),
        ),
    ]
