# Generated by Django 5.1.15 on 2026-03-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_riskassessment_owner_alter_riskassessment_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='inherent_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1 – Trascurabile'), (2, '2 – Minore'), (3, '3 – Moderato'), (4, '4 – Grave'), (5, '5 – Critico')], help_text='Impatto senza considerare i controlli esistenti', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='inherent_probability',
            field=models.IntegerField(blank=True, choices=[(1, '1 – Molto bassa'), (2, '2 – Bassa'), (3, '3 – Media'), (4, '4 – Alta'), (5, '5 – Molto alta')], help_text='Probabilità senza considerare i controlli esistenti', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='inherent_score',
            field=models.IntegerField(blank=True, help_text='Score inerente = inherent_prob × inherent_impact', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_acceptance_expiry',
            field=models.DateField(blank=True, help_text='Data scadenza accettazione rischio — va rinnovata', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_acceptance_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formally_accepted_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_accepted_formally',
            field=models.BooleanField(default=False),
        ),
    ]
