# Generated by Django 5.1.15 on 2026-03-15 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('risk', '0005_riskassessment_inherent_impact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAppetitePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('framework_code', models.CharField(blank=True, help_text='Blank = valida per tutti i framework', max_length=50)),
                ('max_acceptable_score', models.IntegerField(default=14, help_text='Score massimo accettabile senza PDCA obbligatorio.')),
                ('max_red_risks_count', models.IntegerField(default=3, help_text='Numero massimo di rischi rossi tollerabili contemporaneamente.')),
                ('max_unacceptable_score', models.IntegerField(default=20, help_text="Score oltre il quale il rischio NON puo' essere solo accettato.")),
                ('review_frequency_months', models.IntegerField(default=12)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risk_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, help_text='Null = policy org-wide valida per tutti i plant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_appetite_policies', to='plants.plant')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
