# Generated by Django 5.1.15 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_riskassessment_needs_revaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='assessment_type',
            field=models.CharField(choices=[('IT', 'IT'), ('OT', 'OT')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='score',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('completato', 'Completato'), ('archiviato', 'Archiviato')], db_index=True, default='bozza', max_length=20),
        ),
    ]
