# Generated by Django 5.1.15 on 2026-03-18 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_change_portal_url_asset_last_change_date_and_more'),
        ('bia', '0003_criticalprocess_mbco_pct_criticalprocess_mtpd_hours_and_more'),
        ('plants', '0001_initial'),
        ('risk', '0008_alter_riskassessment_assessment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('threat_category', models.CharField(blank=True, choices=[('accesso_non_autorizzato', 'Accesso non autorizzato'), ('malware_ransomware', 'Malware / Ransomware'), ('data_breach', 'Data breach / Fuga di dati'), ('phishing_social', 'Phishing / Social engineering'), ('guasto_hw_sw', 'Guasto hardware / software'), ('disastro_naturale', 'Disastro naturale / ambientale'), ('errore_umano', 'Errore umano'), ('attacco_supply_chain', 'Attacco supply chain'), ('ddos', 'DoS / DDoS'), ('insider_threat', 'Insider threat'), ('furto_perdita', 'Furto / perdita dispositivi'), ('altro', 'Altro')], default='', max_length=50)),
                ('likelihood', models.IntegerField(blank=True, choices=[(1, '1 – Molto bassa'), (2, '2 – Bassa'), (3, '3 – Media'), (4, '4 – Alta'), (5, '5 – Molto alta')], help_text='Probabilità scenario (1-5)', null=True)),
                ('impact', models.IntegerField(blank=True, choices=[(1, '1 – Trascurabile'), (2, '2 – Minore'), (3, '3 – Moderato'), (4, '4 – Grave'), (5, '5 – Critico')], help_text='Impatto scenario (1-5)', null=True)),
                ('risk_score', models.IntegerField(blank=True, help_text='Score scenario = likelihood × impact', null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_scenarios', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('critical_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_scenarios', to='bia.criticalprocess')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scenarios', to='plants.plant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
