# Generated by Django 5.1.15 on 2026-03-18 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0009_riskscenario"),
        ("bcp", "0005_bcp_test_frequency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="riskmitigationplan",
            name="bcp_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_mitigation_plans",
                to="bcp.bcpplan",
            ),
        ),
    ]

