# Generated by Django 5.1.15 on 2026-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_risk_mitigation_bcp_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='consequence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='impacted_systems',
            field=models.TextField(blank=True, default='', help_text='Sistemi/servizi NIS2 impattati (testo libero)'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='nis2_art21_category',
            field=models.CharField(blank=True, choices=[('art21_a', 'Art.21(2)(a) – Analisi dei rischi e policy ISMS'), ('art21_b', 'Art.21(2)(b) – Gestione incidenti'), ('art21_c', 'Art.21(2)(c) – Continuità operativa e BCP/DR'), ('art21_d', 'Art.21(2)(d) – Supply chain'), ('art21_e', 'Art.21(2)(e) – Sicurezza acquisizione e manutenzione sistemi'), ('art21_f', 'Art.21(2)(f) – Verifica efficacia delle misure di sicurezza'), ('art21_g', 'Art.21(2)(g) – Igiene informatica e formazione'), ('art21_h', 'Art.21(2)(h) – Crittografia e protezione dati'), ('art21_i', 'Art.21(2)(i) – Controllo accessi, IAM e gestione asset'), ('art21_j', 'Art.21(2)(j) – MFA e comunicazioni sicure')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='nis2_relevance',
            field=models.CharField(blank=True, choices=[('non_significativo', 'Non significativo'), ('potenzialmente_significativo', 'Potenzialmente significativo'), ('significativo', 'Significativo')], default='', max_length=40),
        ),
    ]
