# Generated by Django 5.1.15 on 2026-06-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_nis2_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='riskdimension',
            options={'ordering': ['assessment_id', 'dimension_code']},
        ),
        migrations.AlterModelOptions(
            name='riskmitigationplan',
            options={'ordering': ['-created_at']},
        ),
    ]
