# Generated by Django 5.2.17 on 2026-10-01 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_alter_riskassessment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='treatment_owner',
            field=models.ForeignKey(blank=True, help_text='Responsabile del trattamento (utente del portale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treated_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='treatment_owner_external',
            field=models.CharField(blank=True, default='', help_text='Responsabile del trattamento non utente del portale (testo libero)', max_length=200),
        ),
        migrations.AddField(
            model_name='riskmitigationplan',
            name='owner_external',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
