# Generated by Django 5.2.17 on 2026-10-02 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0004_alter_criticalprocess_options_and_more'),
        ('governance', '0015_alter_documentworkflowpolicy_approve_roles_and_more'),
        ('management_review', '0011_targeted_outcome_error'),
        ('plants', '0011_alter_plant_country'),
        ('risk', '0013_treatment_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='legacy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='InformationClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('owner_role', models.CharField(blank=True, default='', help_text="Ruolo normativo dell'owner (governance.NormativeRole)", max_length=50)),
                ('confidentiality', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('very_high', 'Very high')], default='normal', max_length=10)),
                ('integrity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('very_high', 'Very high')], default='normal', max_length=10)),
                ('availability', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('very_high', 'Very high')], default='normal', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('critical_processes', models.ManyToManyField(blank=True, related_name='information_classes', to='bia.criticalprocess')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_information_classes', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_classes', to='plants.plant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('primo', 'Primo risk assessment'), ('periodico', 'Revisione periodica'), ('straordinario', 'Revisione straordinaria'), ('legacy', 'Valutazione precedente (metodo superato)')], max_length=20)),
                ('trigger_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('in_corso', 'In corso'), ('in_approvazione', 'In approvazione'), ('approvato', 'Approvato'), ('archiviato', 'Archiviato')], db_index=True, default='in_corso', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('local_adoption_ref', models.CharField(blank=True, default='', help_text="Delibera di recepimento dell'organo della società (società estere)", max_length=300)),
                ('approval_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risk_cycles', to='management_review.managementreview')),
                ('approved_by_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risk_cycles', to='governance.securitycommittee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_cycles', to='plants.plant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='risk.riskassessmentcycle'),
        ),
        migrations.CreateModel(
            name='RiskGovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('preset', models.CharField(choices=[('centralizzato', 'Centralizzato'), ('federato', 'Federato'), ('sito_singolo', 'Sito singolo')], default='centralizzato', max_length=20)),
                ('group_register_enabled', models.BooleanField(blank=True, null=True)),
                ('acceptance_matrix', models.JSONField(blank=True, default=dict)),
                ('upper_opinion', models.JSONField(blank=True, default=dict)),
                ('acceptance_max_months', models.JSONField(blank=True, default=dict)),
                ('economic_thresholds', models.JSONField(blank=True, default=dict)),
                ('overdue_escalation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('review_frequency_months', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risk_governance_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_governance_policies', to='plants.plant')),
            ],
            options={
                'ordering': ['plant_id'],
            },
        ),
        migrations.CreateModel(
            name='ThreatCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30)),
                ('asset_types', models.JSONField(default=list, help_text='Tipologie di asset a cui si applica')),
                ('cia', models.JSONField(default=list, help_text='Proprietà colpite: C, I, A')),
                ('translations', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('catalog', 'Catalogo'), ('custom', 'Personalizzata')], default='custom', max_length=10)),
                ('catalog_version', models.CharField(blank=True, default='', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='riskassessmentcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['in_corso', 'in_approvazione'])), fields=('plant',), name='uniq_open_risk_cycle_per_register', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='riskgovernancepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plant',), name='uniq_active_risk_governance_policy_per_scope', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='threatcatalogentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_active_threat_code'),
        ),
    ]
