# Generated by Django 5.2.17 on 2026-10-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_evaluation_and_acceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdimension',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='riskdimension',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='riskscenario',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='riskscenario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='riskscenario',
            name='critical_process',
        ),
        migrations.RemoveField(
            model_name='riskscenario',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='ale_annuo',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='inherent_impact',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='inherent_probability',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='inherent_score',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='needs_revaluation',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='needs_revaluation_since',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='nis2_relevance',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_acceptance_expiry',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_acceptance_note',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_accepted',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_accepted_at',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_accepted_by',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_accepted_formally',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='threat_category',
        ),
        migrations.DeleteModel(
            name='RiskAppetitePolicy',
        ),
        migrations.DeleteModel(
            name='RiskDimension',
        ),
        migrations.DeleteModel(
            name='RiskScenario',
        ),
    ]
