# Generated by Django 5.2.17 on 2026-10-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0012_reviewagendaitem_risk_acceptance_and_more'),
        ('risk', '0023_remote_access_single_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskacceptance',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_acceptances', to='management_review.managementreview'),
        ),
    ]
