# Generated by Django 5.1.15 on 2026-03-15 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0001_initial'),
        ('controls', '0006_controlinstance_applicability_and_more'),
        ('documents', '0002_document_document_type_evidence'),
        ('lessons', '0002_lessonlearned_source_id_lessonlearned_source_module'),
        ('pdca', '0002_pdcacycle_act_description_pdcacycle_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('finding_type', models.CharField(choices=[('major_nc', 'Major Non Conformity'), ('minor_nc', 'Minor Non Conformity'), ('observation', 'Observation'), ('opportunity', 'Opportunity for Improvement')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('auditor_name', models.CharField(blank=True, max_length=200)),
                ('audit_date', models.DateField()),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Aperto'), ('in_response', 'In risposta'), ('closed', 'Chiuso'), ('accepted_by_auditor', "Accettato dall'auditor")], default='open', max_length=25)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('audit_prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit_prep.auditprep')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_findings', to=settings.AUTH_USER_MODEL)),
                ('closure_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_findings', to='documents.evidence')),
                ('control_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='controls.controlinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson_learned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='lessons.lessonlearned')),
                ('pdca_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='pdca.pdcacycle')),
            ],
            options={
                'ordering': ['-audit_date', 'finding_type'],
            },
        ),
    ]
