# Generated by Django 5.1.15 on 2026-03-15 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0002_auditfinding'),
        ('controls', '0006_controlinstance_applicability_and_more'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('approvato', 'Approvato'), ('in_corso', 'In corso'), ('completato', 'Completato')], default='bozza', max_length=15)),
                ('objectives', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('planned_audits', models.JSONField(default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_audit_programs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_programs', to='controls.framework')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_programs', to='plants.plant')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('plant', 'framework', 'year')},
            },
        ),
    ]
