# Generated by Django 5.1.15 on 2026-03-23 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0003_auditprogram'),
        ('controls', '0008_alter_controlinstance_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auditprogram',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='auditprep',
            name='audit_entry_id',
            field=models.CharField(blank=True, help_text='ID audit pianificato nel programma (UUID JSON)', max_length=36),
        ),
        migrations.AddField(
            model_name='auditprep',
            name='audit_program',
            field=models.ForeignKey(blank=True, help_text='Programma annuale di provenienza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preps', to='audit_prep.auditprogram'),
        ),
        migrations.AddField(
            model_name='auditprep',
            name='coverage_type',
            field=models.CharField(choices=[('campione', 'Campione 25%'), ('esteso', 'Esteso 50%'), ('full', 'Full 100%')], default='campione', max_length=10),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='coverage_type',
            field=models.CharField(choices=[('campione', 'Campione (20-30% dei controlli)'), ('esteso', 'Esteso (50% dei controlli)'), ('full', 'Full (100% dei controlli)')], default='campione', max_length=10),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='frameworks',
            field=models.ManyToManyField(blank=True, help_text='Framework coperti dal programma (multi-framework)', related_name='audit_programs', to='controls.framework'),
        ),
        migrations.AlterField(
            model_name='auditprep',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_preps', to='controls.framework'),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='framework',
            field=models.ForeignKey(blank=True, help_text='Framework primario (legacy — usa frameworks M2M)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_programs_primary', to='controls.framework'),
        ),
    ]
