# Generated by Django 5.1.15 on 2026-04-29 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0004_alter_auditprogram_unique_together_and_more'),
        ('plants', '0007_plant_additional_domains_plant_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('frameworks_requested', models.JSONField(default=list)),
                ('frameworks_expanded', models.JSONField(default=list)),
                ('scope', models.JSONField(default=list)),
                ('since', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'In coda'), ('running', 'In generazione'), ('ready', 'Pronto'), ('failed', 'Fallito'), ('expired', 'Scaduto')], default='queued', max_length=15)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('pack_sha256', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_audit_packs', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_packs', to='plants.plant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
