# Generated by Django 5.1.15 on 2026-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0005_auditpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='auto_generated',
            field=models.BooleanField(db_index=True, default=False, help_text="True se il finding e' stato creato automaticamente da auto_validate_prep"),
        ),
    ]
