# Generated by Django 5.1.15 on 2026-06-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0006_auditfinding_auto_generated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidenceitem',
            options={'ordering': ['created_at']},
        ),
    ]
