# Generated by Django 5.2.17 on 2026-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0007_alter_evidenceitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='status',
            field=models.CharField(choices=[('mancante', 'Mancante'), ('presente', 'Presente'), ('scaduto', 'Scaduto'), ('na', 'Non applicabile')], default='mancante', max_length=10),
        ),
    ]
