# Generated by Django 5.2.17 on 2026-09-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0008_alter_evidenceitem_status'),
        ('documents', '0009_documentapproval_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprep',
            name='audit_type',
            field=models.CharField(choices=[('interno', 'Audit interno (prima parte)'), ('seconda_parte', 'Seconda parte (cliente)'), ('terza_parte', 'Terza parte (certificazione)')], default='interno', help_text="Chi conduce l'audit: interno, cliente (seconda parte) o ente di certificazione", max_length=15),
        ),
        migrations.AddField(
            model_name='auditprep',
            name='report_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to='documents.evidence'),
        ),
        migrations.AddField(
            model_name='auditprep',
            name='requesting_party',
            field=models.CharField(blank=True, help_text="Committente: il cliente per cui è svolto l'audit di seconda parte (può differire dall'ente che lo esegue)", max_length=200),
        ),
    ]
