# Generated by Django 5.2.17 on 2026-09-24 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0009_auditprep_audit_type_auditprep_report_evidence_and_more'),
        ('controls', '0014_controlinstance_implementation_interview'),
        ('documents', '0009_documentapproval_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='common_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('audit_type', models.CharField(default='interno', max_length=15)),
                ('requesting_party', models.CharField(blank=True, max_length=200)),
                ('auditor_name', models.CharField(blank=True, max_length=200)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('scope_id', models.CharField(blank=True, help_text="Identificativo del perimetro dell'assessment (es. TISAX Scope ID)", max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_groups', to='controls.framework')),
                ('report_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_group_reports', to='documents.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditprep',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preps', to='audit_prep.auditgroup'),
        ),
    ]
