# Generated by Django 5.2.17 on 2026-09-25 07:04

from django.db import migrations, models


def standalone_full_coverage(apps, schema_editor):
    """L'audit singolo (non lanciato da un programma) è a copertura completa:
    il campione vale solo nei programmi a più step. Cambia l'etichetta; le
    voci di checklist già create restano come sono."""
    AuditPrep = apps.get_model("audit_prep", "AuditPrep")
    AuditPrep.objects.filter(audit_program__isnull=True).exclude(coverage_type="full").update(
        coverage_type="full",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0010_auditfinding_common_key_auditgroup_auditprep_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup',
            name='external_consultant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditprep',
            name='external_consultant',
            field=models.BooleanField(default=False, help_text="Solo per l'audit interno: condotto da un consulente esterno (niente checklist, si registrano i rilievi del consulente)"),
        ),
        migrations.RunPython(standalone_full_coverage, migrations.RunPython.noop),
    ]
