# Generated by Django 5.2.17 on 2026-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_prep', '0011_external_consultant_full_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('open', 'Aperto'), ('in_response', 'In risposta'), ('closed', 'Chiuso'), ('accepted_by_auditor', "Accettato dall'auditor"), ('not_pursued', 'Non perseguito')], default='open', max_length=25),
        ),
    ]
