# Generated by Django 5.1.15 on 2026-03-13 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField()),
                ('function', models.CharField(max_length=50)),
                ('module_source', models.CharField(max_length=5)),
                ('entity_id', models.UUIDField()),
                ('model_used', models.CharField(max_length=100)),
                ('input_hash', models.CharField(max_length=64)),
                ('output_ai', models.TextField()),
                ('output_human_final', models.TextField(blank=True, null=True)),
                ('delta', models.JSONField(blank=True, null=True)),
                ('confirmed_by_id', models.UUIDField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ignored', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ai_interaction_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
