# Generated by Django 5.1.15 on 2026-03-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiProviderConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="Configurazione AI principale", max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "cloud_provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI (GPT)"),
                            ("groq", "Groq (Llama/Mixtral)"),
                            ("google", "Google (Gemini)"),
                            ("mistral", "Mistral AI"),
                            ("ollama", "Ollama (locale)"),
                        ],
                        default="anthropic",
                        max_length=20,
                    ),
                ),
                ("cloud_model", models.CharField(default="claude-haiku-4-5-20251001", max_length=100)),
                ("api_key", models.TextField(blank=True, help_text="API Key cifrata AES-256")),
                ("azure_endpoint", models.URLField(blank=True)),
                ("azure_deployment", models.CharField(blank=True, max_length=100)),
                ("local_endpoint", models.URLField(default="http://172.17.0.1:11434")),
                ("local_model", models.CharField(default="llama3.2:3b", max_length=100)),
                ("monthly_token_budget", models.IntegerField(default=100000, help_text="Token cloud massimi al mese")),
                ("tokens_used_month", models.IntegerField(default=0)),
                ("budget_reset_day", models.IntegerField(default=1, help_text="Giorno del mese per reset budget")),
                ("last_budget_reset", models.DateField(blank=True, null=True)),
                (
                    "fallback_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Automatico — passa a Ollama se cloud non disponibile"),
                            ("notify", "Notifica — chiedi conferma prima del fallback"),
                            ("disabled", "Disabilitato — mostra errore se cloud non disponibile"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("fallback_notified", models.BooleanField(default=False)),
                ("task_routing", models.JSONField(default=dict, help_text="Routing per tipo task: ollama | cloud")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
