# Generated by Django 5.1.15 on 2026-03-24 09:37

import apps.notifications.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aiproviderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='api_key',
            field=apps.notifications.models.EncryptedCharField(blank=True, help_text='API Key cifrata AES-256', max_length=512),
        ),
    ]
