from django.db import models
from core.models import BaseModel


class IsmsKpiSnapshot(BaseModel):
    """Weekly ISMS KPI snapshot generated by Celery beat every Monday at 06:00."""

    plant = models.ForeignKey(
        "plants.Plant",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="NULL = org-wide snapshot",
    )
    week_start = models.DateField(help_text="Monday of the snapshot week")
    framework_code = models.CharField(max_length=50)

    # Controls
    controls_total = models.IntegerField(default=0)
    controls_compliant = models.IntegerField(default=0)
    controls_gap = models.IntegerField(default=0)
    pct_compliant = models.FloatField(default=0.0)
    overall_maturity = models.FloatField(
        null=True, blank=True, help_text="Average maturity_level of ControlInstances"
    )

    # Risk
    open_risks = models.IntegerField(default=0)
    high_risks = models.IntegerField(default=0)

    # Incidents
    open_incidents = models.IntegerField(default=0)
    critical_incidents = models.IntegerField(default=0)

    # Versione della regola di calcolo della conformità: 1 = compliant/totale
    # con N/A nel denominatore (fino alla 0.9.x); 2 = regola unica di
    # `apps.controls.services.effective_control_rows`. Le serie storiche le
    # distinguono per non confrontare numeri calcolati in modo diverso.
    method_version = models.PositiveSmallIntegerField(default=1)

    snapshot_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [("plant", "framework_code", "week_start")]
        ordering = ["-week_start"]

    def __str__(self):
        plant_label = self.plant.code if self.plant else "ORG"
        return f"KPI {plant_label}/{self.framework_code} w={self.week_start}"
