"""
Catalogo statico dei KPI standard suggeribili in base ai framework attivi.

NON è un modello Django: sono dati Python puri, nessuna migrazione. Usato da
KpiSuggestView/KpiImportSuggestionsView per proporre KPI pre-configurati con
soglie e razionale normativo.

Ogni entry contiene testi localizzati in IT/EN/FR/PL/TR per name, description,
rationale e checklist_hint, più i metadati (unit, aggregation, soglie, sorgente,
categoria, frameworks di riferimento) e `match_keywords` per il collegamento
automatico a un ChecklistTemplate esistente.

Lingue supportate.
"""

LANGS = ("it", "en", "fr", "pl", "tr")

# Categorie usate per raggruppare i suggerimenti nel wizard frontend.
CATEGORIES = (
    "operations",
    "incident",
    "vulnerability",
    "access",
    "compliance",
    "training",
    "supplier",
    "continuity",
    "facility",
)


KPI_CATALOG = {
    # ───────────────────────── OPERATIONS ──────────────────────────────────
    "backup_success_rate": {
        "name": {
            "it": "Tasso di successo backup",
            "en": "Backup Success Rate",
            "fr": "Taux de succès des sauvegardes",
            "pl": "Wskaźnik sukcesu kopii zapasowych",
            "tr": "Yedekleme Başarı Oranı",
        },
        "description": {
            "it": "Percentuale di backup completati con successo sul totale pianificati nel periodo.",
            "en": "Percentage of backups completed successfully out of total scheduled in the period.",
            "fr": "Pourcentage de sauvegardes réussies sur le total planifié sur la période.",
            "pl": "Odsetek pomyślnie ukończonych kopii zapasowych względem zaplanowanych w okresie.",
            "tr": "Dönemde planlanan toplam yedeklemeye göre başarıyla tamamlananların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 99.0,
        "threshold_critical": 95.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "checklist",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["backup", "salvataggi"],
        "rationale": {
            "it": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — la continuità operativa richiede backup verificati con frequenza documentata.",
            "en": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — operational continuity requires verified backups with documented frequency.",
            "fr": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — la continuité opérationnelle exige des sauvegardes vérifiées à fréquence documentée.",
            "pl": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — ciągłość działania wymaga zweryfikowanych kopii zapasowych o udokumentowanej częstotliwości.",
            "tr": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Md.21(2)(c) — operasyonel süreklilik, belgelenmiş sıklıkta doğrulanmış yedekleme gerektirir.",
        },
        "checklist_hint": {
            "it": "Collega al template checklist 'Verifica backup notturno' se presente.",
            "en": "Link to checklist template 'Nightly backup verification' if present.",
            "fr": "Lier au modèle de checklist « Vérification de la sauvegarde nocturne » si présent.",
            "pl": "Połącz z szablonem listy kontrolnej „Weryfikacja nocnej kopii zapasowej”, jeśli istnieje.",
            "tr": "Varsa 'Gecelik yedekleme doğrulaması' kontrol listesi şablonuna bağlayın.",
        },
        "template_seed": {
            "frequency": "daily",
            "name": {
                "it": "Verifica backup notturno",
                "en": "Nightly backup verification",
                "fr": "Vérification de la sauvegarde nocturne",
                "pl": "Weryfikacja nocnej kopii zapasowej",
                "tr": "Gecelik yedekleme doğrulaması",
            },
            "items": [
                {
                    "item_type": "checkbox",
                    "is_mandatory": True,
                    "unit": "",
                    "text": {
                        "it": "Backup notturno completato senza errori",
                        "en": "Nightly backup completed without errors",
                        "fr": "Sauvegarde nocturne terminée sans erreur",
                        "pl": "Nocna kopia zapasowa ukończona bez błędów",
                        "tr": "Gecelik yedekleme hatasız tamamlandı",
                    },
                },
            ],
        },
    },
    "backup_restore_test_age_days": {
        "name": {
            "it": "Anzianità ultimo test di ripristino",
            "en": "Last Restore Test Age",
            "fr": "Ancienneté du dernier test de restauration",
            "pl": "Wiek ostatniego testu odtwarzania",
            "tr": "Son Geri Yükleme Testi Yaşı",
        },
        "description": {
            "it": "Giorni trascorsi dall'ultimo test di ripristino backup eseguito con successo.",
            "en": "Days elapsed since the last successful backup restore test.",
            "fr": "Jours écoulés depuis le dernier test de restauration de sauvegarde réussi.",
            "pl": "Liczba dni od ostatniego udanego testu odtwarzania kopii zapasowej.",
            "tr": "Son başarılı yedek geri yükleme testinden bu yana geçen gün sayısı.",
        },
        "unit": "giorni",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 30.0,
        "threshold_critical": 90.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "checklist",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["ripristino", "restore", "backup"],
        "rationale": {
            "it": "ISO 27001 cl.8.13 — il ripristino deve essere testato periodicamente per garantire l'effettiva recuperabilità dei dati.",
            "en": "ISO 27001 cl.8.13 — restore must be tested periodically to ensure data is actually recoverable.",
            "fr": "ISO 27001 cl.8.13 — la restauration doit être testée périodiquement pour garantir la récupérabilité effective des données.",
            "pl": "ISO 27001 cl.8.13 — odtwarzanie musi być okresowo testowane, aby zapewnić rzeczywistą odzyskiwalność danych.",
            "tr": "ISO 27001 cl.8.13 — verilerin gerçekten kurtarılabilir olduğundan emin olmak için geri yükleme periyodik test edilmelidir.",
        },
        "checklist_hint": {
            "it": "Collega al template checklist di test ripristino trimestrale se presente.",
            "en": "Link to the quarterly restore-test checklist template if present.",
            "fr": "Lier au modèle de checklist de test de restauration trimestriel si présent.",
            "pl": "Połącz z kwartalnym szablonem listy kontrolnej testu odtwarzania, jeśli istnieje.",
            "tr": "Varsa üç aylık geri yükleme testi kontrol listesi şablonuna bağlayın.",
        },
        "template_seed": {
            "frequency": "monthly",
            "name": {
                "it": "Test ripristino backup",
                "en": "Backup restore test",
                "fr": "Test de restauration de sauvegarde",
                "pl": "Test odtwarzania kopii zapasowej",
                "tr": "Yedek geri yükleme testi",
            },
            "items": [
                {
                    "item_type": "numeric",
                    "is_mandatory": True,
                    "unit": "giorni",
                    "text": {
                        "it": "Giorni dall'ultimo test di ripristino completato",
                        "en": "Days since the last completed restore test",
                        "fr": "Jours depuis le dernier test de restauration réalisé",
                        "pl": "Dni od ostatniego ukończonego testu odtwarzania",
                        "tr": "Son tamamlanan geri yükleme testinden bu yana gün",
                    },
                },
            ],
        },
    },
    "patch_critical_compliance_rate": {
        "name": {
            "it": "Conformità patch critiche",
            "en": "Critical Patch Compliance",
            "fr": "Conformité des correctifs critiques",
            "pl": "Zgodność krytycznych poprawek",
            "tr": "Kritik Yama Uyumluluğu",
        },
        "description": {
            "it": "Percentuale di patch critiche applicate entro l'SLA sul totale rilasciate.",
            "en": "Percentage of critical patches applied within SLA out of total released.",
            "fr": "Pourcentage de correctifs critiques appliqués dans le SLA sur le total publié.",
            "pl": "Odsetek krytycznych poprawek wdrożonych w ramach SLA względem wszystkich wydanych.",
            "tr": "Yayımlanan toplam kritik yamadan SLA içinde uygulananların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 85.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["patch", "aggiornament", "update"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — le vulnerabilità tecniche devono essere corrette tempestivamente secondo SLA basati sul rischio.",
            "en": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — technical vulnerabilities must be remediated promptly per risk-based SLAs.",
            "fr": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — les vulnérabilités techniques doivent être corrigées rapidement selon des SLA fondés sur le risque.",
            "pl": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — podatności techniczne należy usuwać niezwłocznie zgodnie z SLA opartymi na ryzyku.",
            "tr": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Md.21(2)(e) — teknik açıklar, riske dayalı SLA'lara göre derhal giderilmelidir.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dal sistema di patch management (es. WSUS/SCCM).",
            "en": "Populated via API ingest from the patch management system (e.g. WSUS/SCCM).",
            "fr": "Alimenté via l'API depuis le système de gestion des correctifs (ex. WSUS/SCCM).",
            "pl": "Zasilane przez API z systemu zarządzania poprawkami (np. WSUS/SCCM).",
            "tr": "Yama yönetim sisteminden (ör. WSUS/SCCM) API ile beslenir.",
        },
    },
    "systems_eol_count": {
        "name": {
            "it": "Sistemi a fine vita (EOL)",
            "en": "End-of-Life Systems",
            "fr": "Systèmes en fin de vie (EOL)",
            "pl": "Systemy wycofane (EOL)",
            "tr": "Kullanım Ömrü Biten Sistemler",
        },
        "description": {
            "it": "Numero di sistemi/software non più supportati dal vendor in esercizio.",
            "en": "Number of vendor-unsupported (EOL) systems/software still in operation.",
            "fr": "Nombre de systèmes/logiciels non supportés par l'éditeur encore en production.",
            "pl": "Liczba systemów/oprogramowania bez wsparcia producenta wciąż używanych.",
            "tr": "Hâlâ kullanımda olan, üretici desteği biten sistem/yazılım sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["eol", "obsolescen", "fine vita"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 — i sistemi non più supportati non ricevono patch di sicurezza e vanno dismessi o isolati.",
            "en": "ISO 27001 cl.8.8 — unsupported systems no longer receive security patches and must be decommissioned or isolated.",
            "fr": "ISO 27001 cl.8.8 — les systèmes non supportés ne reçoivent plus de correctifs et doivent être retirés ou isolés.",
            "pl": "ISO 27001 cl.8.8 — niewspierane systemy nie otrzymują poprawek i muszą zostać wycofane lub odizolowane.",
            "tr": "ISO 27001 cl.8.8 — desteklenmeyen sistemler güvenlik yaması almaz; devre dışı bırakılmalı veya yalıtılmalıdır.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dall'inventario asset (M04) o CMDB.",
            "en": "Populated via API ingest from the asset inventory (M04) or CMDB.",
            "fr": "Alimenté via l'API depuis l'inventaire des actifs (M04) ou la CMDB.",
            "pl": "Zasilane przez API z inwentarza zasobów (M04) lub CMDB.",
            "tr": "Varlık envanterinden (M04) veya CMDB'den API ile beslenir.",
        },
    },
    # ───────────────────────── INCIDENT ────────────────────────────────────
    "incident_mttd_hours": {
        "name": {
            "it": "MTTD — Tempo medio di rilevazione",
            "en": "MTTD — Mean Time To Detect",
            "fr": "MTTD — Temps moyen de détection",
            "pl": "MTTD — Średni czas wykrycia",
            "tr": "MTTD — Ortalama Tespit Süresi",
        },
        "description": {
            "it": "Ore medie tra l'insorgenza e la rilevazione di un incidente di sicurezza.",
            "en": "Average hours between onset and detection of a security incident.",
            "fr": "Heures moyennes entre la survenue et la détection d'un incident de sécurité.",
            "pl": "Średnia liczba godzin między wystąpieniem a wykryciem incydentu bezpieczeństwa.",
            "tr": "Bir güvenlik olayının başlaması ile tespiti arasındaki ortalama saat.",
        },
        "unit": "ore",
        "aggregation": "avg_value",
        "threshold_direction": "below",
        "threshold_warning": 24.0,
        "threshold_critical": 72.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["incident", "rilevazione", "detect"],
        "rationale": {
            "it": "NIS2 Art.23 / ISO 27001 cl.5.24 — la rilevazione tempestiva (entro 24h per incidenti significativi) abilita la notifica preliminare.",
            "en": "NIS2 Art.23 / ISO 27001 cl.5.24 — timely detection (within 24h for significant incidents) enables the early warning notification.",
            "fr": "NIS2 Art.23 / ISO 27001 cl.5.24 — une détection rapide (sous 24h pour les incidents significatifs) permet l'alerte précoce.",
            "pl": "NIS2 Art.23 / ISO 27001 cl.5.24 — szybkie wykrycie (w ciągu 24h dla istotnych incydentów) umożliwia wczesne ostrzeżenie.",
            "tr": "NIS2 Md.23 / ISO 27001 cl.5.24 — zamanında tespit (önemli olaylar için 24 saat içinde) erken uyarı bildirimini sağlar.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Incidenti (M09) e inviato via ingest API.",
            "en": "Computed from the Incidents module (M09) and sent via API ingest.",
            "fr": "Calculé depuis le module Incidents (M09) et envoyé via l'API.",
            "pl": "Obliczane w module Incydenty (M09) i wysyłane przez API.",
            "tr": "Olaylar modülünden (M09) hesaplanır ve API ile gönderilir.",
        },
    },
    "incident_mttr_hours": {
        "name": {
            "it": "MTTR — Tempo medio di risoluzione",
            "en": "MTTR — Mean Time To Resolve",
            "fr": "MTTR — Temps moyen de résolution",
            "pl": "MTTR — Średni czas rozwiązania",
            "tr": "MTTR — Ortalama Çözüm Süresi",
        },
        "description": {
            "it": "Ore medie tra rilevazione e risoluzione di un incidente di sicurezza.",
            "en": "Average hours between detection and resolution of a security incident.",
            "fr": "Heures moyennes entre détection et résolution d'un incident de sécurité.",
            "pl": "Średnia liczba godzin między wykryciem a rozwiązaniem incydentu bezpieczeństwa.",
            "tr": "Bir güvenlik olayının tespiti ile çözümü arasındaki ortalama saat.",
        },
        "unit": "ore",
        "aggregation": "avg_value",
        "threshold_direction": "below",
        "threshold_warning": 72.0,
        "threshold_critical": 168.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["incident", "risoluzione", "resolve"],
        "rationale": {
            "it": "NIS2 Art.23 / ISO 27001 cl.5.26 — la risoluzione entro 72h supporta la notifica intermedia e limita l'impatto.",
            "en": "NIS2 Art.23 / ISO 27001 cl.5.26 — resolution within 72h supports the interim notification and limits impact.",
            "fr": "NIS2 Art.23 / ISO 27001 cl.5.26 — une résolution sous 72h soutient la notification intermédiaire et limite l'impact.",
            "pl": "NIS2 Art.23 / ISO 27001 cl.5.26 — rozwiązanie w ciągu 72h wspiera powiadomienie pośrednie i ogranicza skutki.",
            "tr": "NIS2 Md.23 / ISO 27001 cl.5.26 — 72 saat içinde çözüm ara bildirimi destekler ve etkiyi sınırlar.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Incidenti (M09) e inviato via ingest API.",
            "en": "Computed from the Incidents module (M09) and sent via API ingest.",
            "fr": "Calculé depuis le module Incidents (M09) et envoyé via l'API.",
            "pl": "Obliczane w module Incydenty (M09) i wysyłane przez API.",
            "tr": "Olaylar modülünden (M09) hesaplanır ve API ile gönderilir.",
        },
    },
    "incident_rca_completion_rate": {
        "name": {
            "it": "Completamento RCA incidenti",
            "en": "Incident RCA Completion Rate",
            "fr": "Taux d'achèvement des RCA d'incidents",
            "pl": "Wskaźnik ukończenia RCA incydentów",
            "tr": "Olay Kök Neden Analizi Tamamlama Oranı",
        },
        "description": {
            "it": "Percentuale di incidenti significativi con analisi della causa radice completata.",
            "en": "Percentage of significant incidents with a completed root-cause analysis.",
            "fr": "Pourcentage d'incidents significatifs avec une analyse des causes racines terminée.",
            "pl": "Odsetek istotnych incydentów z ukończoną analizą przyczyn źródłowych.",
            "tr": "Kök neden analizi tamamlanmış önemli olayların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["rca", "causa radice", "root cause"],
        "rationale": {
            "it": "ISO 27001 cl.10.2 / cl.5.27 — ogni incidente significativo richiede analisi della causa radice e azione correttiva.",
            "en": "ISO 27001 cl.10.2 / cl.5.27 — every significant incident requires root-cause analysis and corrective action.",
            "fr": "ISO 27001 cl.10.2 / cl.5.27 — chaque incident significatif exige une analyse des causes racines et une action corrective.",
            "pl": "ISO 27001 cl.10.2 / cl.5.27 — każdy istotny incydent wymaga analizy przyczyn źródłowych i działań korygujących.",
            "tr": "ISO 27001 cl.10.2 / cl.5.27 — her önemli olay kök neden analizi ve düzeltici faaliyet gerektirir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Incidenti/Lessons (M09/M12) via ingest API.",
            "en": "Computed from the Incidents/Lessons modules (M09/M12) via API ingest.",
            "fr": "Calculé depuis les modules Incidents/Lessons (M09/M12) via l'API.",
            "pl": "Obliczane z modułów Incydenty/Lekcje (M09/M12) przez API.",
            "tr": "Olaylar/Çıkarımlar modüllerinden (M09/M12) API ile hesaplanır.",
        },
    },
    "incident_recurrence_rate": {
        "name": {
            "it": "Tasso di ricorrenza incidenti",
            "en": "Incident Recurrence Rate",
            "fr": "Taux de récurrence des incidents",
            "pl": "Wskaźnik nawrotów incydentów",
            "tr": "Olay Tekrarlanma Oranı",
        },
        "description": {
            "it": "Percentuale di incidenti ricorrenti (stessa causa radice) sul totale del periodo.",
            "en": "Percentage of recurring incidents (same root cause) out of the period total.",
            "fr": "Pourcentage d'incidents récurrents (même cause racine) sur le total de la période.",
            "pl": "Odsetek nawracających incydentów (ta sama przyczyna) względem sumy w okresie.",
            "tr": "Dönem toplamına göre tekrarlayan (aynı kök neden) olayların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "count_fail",
        "threshold_direction": "below",
        "threshold_warning": 5.0,
        "threshold_critical": 15.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["ricorrenza", "recurrence"],
        "rationale": {
            "it": "ISO 27001 cl.5.27 / cl.10.1 — incidenti ricorrenti indicano azioni correttive inefficaci e mancato apprendimento.",
            "en": "ISO 27001 cl.5.27 / cl.10.1 — recurring incidents indicate ineffective corrective actions and lack of learning.",
            "fr": "ISO 27001 cl.5.27 / cl.10.1 — les incidents récurrents révèlent des actions correctives inefficaces et un manque d'apprentissage.",
            "pl": "ISO 27001 cl.5.27 / cl.10.1 — nawracające incydenty wskazują na nieskuteczne działania korygujące i brak wniosków.",
            "tr": "ISO 27001 cl.5.27 / cl.10.1 — tekrarlayan olaylar etkisiz düzeltici faaliyetlere ve öğrenememeye işaret eder.",
        },
        "checklist_hint": {
            "it": "Calcolato dai moduli Incidenti/Lessons (M09/M12) via ingest API.",
            "en": "Computed from the Incidents/Lessons modules (M09/M12) via API ingest.",
            "fr": "Calculé depuis les modules Incidents/Lessons (M09/M12) via l'API.",
            "pl": "Obliczane z modułów Incydenty/Lekcje (M09/M12) przez API.",
            "tr": "Olaylar/Çıkarımlar modüllerinden (M09/M12) API ile hesaplanır.",
        },
    },
    # ───────────────────────── VULNERABILITY ───────────────────────────────
    "vuln_critical_open_count": {
        "name": {
            "it": "Vulnerabilità critiche aperte",
            "en": "Open Critical Vulnerabilities",
            "fr": "Vulnérabilités critiques ouvertes",
            "pl": "Otwarte krytyczne podatności",
            "tr": "Açık Kritik Açıklar",
        },
        "description": {
            "it": "Numero di vulnerabilità critiche attualmente aperte (non rimediate).",
            "en": "Number of critical vulnerabilities currently open (not remediated).",
            "fr": "Nombre de vulnérabilités critiques actuellement ouvertes (non corrigées).",
            "pl": "Liczba krytycznych podatności obecnie otwartych (nieusuniętych).",
            "tr": "Şu anda açık (giderilmemiş) kritik açık sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "vulnerability",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["vuln", "vulnerab"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — le vulnerabilità critiche devono essere rimediate entro tempi definiti (tipicamente 15gg).",
            "en": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — critical vulnerabilities must be remediated within defined timelines (typically 15 days).",
            "fr": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — les vulnérabilités critiques doivent être corrigées dans des délais définis (généralement 15 jours).",
            "pl": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — krytyczne podatności należy usuwać w określonym czasie (zwykle 15 dni).",
            "tr": "ISO 27001 cl.8.8 / NIS2 Md.21(2)(e) — kritik açıklar tanımlı sürelerde (genellikle 15 gün) giderilmelidir.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dallo scanner di vulnerabilità o dal modulo OSINT.",
            "en": "Populated via API ingest from the vulnerability scanner or the OSINT module.",
            "fr": "Alimenté via l'API depuis le scanner de vulnérabilités ou le module OSINT.",
            "pl": "Zasilane przez API ze skanera podatności lub modułu OSINT.",
            "tr": "Açık tarayıcısından veya OSINT modülünden API ile beslenir.",
        },
    },
    "vuln_critical_sla_compliance": {
        "name": {
            "it": "Conformità SLA vulnerabilità critiche",
            "en": "Critical Vulnerability SLA Compliance",
            "fr": "Conformité SLA des vulnérabilités critiques",
            "pl": "Zgodność SLA krytycznych podatności",
            "tr": "Kritik Açık SLA Uyumluluğu",
        },
        "description": {
            "it": "Percentuale di vulnerabilità critiche rimediate entro l'SLA definito.",
            "en": "Percentage of critical vulnerabilities remediated within the defined SLA.",
            "fr": "Pourcentage de vulnérabilités critiques corrigées dans le SLA défini.",
            "pl": "Odsetek krytycznych podatności usuniętych w ramach zdefiniowanego SLA.",
            "tr": "Tanımlı SLA içinde giderilen kritik açıkların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 85.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "vulnerability",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["vuln", "sla"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 — l'efficacia del processo di gestione vulnerabilità si misura sul rispetto degli SLA di remediation.",
            "en": "ISO 27001 cl.8.8 — the effectiveness of vulnerability management is measured by adherence to remediation SLAs.",
            "fr": "ISO 27001 cl.8.8 — l'efficacité de la gestion des vulnérabilités se mesure au respect des SLA de correction.",
            "pl": "ISO 27001 cl.8.8 — skuteczność zarządzania podatnościami mierzy się przestrzeganiem SLA usuwania.",
            "tr": "ISO 27001 cl.8.8 — açık yönetiminin etkinliği, giderme SLA'larına uyumla ölçülür.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dal sistema di vulnerability management.",
            "en": "Populated via API ingest from the vulnerability management system.",
            "fr": "Alimenté via l'API depuis le système de gestion des vulnérabilités.",
            "pl": "Zasilane przez API z systemu zarządzania podatnościami.",
            "tr": "Açık yönetim sisteminden API ile beslenir.",
        },
    },
    "vapt_age_days": {
        "name": {
            "it": "Anzianità ultimo VA/PT",
            "en": "Last VA/PT Age",
            "fr": "Ancienneté du dernier VA/PT",
            "pl": "Wiek ostatniego VA/PT",
            "tr": "Son VA/PT Yaşı",
        },
        "description": {
            "it": "Giorni trascorsi dall'ultimo Vulnerability Assessment / Penetration Test.",
            "en": "Days elapsed since the last Vulnerability Assessment / Penetration Test.",
            "fr": "Jours écoulés depuis le dernier Vulnerability Assessment / Penetration Test.",
            "pl": "Liczba dni od ostatniego testu VA/PT.",
            "tr": "Son Zafiyet Değerlendirmesi / Sızma Testinden bu yana geçen gün.",
        },
        "unit": "giorni",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 180.0,
        "threshold_critical": 365.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "vulnerability",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["vapt", "penetration", "pentest"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — i test di sicurezza (VA/PT) vanno eseguiti con cadenza almeno annuale.",
            "en": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — security testing (VA/PT) must be performed at least annually.",
            "fr": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — les tests de sécurité (VA/PT) doivent être réalisés au moins annuellement.",
            "pl": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — testy bezpieczeństwa (VA/PT) należy wykonywać co najmniej raz w roku.",
            "tr": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — güvenlik testleri (VA/PT) en az yılda bir yapılmalıdır.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API o registrato in una checklist di pianificazione VA/PT.",
            "en": "Populated via API ingest or recorded in a VA/PT planning checklist.",
            "fr": "Alimenté via l'API ou enregistré dans une checklist de planification VA/PT.",
            "pl": "Zasilane przez API lub rejestrowane w liście kontrolnej planowania VA/PT.",
            "tr": "API ile beslenir veya VA/PT planlama kontrol listesinde kaydedilir.",
        },
    },
    # ───────────────────────── ACCESS & IDENTITY ───────────────────────────
    "zombie_accounts_count": {
        "name": {
            "it": "Account dormienti (zombie)",
            "en": "Zombie Accounts",
            "fr": "Comptes dormants (zombies)",
            "pl": "Konta uśpione (zombie)",
            "tr": "Atıl (Zombi) Hesaplar",
        },
        "description": {
            "it": "Numero di account attivi ma inutilizzati da oltre 90 giorni.",
            "en": "Number of accounts that are active but unused for more than 90 days.",
            "fr": "Nombre de comptes actifs mais inutilisés depuis plus de 90 jours.",
            "pl": "Liczba kont aktywnych, lecz nieużywanych od ponad 90 dni.",
            "tr": "Aktif ancak 90 günden fazla kullanılmayan hesap sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "access",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["account", "utenz", "zombie"],
        "rationale": {
            "it": "ISO 27001 cl.5.18 / cl.8.2 — i diritti di accesso vanno riesaminati; gli account inattivi >90gg vanno disabilitati.",
            "en": "ISO 27001 cl.5.18 / cl.8.2 — access rights must be reviewed; accounts inactive >90 days must be disabled.",
            "fr": "ISO 27001 cl.5.18 / cl.8.2 — les droits d'accès doivent être revus ; les comptes inactifs >90j doivent être désactivés.",
            "pl": "ISO 27001 cl.5.18 / cl.8.2 — prawa dostępu należy przeglądać; konta nieaktywne >90 dni należy wyłączyć.",
            "tr": "ISO 27001 cl.5.18 / cl.8.2 — erişim hakları gözden geçirilmeli; 90 günden fazla atıl hesaplar devre dışı bırakılmalıdır.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dall'IdP/AD (es. review accessi periodica).",
            "en": "Populated via API ingest from the IdP/AD (e.g. periodic access review).",
            "fr": "Alimenté via l'API depuis l'IdP/AD (ex. revue d'accès périodique).",
            "pl": "Zasilane przez API z IdP/AD (np. okresowy przegląd dostępu).",
            "tr": "IdP/AD'den API ile beslenir (ör. periyodik erişim incelemesi).",
        },
    },
    "offboarding_access_revocation_rate": {
        "name": {
            "it": "Revoca accessi a fine rapporto",
            "en": "Offboarding Access Revocation Rate",
            "fr": "Taux de révocation des accès au départ",
            "pl": "Wskaźnik odbierania dostępu przy offboardingu",
            "tr": "İşten Ayrılışta Erişim İptal Oranı",
        },
        "description": {
            "it": "Percentuale di offboarding con accessi revocati entro 24h dalla cessazione.",
            "en": "Percentage of offboardings with access revoked within 24h of termination.",
            "fr": "Pourcentage de départs avec accès révoqués sous 24h après la fin du contrat.",
            "pl": "Odsetek offboardingów z dostępem odebranym w ciągu 24h od zakończenia.",
            "tr": "İş ilişkisi bitiminden sonra 24 saat içinde erişimi iptal edilen ayrılışların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 95.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "checklist",
        "category": "access",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["offboarding", "cessazion", "revoca"],
        "rationale": {
            "it": "ISO 27001 cl.6.5 / cl.5.18 — alla cessazione del rapporto i diritti di accesso devono essere revocati tempestivamente.",
            "en": "ISO 27001 cl.6.5 / cl.5.18 — upon termination of employment, access rights must be revoked promptly.",
            "fr": "ISO 27001 cl.6.5 / cl.5.18 — à la fin du contrat, les droits d'accès doivent être révoqués sans délai.",
            "pl": "ISO 27001 cl.6.5 / cl.5.18 — po zakończeniu zatrudnienia prawa dostępu należy niezwłocznie odebrać.",
            "tr": "ISO 27001 cl.6.5 / cl.5.18 — iş ilişkisinin bitiminde erişim hakları derhal iptal edilmelidir.",
        },
        "checklist_hint": {
            "it": "Collega al template checklist di offboarding HR/IT se presente.",
            "en": "Link to the HR/IT offboarding checklist template if present.",
            "fr": "Lier au modèle de checklist d'offboarding RH/IT si présent.",
            "pl": "Połącz z szablonem listy kontrolnej offboardingu HR/IT, jeśli istnieje.",
            "tr": "Varsa İK/BT işten ayrılış kontrol listesi şablonuna bağlayın.",
        },
        "template_seed": {
            "frequency": "weekly",
            "name": {
                "it": "Offboarding — revoca accessi",
                "en": "Offboarding — access revocation",
                "fr": "Offboarding — révocation des accès",
                "pl": "Offboarding — odebranie dostępu",
                "tr": "İşten ayrılış — erişim iptali",
            },
            "items": [
                {
                    "item_type": "checkbox",
                    "is_mandatory": True,
                    "unit": "",
                    "text": {
                        "it": "Accessi revocati entro 24h dalla cessazione",
                        "en": "Access revoked within 24h of termination",
                        "fr": "Accès révoqués sous 24h après la fin du contrat",
                        "pl": "Dostęp odebrany w ciągu 24h od zakończenia",
                        "tr": "İş bitiminden sonra 24 saat içinde erişim iptal edildi",
                    },
                },
            ],
        },
    },
    "privileged_accounts_count": {
        "name": {
            "it": "Account privilegiati",
            "en": "Privileged Accounts",
            "fr": "Comptes à privilèges",
            "pl": "Konta uprzywilejowane",
            "tr": "Ayrıcalıklı Hesaplar",
        },
        "description": {
            "it": "Numero di account con privilegi amministrativi (monitoraggio del trend).",
            "en": "Number of accounts with administrative privileges (trend monitoring).",
            "fr": "Nombre de comptes à privilèges administratifs (suivi de tendance).",
            "pl": "Liczba kont z uprawnieniami administracyjnymi (monitorowanie trendu).",
            "tr": "Yönetici ayrıcalıklarına sahip hesap sayısı (eğilim izleme).",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": None,
        "threshold_critical": None,
        "notify_on_warning": False,
        "notify_on_critical": False,
        "source": "api",
        "category": "access",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["privileg", "admin"],
        "rationale": {
            "it": "ISO 27001 cl.8.2 — gli accessi privilegiati vanno limitati e monitorati nel tempo (least privilege).",
            "en": "ISO 27001 cl.8.2 — privileged access must be restricted and monitored over time (least privilege).",
            "fr": "ISO 27001 cl.8.2 — les accès à privilèges doivent être limités et suivis dans le temps (moindre privilège).",
            "pl": "ISO 27001 cl.8.2 — dostęp uprzywilejowany należy ograniczać i monitorować w czasie (najmniejsze uprawnienia).",
            "tr": "ISO 27001 cl.8.2 — ayrıcalıklı erişim kısıtlanmalı ve zaman içinde izlenmelidir (en az ayrıcalık).",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dall'IdP/PAM; soglie da personalizzare per plant.",
            "en": "Populated via API ingest from the IdP/PAM; thresholds to customize per plant.",
            "fr": "Alimenté via l'API depuis l'IdP/PAM ; seuils à personnaliser par site.",
            "pl": "Zasilane przez API z IdP/PAM; progi do dostosowania per zakład.",
            "tr": "IdP/PAM'den API ile beslenir; eşikler tesise göre özelleştirilir.",
        },
    },
    # ───────────────────────── COMPLIANCE & CONTROLS ───────────────────────
    "controls_compliance_rate": {
        "name": {
            "it": "Tasso di conformità controlli",
            "en": "Controls Compliance Rate",
            "fr": "Taux de conformité des contrôles",
            "pl": "Wskaźnik zgodności kontroli",
            "tr": "Kontrol Uyumluluk Oranı",
        },
        "description": {
            "it": "Percentuale di controlli in stato 'compliant' sul totale applicabile.",
            "en": "Percentage of controls in 'compliant' status out of total applicable.",
            "fr": "Pourcentage de contrôles « conformes » sur le total applicable.",
            "pl": "Odsetek kontroli w statusie „zgodny” względem wszystkich obowiązujących.",
            "tr": "Uygulanabilir toplam içinde 'uyumlu' durumdaki kontrollerin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 85.0,
        "threshold_critical": 70.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["controll", "compliance"],
        "rationale": {
            "it": "ISO 27001 cl.9.1 — l'efficacia dell'ISMS richiede monitoraggio e misurazione continui della conformità dei controlli.",
            "en": "ISO 27001 cl.9.1 — ISMS effectiveness requires continuous monitoring and measurement of controls compliance.",
            "fr": "ISO 27001 cl.9.1 — l'efficacité du SMSI exige un suivi et une mesure continus de la conformité des contrôles.",
            "pl": "ISO 27001 cl.9.1 — skuteczność SZBI wymaga ciągłego monitorowania i pomiaru zgodności kontroli.",
            "tr": "ISO 27001 cl.9.1 — BGYS etkinliği, kontrol uyumunun sürekli izlenmesini ve ölçülmesini gerektirir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Controlli (M03) e inviato via ingest API.",
            "en": "Computed from the Controls module (M03) and sent via API ingest.",
            "fr": "Calculé depuis le module Contrôles (M03) et envoyé via l'API.",
            "pl": "Obliczane w module Kontrole (M03) i wysyłane przez API.",
            "tr": "Kontroller modülünden (M03) hesaplanır ve API ile gönderilir.",
        },
    },
    "evidence_expiry_rate": {
        "name": {
            "it": "Evidenze valide (non scadute)",
            "en": "Valid Evidence Rate",
            "fr": "Taux de preuves valides",
            "pl": "Wskaźnik ważnych dowodów",
            "tr": "Geçerli Kanıt Oranı",
        },
        "description": {
            "it": "Percentuale di evidenze di controllo ancora valide (non scadute) sul totale.",
            "en": "Percentage of control evidence still valid (not expired) out of total.",
            "fr": "Pourcentage de preuves de contrôle encore valides (non expirées) sur le total.",
            "pl": "Odsetek dowodów kontroli wciąż ważnych (nieprzeterminowanych) względem sumy.",
            "tr": "Toplam içinde hâlâ geçerli (süresi dolmamış) kontrol kanıtlarının yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 90.0,
        "threshold_critical": 75.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["eviden", "prove"],
        "rationale": {
            "it": "ISO 27001 cl.7.5 — le informazioni documentate (evidenze) devono essere aggiornate e non scadute per dimostrare la conformità.",
            "en": "ISO 27001 cl.7.5 — documented information (evidence) must be current and non-expired to demonstrate compliance.",
            "fr": "ISO 27001 cl.7.5 — les informations documentées (preuves) doivent être à jour et non expirées pour démontrer la conformité.",
            "pl": "ISO 27001 cl.7.5 — informacje udokumentowane (dowody) muszą być aktualne i nieprzeterminowane, by wykazać zgodność.",
            "tr": "ISO 27001 cl.7.5 — belgelenmiş bilgi (kanıt) uyumu göstermek için güncel ve süresi dolmamış olmalıdır.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Documenti/Evidenze (M07) via ingest API.",
            "en": "Computed from the Documents/Evidence module (M07) via API ingest.",
            "fr": "Calculé depuis le module Documents/Preuves (M07) via l'API.",
            "pl": "Obliczane z modułu Dokumenty/Dowody (M07) przez API.",
            "tr": "Belgeler/Kanıtlar modülünden (M07) API ile hesaplanır.",
        },
    },
    "open_pdca_over_90days": {
        "name": {
            "it": "PDCA aperti da oltre 90 giorni",
            "en": "PDCA Open Over 90 Days",
            "fr": "PDCA ouverts depuis plus de 90 jours",
            "pl": "PDCA otwarte ponad 90 dni",
            "tr": "90 Günden Uzun Açık PDCA",
        },
        "description": {
            "it": "Numero di cicli PDCA aperti da più di 90 giorni senza avanzamento.",
            "en": "Number of PDCA cycles open for more than 90 days without progress.",
            "fr": "Nombre de cycles PDCA ouverts depuis plus de 90 jours sans progression.",
            "pl": "Liczba cykli PDCA otwartych ponad 90 dni bez postępu.",
            "tr": "İlerleme olmadan 90 günden uzun açık PDCA döngüsü sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 3.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["pdca", "miglioramento"],
        "rationale": {
            "it": "ISO 27001 cl.10.1 — i PDCA bloccati indicano mancato miglioramento continuo del sistema di gestione.",
            "en": "ISO 27001 cl.10.1 — stalled PDCA cycles indicate a lack of continual improvement of the management system.",
            "fr": "ISO 27001 cl.10.1 — des cycles PDCA bloqués révèlent un défaut d'amélioration continue du système de management.",
            "pl": "ISO 27001 cl.10.1 — zablokowane cykle PDCA wskazują na brak ciągłego doskonalenia systemu zarządzania.",
            "tr": "ISO 27001 cl.10.1 — tıkanmış PDCA döngüleri yönetim sisteminin sürekli iyileştirilmediğini gösterir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo PDCA (M11) via ingest API.",
            "en": "Computed from the PDCA module (M11) via API ingest.",
            "fr": "Calculé depuis le module PDCA (M11) via l'API.",
            "pl": "Obliczane z modułu PDCA (M11) przez API.",
            "tr": "PDCA modülünden (M11) API ile hesaplanır.",
        },
    },
    "audit_findings_open_rate": {
        "name": {
            "it": "Quota finding di audit aperti",
            "en": "Open Audit Findings Rate",
            "fr": "Taux de constats d'audit ouverts",
            "pl": "Wskaźnik otwartych ustaleń audytu",
            "tr": "Açık Denetim Bulguları Oranı",
        },
        "description": {
            "it": "Percentuale di finding di audit ancora aperti sul totale registrato.",
            "en": "Percentage of audit findings still open out of the total recorded.",
            "fr": "Pourcentage de constats d'audit encore ouverts sur le total enregistré.",
            "pl": "Odsetek ustaleń audytu wciąż otwartych względem wszystkich zarejestrowanych.",
            "tr": "Kaydedilen toplam içinde hâlâ açık denetim bulgularının yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 10.0,
        "threshold_critical": 25.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["audit", "finding", "rilievo"],
        "rationale": {
            "it": "ISO 27001 cl.9.2 / cl.10.2 — i finding di audit interno richiedono azioni correttive entro tempi definiti.",
            "en": "ISO 27001 cl.9.2 / cl.10.2 — internal audit findings require corrective actions within defined timelines.",
            "fr": "ISO 27001 cl.9.2 / cl.10.2 — les constats d'audit interne exigent des actions correctives dans des délais définis.",
            "pl": "ISO 27001 cl.9.2 / cl.10.2 — ustalenia audytu wewnętrznego wymagają działań korygujących w określonym czasie.",
            "tr": "ISO 27001 cl.9.2 / cl.10.2 — iç denetim bulguları tanımlı sürelerde düzeltici faaliyet gerektirir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Audit Readiness (M17) via ingest API.",
            "en": "Computed from the Audit Readiness module (M17) via API ingest.",
            "fr": "Calculé depuis le module Audit Readiness (M17) via l'API.",
            "pl": "Obliczane z modułu Audit Readiness (M17) przez API.",
            "tr": "Denetim Hazırlığı modülünden (M17) API ile hesaplanır.",
        },
    },
    # ───────────────────────── TRAINING & AWARENESS ────────────────────────
    "training_completion_rate": {
        "name": {
            "it": "Copertura formazione obbligatoria",
            "en": "Mandatory Training Coverage",
            "fr": "Couverture de la formation obligatoire",
            "pl": "Pokrycie obowiązkowymi szkoleniami",
            "tr": "Zorunlu Eğitim Kapsamı",
        },
        "description": {
            "it": "Percentuale del personale dei gruppi destinatari coperta da un'erogazione ancora valida dei corsi obbligatori del piano formativo dell'anno.",
            "en": "Percentage of staff in the target groups covered by a still-valid session of the mandatory courses in this year's training plan.",
            "fr": "Pourcentage du personnel des groupes cibles couvert par une session encore valide des cours obligatoires du plan de formation de l'année.",
            "pl": "Odsetek pracowników grup docelowych objętych wciąż ważnym szkoleniem z obowiązkowych kursów tegorocznego planu szkoleń.",
            "tr": "Hedef gruplardaki personelin, yılın eğitim planındaki zorunlu kursların hâlâ geçerli bir oturumuyla kapsanan yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["formazione", "training", "corso"],
        "rationale": {
            "it": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 2.1.3 / NIS2 Art.21(2)(g) — tutto il personale riceve formazione di sensibilizzazione, ripetuta periodicamente e documentata.",
            "en": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 2.1.3 / NIS2 Art.21(2)(g) — all staff receive awareness training, repeated periodically and documented.",
            "fr": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 2.1.3 / NIS2 Art.21(2)(g) — tout le personnel reçoit une formation de sensibilisation, répétée périodiquement et documentée.",
            "pl": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 2.1.3 / NIS2 Art.21(2)(g) — cały personel przechodzi szkolenia świadomościowe, powtarzane okresowo i udokumentowane.",
            "tr": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 2.1.3 / NIS2 Md.21(2)(g) — tüm personel, periyodik olarak tekrarlanan ve belgelenen farkındalık eğitimi alır.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "training_plan_progress": {
        "name": {
            "it": "Avanzamento del piano formativo",
            "en": "Training Plan Progress",
            "fr": "Avancement du plan de formation",
            "pl": "Realizacja planu szkoleń",
            "tr": "Eğitim Planı İlerlemesi",
        },
        "description": {
            "it": "Percentuale delle voci del piano formativo dell'anno, già arrivate a scadenza, per cui è registrata un'erogazione.",
            "en": "Percentage of this year's training plan items, already past their due date, for which a session has been recorded.",
            "fr": "Pourcentage des éléments du plan de formation de l'année, déjà arrivés à échéance, pour lesquels une session est enregistrée.",
            "pl": "Odsetek pozycji tegorocznego planu szkoleń, których termin już minął, z zarejestrowanym szkoleniem.",
            "tr": "Yılın eğitim planında vadesi gelmiş ve oturumu kaydedilmiş kalemlerin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 90.0,
        "threshold_critical": 70.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.6.3 / cl.7.3 — il programma di sensibilizzazione è pianificato: le attività previste devono essere svolte nei tempi del piano approvato.",
            "en": "ISO 27001 A.6.3 / cl.7.3 — the awareness programme is planned: the scheduled activities must be carried out within the timelines of the approved plan.",
            "fr": "ISO 27001 A.6.3 / cl.7.3 — le programme de sensibilisation est planifié : les activités prévues doivent être réalisées dans les délais du plan approuvé.",
            "pl": "ISO 27001 A.6.3 / cl.7.3 — program świadomości jest planowany: zaplanowane działania muszą być realizowane w terminach zatwierdzonego planu.",
            "tr": "ISO 27001 A.6.3 / cl.7.3 — farkındalık programı planlıdır: öngörülen faaliyetler onaylı planın süreleri içinde gerçekleştirilmelidir.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "training_plan_overdue": {
        "name": {
            "it": "Voci del piano formativo in ritardo",
            "en": "Overdue Training Plan Items",
            "fr": "Éléments du plan de formation en retard",
            "pl": "Zaległe pozycje planu szkoleń",
            "tr": "Geciken Eğitim Planı Kalemleri",
        },
        "description": {
            "it": "Numero di voci del piano formativo oltre la scadenza senza alcuna erogazione registrata.",
            "en": "Number of training plan items past their due date with no session recorded.",
            "fr": "Nombre d'éléments du plan de formation échus sans aucune session enregistrée.",
            "pl": "Liczba pozycji planu szkoleń po terminie bez zarejestrowanego szkolenia.",
            "tr": "Vadesi geçmiş ve hiç oturumu kaydedilmemiş eğitim planı kalemi sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 3.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.6.3 / NIS2 Art.21(2)(g) — una formazione pianificata e non svolta è un impegno mancato, verificabile in audit.",
            "en": "ISO 27001 A.6.3 / NIS2 Art.21(2)(g) — planned training not delivered is a missed commitment, verifiable in audit.",
            "fr": "ISO 27001 A.6.3 / NIS2 Art.21(2)(g) — une formation planifiée et non réalisée est un engagement manqué, vérifiable en audit.",
            "pl": "ISO 27001 A.6.3 / NIS2 Art.21(2)(g) — zaplanowane, a nieprzeprowadzone szkolenie to niedotrzymane zobowiązanie, weryfikowalne w audycie.",
            "tr": "ISO 27001 A.6.3 / NIS2 Md.21(2)(g) — planlanıp yapılmayan eğitim, denetimde doğrulanabilen yerine getirilmemiş bir taahhüttür.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "phishing_click_rate": {
        "name": {
            "it": "Tasso di click su phishing simulato",
            "en": "Simulated Phishing Click Rate",
            "fr": "Taux de clic au phishing simulé",
            "pl": "Wskaźnik kliknięć w symulowany phishing",
            "tr": "Simüle Oltalama Tıklama Oranı",
        },
        "description": {
            "it": "Percentuale di e-mail cliccate sul totale inviato nell'ultima simulazione di phishing di ogni sito (ultimi 12 mesi).",
            "en": "Percentage of e-mails clicked out of those sent in each site's latest phishing simulation (last 12 months).",
            "fr": "Pourcentage d'e-mails cliqués sur le total envoyé lors de la dernière simulation de phishing de chaque site (12 derniers mois).",
            "pl": "Odsetek klikniętych e-maili spośród wysłanych w ostatniej symulacji phishingu każdego zakładu (ostatnie 12 miesięcy).",
            "tr": "Her tesisin son oltalama simülasyonunda gönderilen e-postalardan tıklananların yüzdesi (son 12 ay).",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 5.0,
        "threshold_critical": 15.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["phishing", "simulazion"],
        "rationale": {
            "it": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — l'efficacia della consapevolezza si misura con simulazioni di phishing periodiche.",
            "en": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — awareness effectiveness is measured via periodic phishing simulations.",
            "fr": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — l'efficacité de la sensibilisation se mesure par des simulations de phishing périodiques.",
            "pl": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — skuteczność świadomości mierzy się okresowymi symulacjami phishingu.",
            "tr": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — farkındalık etkinliği periyodik oltalama simülasyonlarıyla ölçülür.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "phishing_report_rate": {
        "name": {
            "it": "Tasso di segnalazione del phishing simulato",
            "en": "Simulated Phishing Report Rate",
            "fr": "Taux de signalement du phishing simulé",
            "pl": "Wskaźnik zgłoszeń symulowanego phishingu",
            "tr": "Simüle Oltalama Bildirim Oranı",
        },
        "description": {
            "it": "Percentuale di e-mail segnalate come sospette sul totale inviato nell'ultima simulazione di phishing di ogni sito (ultimi 12 mesi).",
            "en": "Percentage of e-mails reported as suspicious out of those sent in each site's latest phishing simulation (last 12 months).",
            "fr": "Pourcentage d'e-mails signalés comme suspects sur le total envoyé lors de la dernière simulation de phishing de chaque site (12 derniers mois).",
            "pl": "Odsetek e-maili zgłoszonych jako podejrzane spośród wysłanych w ostatniej symulacji phishingu każdego zakładu (ostatnie 12 miesięcy).",
            "tr": "Her tesisin son oltalama simülasyonunda gönderilen e-postalardan şüpheli olarak bildirilenlerin yüzdesi (son 12 ay).",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 40.0,
        "threshold_critical": 20.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.6.8 / A.6.3 / NIS2 Art.21(2)(g) — non basta non cliccare: il personale deve segnalare gli eventi sospetti, ed è la segnalazione rapida a limitare un attacco reale.",
            "en": "ISO 27001 A.6.8 / A.6.3 / NIS2 Art.21(2)(g) — not clicking is not enough: staff must report suspicious events, and fast reporting is what limits a real attack.",
            "fr": "ISO 27001 A.6.8 / A.6.3 / NIS2 Art.21(2)(g) — ne pas cliquer ne suffit pas : le personnel doit signaler les événements suspects, et c'est le signalement rapide qui limite une attaque réelle.",
            "pl": "ISO 27001 A.6.8 / A.6.3 / NIS2 Art.21(2)(g) — samo nieklikanie nie wystarcza: personel musi zgłaszać podejrzane zdarzenia, a to szybkie zgłoszenie ogranicza rzeczywisty atak.",
            "tr": "ISO 27001 A.6.8 / A.6.3 / NIS2 Md.21(2)(g) — tıklamamak yeterli değildir: personel şüpheli olayları bildirmelidir ve gerçek bir saldırıyı sınırlayan hızlı bildirimdir.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "board_training_valid": {
        "name": {
            "it": "Formazione dell'organo di gestione",
            "en": "Management Body Training",
            "fr": "Formation de l'organe de direction",
            "pl": "Szkolenie organu zarządzającego",
            "tr": "Yönetim Organı Eğitimi",
        },
        "description": {
            "it": "Percentuale dei componenti in carica dell'organo di gestione (CdA) con un'erogazione ancora valida di un corso per l'organo di gestione.",
            "en": "Percentage of the serving members of the management body (board) with a still-valid session of a management-body course.",
            "fr": "Pourcentage des membres en fonction de l'organe de direction (CA) ayant suivi une session encore valide d'un cours destiné à l'organe de direction.",
            "pl": "Odsetek urzędujących członków organu zarządzającego (zarządu) z wciąż ważnym szkoleniem z kursu dla organu zarządzającego.",
            "tr": "Yönetim organının (yönetim kurulu) görevdeki üyelerinden, yönetim organına yönelik bir kursun hâlâ geçerli bir oturumuna katılmış olanların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 75.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "training",
        "frameworks": ["NIS2", "ISO27001"],
        "match_keywords": [],
        "rationale": {
            "it": "NIS2 Art.20(2) / ISO 27001 cl.5.1 e 7.2 — i membri dell'organo di gestione sono tenuti a seguire una formazione per valutare i rischi di cibersicurezza e il loro impatto; la formazione va ripetuta e documentata.",
            "en": "NIS2 Art.20(2) / ISO 27001 cl.5.1 and 7.2 — members of the management body are required to follow training to assess cybersecurity risks and their impact; the training must be repeated and documented.",
            "fr": "NIS2 Art.20(2) / ISO 27001 cl.5.1 et 7.2 — les membres de l'organe de direction sont tenus de suivre une formation pour évaluer les risques de cybersécurité et leur impact ; la formation doit être renouvelée et documentée.",
            "pl": "NIS2 Art.20(2) / ISO 27001 pkt 5.1 i 7.2 — członkowie organu zarządzającego mają obowiązek uczestniczyć w szkoleniach, aby oceniać ryzyka cyberbezpieczeństwa i ich wpływ; szkolenie należy powtarzać i dokumentować.",
            "tr": "NIS2 Md.20(2) / ISO 27001 md.5.1 ve 7.2 — yönetim organı üyeleri siber güvenlik risklerini ve etkilerini değerlendirebilmek için eğitim almakla yükümlüdür; eğitim tekrarlanmalı ve belgelenmelidir.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    # ───────────────────────── SUPPLIER ────────────────────────────────────
    "suppliers_assessed_rate": {
        "name": {
            "it": "Fornitori critici valutati",
            "en": "Critical Suppliers Assessed",
            "fr": "Fournisseurs critiques évalués",
            "pl": "Ocenieni dostawcy krytyczni",
            "tr": "Değerlendirilen Kritik Tedarikçiler",
        },
        "description": {
            "it": "Percentuale di fornitori critici con valutazione di sicurezza aggiornata.",
            "en": "Percentage of critical suppliers with an up-to-date security assessment.",
            "fr": "Pourcentage de fournisseurs critiques avec une évaluation de sécurité à jour.",
            "pl": "Odsetek dostawców krytycznych z aktualną oceną bezpieczeństwa.",
            "tr": "Güncel güvenlik değerlendirmesine sahip kritik tedarikçilerin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 85.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "supplier",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["fornitor", "supplier"],
        "rationale": {
            "it": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — i fornitori critici vanno valutati per la sicurezza della catena di fornitura, almeno annualmente.",
            "en": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — critical suppliers must be assessed for supply-chain security, at least annually.",
            "fr": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — les fournisseurs critiques doivent être évalués pour la sécurité de la chaîne d'approvisionnement, au moins annuellement.",
            "pl": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — dostawców krytycznych należy oceniać pod kątem bezpieczeństwa łańcucha dostaw, co najmniej raz w roku.",
            "tr": "ISO 27001 A.5.19–A.5.22 / NIS2 Md.21(2)(d) — kritik tedarikçiler tedarik zinciri güvenliği için en az yılda bir değerlendirilmelidir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Fornitori (M14) via ingest API.",
            "en": "Computed from the Suppliers module (M14) via API ingest.",
            "fr": "Calculé depuis le module Fournisseurs (M14) via l'API.",
            "pl": "Obliczane z modułu Dostawcy (M14) przez API.",
            "tr": "Tedarikçiler modülünden (M14) API ile hesaplanır.",
        },
    },
    "suppliers_critical_unassessed": {
        "name": {
            "it": "Fornitori critici non valutati",
            "en": "Unassessed Critical Suppliers",
            "fr": "Fournisseurs critiques non évalués",
            "pl": "Nieoceni dostawcy krytyczni",
            "tr": "Değerlendirilmemiş Kritik Tedarikçiler",
        },
        "description": {
            "it": "Numero di fornitori critici privi di valutazione di sicurezza valida.",
            "en": "Number of critical suppliers lacking a valid security assessment.",
            "fr": "Nombre de fournisseurs critiques sans évaluation de sécurité valide.",
            "pl": "Liczba dostawców krytycznych bez ważnej oceny bezpieczeństwa.",
            "tr": "Geçerli güvenlik değerlendirmesi olmayan kritik tedarikçi sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 3.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "supplier",
        "frameworks": ["TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["fornitor", "supplier"],
        "rationale": {
            "it": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — i fornitori critici non valutati rappresentano un rischio non gestito nella catena di fornitura.",
            "en": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — unassessed critical suppliers represent an unmanaged supply-chain risk.",
            "fr": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — les fournisseurs critiques non évalués constituent un risque non maîtrisé de la chaîne d'approvisionnement.",
            "pl": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — nieocenieni dostawcy krytyczni stanowią niezarządzane ryzyko łańcucha dostaw.",
            "tr": "TISAX ISA 7.x / NIS2 Md.21(2)(d) — değerlendirilmemiş kritik tedarikçiler, yönetilmeyen bir tedarik zinciri riskidir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Fornitori (M14) via ingest API.",
            "en": "Computed from the Suppliers module (M14) via API ingest.",
            "fr": "Calculé depuis le module Fournisseurs (M14) via l'API.",
            "pl": "Obliczane z modułu Dostawcy (M14) przez API.",
            "tr": "Tedarikçiler modülünden (M14) API ile hesaplanır.",
        },
    },
    # ───────────────────────── CONTINUITY (M16 BCP/DR) ─────────────────────
    "dr_test_age_days": {
        "name": {
            "it": "Anzianità ultimo test DR",
            "en": "Last DR Test Age",
            "fr": "Ancienneté du dernier test PRA",
            "pl": "Wiek ostatniego testu DR",
            "tr": "Son OK Testi Yaşı",
        },
        "description": {
            "it": "Giorni trascorsi dall'ultimo test di continuità del piano messo peggio. Un piano mai testato conta dalla propria creazione.",
            "en": "Days since the last continuity test of the worst-placed plan. A plan never tested counts from its creation.",
            "fr": "Jours écoulés depuis le dernier test de continuité du plan le plus en retard. Un plan jamais testé compte depuis sa création.",
            "pl": "Liczba dni od ostatniego testu ciągłości najgorzej wypadającego planu. Plan nigdy nietestowany liczy się od utworzenia.",
            "tr": "En kötü durumdaki planın son süreklilik testinden bu yana geçen gün. Hiç test edilmemiş plan, oluşturulmasından itibaren sayılır.",
        },
        "unit": "giorni",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 365.0,
        "threshold_critical": 540.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "continuity",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — un piano di continuità non provato non è una misura, è un'intenzione: il test va ripetuto almeno una volta l'anno.",
            "en": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — an untested continuity plan is not a control but an intention: the test must be repeated at least yearly.",
            "fr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — un plan de continuité non testé n'est pas une mesure mais une intention : le test doit être répété au moins une fois par an.",
            "pl": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — nieprzetestowany plan ciągłości nie jest zabezpieczeniem, lecz zamiarem: test należy powtarzać co najmniej raz w roku.",
            "tr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Md.21(2)(c) — test edilmemiş bir süreklilik planı bir önlem değil, bir niyettir: test en az yılda bir tekrarlanmalıdır.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "dr_test_pass_rate": {
        "name": {
            "it": "Tasso di test DR superati",
            "en": "DR Test Pass Rate",
            "fr": "Taux de tests PRA réussis",
            "pl": "Wskaźnik zdanych testów DR",
            "tr": "Başarılı OK Testi Oranı",
        },
        "description": {
            "it": "Percentuale di test di continuità con esito «superato» negli ultimi 12 mesi. Un esito parziale non conta come superato.",
            "en": "Percentage of continuity tests with a \u201cpassed\u201d outcome in the last 12 months. A partial outcome does not count as passed.",
            "fr": "Pourcentage de tests de continuité «\u00a0réussis\u00a0» sur les 12 derniers mois. Un résultat partiel ne compte pas comme réussi.",
            "pl": "Odsetek testów ciągłości z wynikiem \u201ezdany\u201d w ostatnich 12 miesiącach. Wynik częściowy nie liczy się jako zdany.",
            "tr": "Son 12 ayda «başarılı» sonuçlanan süreklilik testlerinin yüzdesi. Kısmi sonuç başarılı sayılmaz.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 90.0,
        "threshold_critical": 70.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "continuity",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.5.30 / TISAX ISA 1.6.3 / NIS2 Art.21(2)(c) — testare e fallire senza rimediare equivale a non testare: l'esito va tracciato e gli scostamenti trattati.",
            "en": "ISO 27001 A.5.30 / TISAX ISA 1.6.3 / NIS2 Art.21(2)(c) — testing and failing without remediation equals not testing: outcomes must be tracked and gaps treated.",
            "fr": "ISO 27001 A.5.30 / TISAX ISA 1.6.3 / NIS2 Art.21(2)(c) — tester et échouer sans remédier équivaut à ne pas tester : le résultat doit être tracé et les écarts traités.",
            "pl": "ISO 27001 A.5.30 / TISAX ISA 1.6.3 / NIS2 Art.21(2)(c) — testowanie i niepowodzenie bez działań naprawczych równa się brakowi testu: wynik należy rejestrować, a odchylenia obsłużyć.",
            "tr": "ISO 27001 A.5.30 / TISAX ISA 1.6.3 / NIS2 Md.21(2)(c) — test edip başarısız olmak ve düzeltmemek, test etmemekle aynıdır: sonuç izlenmeli, sapmalar ele alınmalıdır.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "dr_rto_gap_hours": {
        "name": {
            "it": "Scostamento RTO reale vs obiettivo",
            "en": "Actual vs Target RTO Gap",
            "fr": "Écart RTO réel vs objectif",
            "pl": "Odchylenie RTO rzeczywistego od celu",
            "tr": "Gerçekleşen ve Hedef RTO Farkı",
        },
        "description": {
            "it": "Ore di scostamento medio fra il tempo di ripristino ottenuto nei test e l'obiettivo dichiarato dal piano. Positivo = ripristino più lento del promesso.",
            "en": "Average hours between the recovery time achieved in tests and the target declared by the plan. Positive = recovery slower than promised.",
            "fr": "Écart moyen en heures entre le temps de reprise obtenu lors des tests et l'objectif déclaré par le plan. Positif = reprise plus lente que promis.",
            "pl": "Średnia różnica w godzinach między czasem odtworzenia osiągniętym w testach a celem deklarowanym w planie. Dodatnia = odtworzenie wolniejsze niż obiecano.",
            "tr": "Testlerde elde edilen kurtarma süresi ile planın beyan ettiği hedef arasındaki ortalama saat farkı. Pozitif = vaat edilenden yavaş kurtarma.",
        },
        "unit": "ore",
        "aggregation": "avg_value",
        "threshold_direction": "below",
        "threshold_warning": 0.0,
        "threshold_critical": 24.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "continuity",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — un piano con RTO dichiarato di 4 ore, ripristinato in 30, espone l'azienda per 26 ore non pianificate: lo scostamento è il vero indicatore di affidabilità del piano.",
            "en": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — a plan declaring a 4-hour RTO but recovering in 30 leaves the company exposed for 26 unplanned hours: the gap is the plan's real reliability indicator.",
            "fr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — un plan annonçant un RTO de 4 heures mais restauré en 30 expose l'entreprise pendant 26 heures non planifiées : l'écart est le véritable indicateur de fiabilité du plan.",
            "pl": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — plan deklarujący RTO 4 godzin, a odtworzony w 30, naraża firmę przez 26 nieplanowanych godzin: odchylenie jest prawdziwym miernikiem wiarygodności planu.",
            "tr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Md.21(2)(c) — 4 saatlik RTO beyan eden ancak 30 saatte kurtarılan bir plan, şirketi 26 planlanmamış saat boyunca açıkta bırakır: fark, planın gerçek güvenilirlik göstergesidir.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "dr_plans_overdue_count": {
        "name": {
            "it": "Piani di continuità con test scaduto",
            "en": "Continuity Plans With Overdue Test",
            "fr": "Plans de continuité au test échu",
            "pl": "Plany ciągłości z zaległym testem",
            "tr": "Testi Geciken Süreklilik Planları",
        },
        "description": {
            "it": "Numero di piani BCP approvati con test scaduto rispetto alla cadenza prevista, o mai eseguito.",
            "en": "Number of approved BCP plans whose test is overdue against the planned frequency, or never performed.",
            "fr": "Nombre de plans PCA approuvés dont le test est échu par rapport à la fréquence prévue, ou jamais réalisé.",
            "pl": "Liczba zatwierdzonych planów BCP z testem zaległym względem zaplanowanej częstotliwości lub nigdy nieprzeprowadzonym.",
            "tr": "Planlanan sıklığa göre testi geciken veya hiç yapılmamış onaylı İSP planı sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 3.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "continuity",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — la cadenza di test dichiarata nel piano è un impegno verificabile in audit: superarla senza motivo documentato è una non conformità.",
            "en": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — the test frequency declared in the plan is an auditable commitment: exceeding it without documented reason is a nonconformity.",
            "fr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — la fréquence de test déclarée dans le plan est un engagement auditable : la dépasser sans motif documenté est une non-conformité.",
            "pl": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — częstotliwość testów zadeklarowana w planie jest zobowiązaniem podlegającym audytowi: jej przekroczenie bez udokumentowanego powodu to niezgodność.",
            "tr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Md.21(2)(c) — planda beyan edilen test sıklığı denetlenebilir bir taahhüttür: belgelenmiş gerekçe olmadan aşılması bir uygunsuzluktur.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "bcp_critical_process_coverage": {
        "name": {
            "it": "Copertura BCP dei processi critici",
            "en": "BCP Coverage of Critical Processes",
            "fr": "Couverture PCA des processus critiques",
            "pl": "Pokrycie procesów krytycznych planem BCP",
            "tr": "Kritik Süreçlerin İSP Kapsamı",
        },
        "description": {
            "it": "Percentuale di processi critici della BIA coperti da almeno un piano di continuità approvato.",
            "en": "Percentage of BIA critical processes covered by at least one approved continuity plan.",
            "fr": "Pourcentage de processus critiques du BIA couverts par au moins un plan de continuité approuvé.",
            "pl": "Odsetek procesów krytycznych z BIA objętych co najmniej jednym zatwierdzonym planem ciągłości.",
            "tr": "En az bir onaylı süreklilik planı kapsamındaki BIA kritik süreçlerinin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "continuity",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — un processo critico senza piano è un buco che non si vede finché non serve il piano: la BIA identifica, il BCP deve coprire.",
            "en": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — a critical process without a plan is a gap invisible until the plan is needed: the BIA identifies, the BCP must cover.",
            "fr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — un processus critique sans plan est une lacune invisible jusqu'au moment où le plan devient nécessaire : le BIA identifie, le PCA doit couvrir.",
            "pl": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Art.21(2)(c) — proces krytyczny bez planu to luka niewidoczna do chwili, gdy plan jest potrzebny: BIA identyfikuje, BCP musi pokryć.",
            "tr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 / NIS2 Md.21(2)(c) — planı olmayan kritik süreç, plana ihtiyaç duyulana kadar görünmeyen bir boşluktur: BIA tanımlar, İSP kapsamalıdır.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "bcp_rto_meets_bia_target_rate": {
        "name": {
            "it": "Piani BCP entro il target RTO della BIA",
            "en": "BCP Plans Within BIA RTO Target",
            "fr": "Plans PCA respectant l'objectif RTO du BIA",
            "pl": "Plany BCP w celu RTO z BIA",
            "tr": "BIA RTO Hedefi İçindeki İSP Planları",
        },
        "description": {
            "it": "Percentuale di piani il cui RTO dichiarato rispetta il target più stringente fra i processi critici che il piano copre.",
            "en": "Percentage of plans whose declared RTO meets the strictest target among the critical processes the plan covers.",
            "fr": "Pourcentage de plans dont le RTO déclaré respecte l'objectif le plus strict parmi les processus critiques couverts.",
            "pl": "Odsetek planów, których deklarowane RTO spełnia najostrzejszy cel spośród objętych procesów krytycznych.",
            "tr": "Beyan edilen RTO'su, kapsadığı kritik süreçler arasındaki en sıkı hedefi karşılayan planların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "continuity",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 — un piano approvato e testato può comunque promettere meno di quanto il processo richiede: il confronto fra RTO del piano e target della BIA è l'unico modo per accorgersene prima dell'emergenza.",
            "en": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 — an approved, tested plan may still promise less than the process requires: comparing the plan's RTO with the BIA target is the only way to notice before the emergency.",
            "fr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 — un plan approuvé et testé peut néanmoins promettre moins que ce que le processus exige : comparer le RTO du plan à l'objectif du BIA est le seul moyen de s'en apercevoir avant l'urgence.",
            "pl": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 — zatwierdzony i przetestowany plan może i tak obiecywać mniej, niż wymaga proces: porównanie RTO planu z celem z BIA to jedyny sposób, by zauważyć to przed awarią.",
            "tr": "ISO 27001 A.5.30 / TISAX ISA 5.2.8 — onaylı ve test edilmiş bir plan yine de sürecin gerektirdiğinden azını vaat edebilir: planın RTO'sunu BIA hedefiyle karşılaştırmak, bunu acil durumdan önce fark etmenin tek yoludur.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    # ───────────────────────── FACILITY / MANUTENZIONE (M04) ───────────────
    "maintenance_plan_compliance_rate": {
        "name": {
            "it": "Rispetto del piano di manutenzione",
            "en": "Maintenance Plan Compliance",
            "fr": "Respect du plan de maintenance",
            "pl": "Zgodność z planem konserwacji",
            "tr": "Bakım Planına Uygunluk",
        },
        "description": {
            "it": "Percentuale di apparati e impianti con manutenzione programmata eseguita entro la scadenza prevista.",
            "en": "Percentage of equipment and facilities whose scheduled maintenance is performed within the due date.",
            "fr": "Pourcentage d'équipements et d'installations dont la maintenance programmée est effectuée dans les délais.",
            "pl": "Odsetek urządzeń i instalacji, których zaplanowana konserwacja wykonywana jest w terminie.",
            "tr": "Planlanan bakımı süresi içinde yapılan ekipman ve tesislerin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "facility",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["manutenzione", "maintenance"],
        "rationale": {
            "it": "ISO 27001 A.7.8 e A.7.11 — apparecchiature e utilities di supporto vanno manutenute secondo le indicazioni del costruttore: la manutenzione saltata è la causa più comune di indisponibilità evitabile.",
            "en": "ISO 27001 A.7.8 and A.7.11 — equipment and supporting utilities must be maintained per manufacturer guidance: skipped maintenance is the most common cause of avoidable downtime.",
            "fr": "ISO 27001 A.7.8 et A.7.11 — les équipements et services généraux doivent être maintenus selon les préconisations du constructeur : une maintenance sautée est la cause la plus fréquente d'indisponibilité évitable.",
            "pl": "ISO 27001 A.7.8 i A.7.11 — sprzęt i media wspierające należy konserwować zgodnie z zaleceniami producenta: pominięta konserwacja to najczęstsza przyczyna możliwej do uniknięcia niedostępności.",
            "tr": "ISO 27001 A.7.8 ve A.7.11 — ekipman ve destek altyapıları üretici talimatlarına göre bakılmalıdır: atlanan bakım, önlenebilir kesintilerin en yaygın nedenidir.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "maintenance_overdue_count": {
        "name": {
            "it": "Manutenzioni scadute",
            "en": "Overdue Maintenance",
            "fr": "Maintenances échues",
            "pl": "Zaległe konserwacje",
            "tr": "Geciken Bakımlar",
        },
        "description": {
            "it": "Numero di apparati e impianti la cui manutenzione programmata è oltre la data prevista.",
            "en": "Number of equipment and facilities whose scheduled maintenance is past its due date.",
            "fr": "Nombre d'équipements et d'installations dont la maintenance programmée a dépassé l'échéance.",
            "pl": "Liczba urządzeń i instalacji, których zaplanowana konserwacja przekroczyła termin.",
            "tr": "Planlanan bakımı vadesini geçmiş ekipman ve tesis sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "facility",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": [],
        "rationale": {
            "it": "ISO 27001 A.7.8 / TISAX ISA 5.1 — la cadenza di manutenzione dichiarata è un impegno verificabile in audit; superarla senza motivo documentato è una non conformità e, sugli impianti di continuità, un rischio diretto per la disponibilità.",
            "en": "ISO 27001 A.7.8 / TISAX ISA 5.1 — the declared maintenance frequency is an auditable commitment; exceeding it without documented reason is a nonconformity and, on continuity equipment, a direct availability risk.",
            "fr": "ISO 27001 A.7.8 / TISAX ISA 5.1 — la fréquence de maintenance déclarée est un engagement auditable ; la dépasser sans motif documenté est une non-conformité et, sur les installations de continuité, un risque direct de disponibilité.",
            "pl": "ISO 27001 A.7.8 / TISAX ISA 5.1 — zadeklarowana częstotliwość konserwacji jest zobowiązaniem podlegającym audytowi; jej przekroczenie bez uzasadnienia to niezgodność, a na instalacjach ciągłości — bezpośrednie ryzyko dostępności.",
            "tr": "ISO 27001 A.7.8 / TISAX ISA 5.1 — beyan edilen bakım sıklığı denetlenebilir bir taahhüttür; belgelenmiş gerekçe olmadan aşılması bir uygunsuzluk, süreklilik sistemlerinde ise doğrudan erişilebilirlik riskidir.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
    "facility_check_age_days": {
        "name": {
            "it": "Anzianità verifica impianti",
            "en": "Facility Check Age",
            "fr": "Ancienneté du contrôle des installations",
            "pl": "Wiek kontroli instalacji",
            "tr": "Tesis Kontrolü Yaşı",
        },
        "description": {
            "it": "Giorni trascorsi dall'ultima verifica dell'impianto di supporto messo peggio: UPS, gruppi elettrogeni, antincendio, climatizzazione, sicurezza fisica.",
            "en": "Days since the last check of the worst-placed supporting facility: UPS, generators, fire protection, cooling, physical security.",
            "fr": "Jours écoulés depuis le dernier contrôle de l'installation de support la plus en retard : onduleurs, groupes électrogènes, incendie, climatisation, sécurité physique.",
            "pl": "Liczba dni od ostatniej kontroli najgorzej wypadającej instalacji wspierającej: UPS, agregaty, ppoż., klimatyzacja, ochrona fizyczna.",
            "tr": "En kötü durumdaki destek tesisinin son kontrolünden bu yana geçen gün: UPS, jeneratör, yangın, iklimlendirme, fiziksel güvenlik.",
        },
        "unit": "giorni",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 180.0,
        "threshold_critical": 365.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "internal",
        "category": "facility",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["ups", "impianto", "gruppo elettrogeno"],
        "rationale": {
            "it": "ISO 27001 A.7.11 — le utilities di supporto (alimentazione, condizionamento, antincendio) vanno ispezionate e provate a intervalli regolari: un UPS non provato è una batteria che si scopre scarica durante il blackout.",
            "en": "ISO 27001 A.7.11 — supporting utilities (power, cooling, fire protection) must be inspected and tested at regular intervals: an untested UPS is a battery you discover flat during the blackout.",
            "fr": "ISO 27001 A.7.11 — les services généraux (alimentation, climatisation, incendie) doivent être inspectés et testés à intervalles réguliers : un onduleur non testé est une batterie que l'on découvre à plat pendant la coupure.",
            "pl": "ISO 27001 A.7.11 — media wspierające (zasilanie, chłodzenie, ppoż.) należy regularnie kontrolować i testować: nieprzetestowany UPS to akumulator, który okazuje się rozładowany podczas awarii zasilania.",
            "tr": "ISO 27001 A.7.11 — destek altyapıları (güç, iklimlendirme, yangın) düzenli aralıklarla denetlenmeli ve test edilmelidir: test edilmemiş bir UPS, elektrik kesintisinde boş olduğu anlaşılan bir aküdür.",
        },
        "checklist_hint": {"it": "", "en": "", "fr": "", "pl": "", "tr": ""},
    },
}


# I KPI dotati di connettore interno (kpi_connectors.INTERNAL_CONNECTORS) si
# popolano da soli leggendo i dati dei moduli GRC: il loro source è "internal"
# (auto-calcolo), non "api" (push esterno). Allineiamo qui source e checklist_hint
# usando il registry come unica fonte di verità, così catalogo, wizard di import
# e task settimanale restano coerenti senza duplicare l'elenco dei codici.
_INTERNAL_HINT = {
    "it": "Calcolato automaticamente dal modulo interno: nessun inserimento manuale o ingest API necessario.",
    "en": "Computed automatically from the internal module: no manual entry or API ingest required.",
    "fr": "Calculé automatiquement depuis le module interne : aucune saisie manuelle ni ingestion API requise.",
    "pl": "Obliczane automatycznie z modułu wewnętrznego: bez ręcznego wprowadzania ani ingestu API.",
    "tr": "Dahili modülden otomatik hesaplanır: manuel giriş veya API beslemesi gerekmez.",
}


def _apply_internal_sources():
    from .kpi_connectors import INTERNAL_CONNECTORS

    for code in INTERNAL_CONNECTORS:
        entry = KPI_CATALOG.get(code)
        if entry is not None:
            entry["source"] = "internal"
            entry["checklist_hint"] = dict(_INTERNAL_HINT)


_apply_internal_sources()


def _text(entry_field: dict, lang: str) -> str:
    """Estrae un campo localizzato con fallback IT → EN → primo disponibile."""
    if not isinstance(entry_field, dict):
        return entry_field or ""
    return (
        entry_field.get(lang)
        or entry_field.get("it")
        or entry_field.get("en")
        or next(iter(entry_field.values()), "")
    )


def localized_catalog(lang: str = "it") -> list:
    """
    Restituisce il catalogo con i testi risolti nella lingua richiesta,
    ordinato per categoria (ordine di CATEGORIES) e poi per nome.
    """
    if lang not in LANGS:
        lang = "it"

    items = []
    for code, entry in KPI_CATALOG.items():
        seed = entry.get("template_seed")
        items.append({
            "kpi_code": code,
            "name": _text(entry["name"], lang),
            "description": _text(entry["description"], lang),
            "unit": entry["unit"],
            "aggregation": entry["aggregation"],
            "threshold_direction": entry["threshold_direction"],
            "threshold_warning": entry["threshold_warning"],
            "threshold_critical": entry["threshold_critical"],
            "notify_on_warning": entry["notify_on_warning"],
            "notify_on_critical": entry["notify_on_critical"],
            "source": entry["source"],
            "category": entry["category"],
            "frameworks": entry["frameworks"],
            "rationale": _text(entry["rationale"], lang),
            "checklist_hint": _text(entry["checklist_hint"], lang),
            "match_keywords": entry.get("match_keywords", []),
            "has_template_seed": seed is not None,
            "template_seed_name": _text(seed["name"], lang) if seed else "",
        })

    cat_order = {c: i for i, c in enumerate(CATEGORIES)}
    items.sort(key=lambda x: (cat_order.get(x["category"], 99), x["name"].lower()))
    return items
