"""
Catalogo statico dei KPI standard suggeribili in base ai framework attivi.

NON è un modello Django: sono dati Python puri, nessuna migrazione. Usato da
KpiSuggestView/KpiImportSuggestionsView per proporre KPI pre-configurati con
soglie e razionale normativo.

Ogni entry contiene testi localizzati in IT/EN/FR/PL/TR per name, description,
rationale e checklist_hint, più i metadati (unit, aggregation, soglie, sorgente,
categoria, frameworks di riferimento) e `match_keywords` per il collegamento
automatico a un ChecklistTemplate esistente.

Lingue supportate.
"""

LANGS = ("it", "en", "fr", "pl", "tr")

# Categorie usate per raggruppare i suggerimenti nel wizard frontend.
CATEGORIES = (
    "operations",
    "incident",
    "vulnerability",
    "access",
    "compliance",
    "training",
    "supplier",
)


KPI_CATALOG = {
    # ───────────────────────── OPERATIONS ──────────────────────────────────
    "backup_success_rate": {
        "name": {
            "it": "Tasso di successo backup",
            "en": "Backup Success Rate",
            "fr": "Taux de succès des sauvegardes",
            "pl": "Wskaźnik sukcesu kopii zapasowych",
            "tr": "Yedekleme Başarı Oranı",
        },
        "description": {
            "it": "Percentuale di backup completati con successo sul totale pianificati nel periodo.",
            "en": "Percentage of backups completed successfully out of total scheduled in the period.",
            "fr": "Pourcentage de sauvegardes réussies sur le total planifié sur la période.",
            "pl": "Odsetek pomyślnie ukończonych kopii zapasowych względem zaplanowanych w okresie.",
            "tr": "Dönemde planlanan toplam yedeklemeye göre başarıyla tamamlananların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 99.0,
        "threshold_critical": 95.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "checklist",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["backup", "salvataggi"],
        "rationale": {
            "it": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — la continuità operativa richiede backup verificati con frequenza documentata.",
            "en": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — operational continuity requires verified backups with documented frequency.",
            "fr": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — la continuité opérationnelle exige des sauvegardes vérifiées à fréquence documentée.",
            "pl": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Art.21(2)(c) — ciągłość działania wymaga zweryfikowanych kopii zapasowych o udokumentowanej częstotliwości.",
            "tr": "ISO 27001 cl.8.13 / TISAX ISA 5.2.4 / NIS2 Md.21(2)(c) — operasyonel süreklilik, belgelenmiş sıklıkta doğrulanmış yedekleme gerektirir.",
        },
        "checklist_hint": {
            "it": "Collega al template checklist 'Verifica backup notturno' se presente.",
            "en": "Link to checklist template 'Nightly backup verification' if present.",
            "fr": "Lier au modèle de checklist « Vérification de la sauvegarde nocturne » si présent.",
            "pl": "Połącz z szablonem listy kontrolnej „Weryfikacja nocnej kopii zapasowej”, jeśli istnieje.",
            "tr": "Varsa 'Gecelik yedekleme doğrulaması' kontrol listesi şablonuna bağlayın.",
        },
        "template_seed": {
            "frequency": "daily",
            "name": {
                "it": "Verifica backup notturno",
                "en": "Nightly backup verification",
                "fr": "Vérification de la sauvegarde nocturne",
                "pl": "Weryfikacja nocnej kopii zapasowej",
                "tr": "Gecelik yedekleme doğrulaması",
            },
            "items": [
                {
                    "item_type": "checkbox",
                    "is_mandatory": True,
                    "unit": "",
                    "text": {
                        "it": "Backup notturno completato senza errori",
                        "en": "Nightly backup completed without errors",
                        "fr": "Sauvegarde nocturne terminée sans erreur",
                        "pl": "Nocna kopia zapasowa ukończona bez błędów",
                        "tr": "Gecelik yedekleme hatasız tamamlandı",
                    },
                },
            ],
        },
    },
    "backup_restore_test_age_days": {
        "name": {
            "it": "Anzianità ultimo test di ripristino",
            "en": "Last Restore Test Age",
            "fr": "Ancienneté du dernier test de restauration",
            "pl": "Wiek ostatniego testu odtwarzania",
            "tr": "Son Geri Yükleme Testi Yaşı",
        },
        "description": {
            "it": "Giorni trascorsi dall'ultimo test di ripristino backup eseguito con successo.",
            "en": "Days elapsed since the last successful backup restore test.",
            "fr": "Jours écoulés depuis le dernier test de restauration de sauvegarde réussi.",
            "pl": "Liczba dni od ostatniego udanego testu odtwarzania kopii zapasowej.",
            "tr": "Son başarılı yedek geri yükleme testinden bu yana geçen gün sayısı.",
        },
        "unit": "giorni",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 30.0,
        "threshold_critical": 90.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "checklist",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["ripristino", "restore", "backup"],
        "rationale": {
            "it": "ISO 27001 cl.8.13 — il ripristino deve essere testato periodicamente per garantire l'effettiva recuperabilità dei dati.",
            "en": "ISO 27001 cl.8.13 — restore must be tested periodically to ensure data is actually recoverable.",
            "fr": "ISO 27001 cl.8.13 — la restauration doit être testée périodiquement pour garantir la récupérabilité effective des données.",
            "pl": "ISO 27001 cl.8.13 — odtwarzanie musi być okresowo testowane, aby zapewnić rzeczywistą odzyskiwalność danych.",
            "tr": "ISO 27001 cl.8.13 — verilerin gerçekten kurtarılabilir olduğundan emin olmak için geri yükleme periyodik test edilmelidir.",
        },
        "checklist_hint": {
            "it": "Collega al template checklist di test ripristino trimestrale se presente.",
            "en": "Link to the quarterly restore-test checklist template if present.",
            "fr": "Lier au modèle de checklist de test de restauration trimestriel si présent.",
            "pl": "Połącz z kwartalnym szablonem listy kontrolnej testu odtwarzania, jeśli istnieje.",
            "tr": "Varsa üç aylık geri yükleme testi kontrol listesi şablonuna bağlayın.",
        },
        "template_seed": {
            "frequency": "monthly",
            "name": {
                "it": "Test ripristino backup",
                "en": "Backup restore test",
                "fr": "Test de restauration de sauvegarde",
                "pl": "Test odtwarzania kopii zapasowej",
                "tr": "Yedek geri yükleme testi",
            },
            "items": [
                {
                    "item_type": "numeric",
                    "is_mandatory": True,
                    "unit": "giorni",
                    "text": {
                        "it": "Giorni dall'ultimo test di ripristino completato",
                        "en": "Days since the last completed restore test",
                        "fr": "Jours depuis le dernier test de restauration réalisé",
                        "pl": "Dni od ostatniego ukończonego testu odtwarzania",
                        "tr": "Son tamamlanan geri yükleme testinden bu yana gün",
                    },
                },
            ],
        },
    },
    "patch_critical_compliance_rate": {
        "name": {
            "it": "Conformità patch critiche",
            "en": "Critical Patch Compliance",
            "fr": "Conformité des correctifs critiques",
            "pl": "Zgodność krytycznych poprawek",
            "tr": "Kritik Yama Uyumluluğu",
        },
        "description": {
            "it": "Percentuale di patch critiche applicate entro l'SLA sul totale rilasciate.",
            "en": "Percentage of critical patches applied within SLA out of total released.",
            "fr": "Pourcentage de correctifs critiques appliqués dans le SLA sur le total publié.",
            "pl": "Odsetek krytycznych poprawek wdrożonych w ramach SLA względem wszystkich wydanych.",
            "tr": "Yayımlanan toplam kritik yamadan SLA içinde uygulananların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 85.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["patch", "aggiornament", "update"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — le vulnerabilità tecniche devono essere corrette tempestivamente secondo SLA basati sul rischio.",
            "en": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — technical vulnerabilities must be remediated promptly per risk-based SLAs.",
            "fr": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — les vulnérabilités techniques doivent être corrigées rapidement selon des SLA fondés sur le risque.",
            "pl": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Art.21(2)(e) — podatności techniczne należy usuwać niezwłocznie zgodnie z SLA opartymi na ryzyku.",
            "tr": "ISO 27001 cl.8.8 / TISAX ISA 3.1.1 / NIS2 Md.21(2)(e) — teknik açıklar, riske dayalı SLA'lara göre derhal giderilmelidir.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dal sistema di patch management (es. WSUS/SCCM).",
            "en": "Populated via API ingest from the patch management system (e.g. WSUS/SCCM).",
            "fr": "Alimenté via l'API depuis le système de gestion des correctifs (ex. WSUS/SCCM).",
            "pl": "Zasilane przez API z systemu zarządzania poprawkami (np. WSUS/SCCM).",
            "tr": "Yama yönetim sisteminden (ör. WSUS/SCCM) API ile beslenir.",
        },
    },
    "systems_eol_count": {
        "name": {
            "it": "Sistemi a fine vita (EOL)",
            "en": "End-of-Life Systems",
            "fr": "Systèmes en fin de vie (EOL)",
            "pl": "Systemy wycofane (EOL)",
            "tr": "Kullanım Ömrü Biten Sistemler",
        },
        "description": {
            "it": "Numero di sistemi/software non più supportati dal vendor in esercizio.",
            "en": "Number of vendor-unsupported (EOL) systems/software still in operation.",
            "fr": "Nombre de systèmes/logiciels non supportés par l'éditeur encore en production.",
            "pl": "Liczba systemów/oprogramowania bez wsparcia producenta wciąż używanych.",
            "tr": "Hâlâ kullanımda olan, üretici desteği biten sistem/yazılım sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "operations",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["eol", "obsolescen", "fine vita"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 — i sistemi non più supportati non ricevono patch di sicurezza e vanno dismessi o isolati.",
            "en": "ISO 27001 cl.8.8 — unsupported systems no longer receive security patches and must be decommissioned or isolated.",
            "fr": "ISO 27001 cl.8.8 — les systèmes non supportés ne reçoivent plus de correctifs et doivent être retirés ou isolés.",
            "pl": "ISO 27001 cl.8.8 — niewspierane systemy nie otrzymują poprawek i muszą zostać wycofane lub odizolowane.",
            "tr": "ISO 27001 cl.8.8 — desteklenmeyen sistemler güvenlik yaması almaz; devre dışı bırakılmalı veya yalıtılmalıdır.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dall'inventario asset (M04) o CMDB.",
            "en": "Populated via API ingest from the asset inventory (M04) or CMDB.",
            "fr": "Alimenté via l'API depuis l'inventaire des actifs (M04) ou la CMDB.",
            "pl": "Zasilane przez API z inwentarza zasobów (M04) lub CMDB.",
            "tr": "Varlık envanterinden (M04) veya CMDB'den API ile beslenir.",
        },
    },
    # ───────────────────────── INCIDENT ────────────────────────────────────
    "incident_mttd_hours": {
        "name": {
            "it": "MTTD — Tempo medio di rilevazione",
            "en": "MTTD — Mean Time To Detect",
            "fr": "MTTD — Temps moyen de détection",
            "pl": "MTTD — Średni czas wykrycia",
            "tr": "MTTD — Ortalama Tespit Süresi",
        },
        "description": {
            "it": "Ore medie tra l'insorgenza e la rilevazione di un incidente di sicurezza.",
            "en": "Average hours between onset and detection of a security incident.",
            "fr": "Heures moyennes entre la survenue et la détection d'un incident de sécurité.",
            "pl": "Średnia liczba godzin między wystąpieniem a wykryciem incydentu bezpieczeństwa.",
            "tr": "Bir güvenlik olayının başlaması ile tespiti arasındaki ortalama saat.",
        },
        "unit": "ore",
        "aggregation": "avg_value",
        "threshold_direction": "below",
        "threshold_warning": 24.0,
        "threshold_critical": 72.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["incident", "rilevazione", "detect"],
        "rationale": {
            "it": "NIS2 Art.23 / ISO 27001 cl.5.24 — la rilevazione tempestiva (entro 24h per incidenti significativi) abilita la notifica preliminare.",
            "en": "NIS2 Art.23 / ISO 27001 cl.5.24 — timely detection (within 24h for significant incidents) enables the early warning notification.",
            "fr": "NIS2 Art.23 / ISO 27001 cl.5.24 — une détection rapide (sous 24h pour les incidents significatifs) permet l'alerte précoce.",
            "pl": "NIS2 Art.23 / ISO 27001 cl.5.24 — szybkie wykrycie (w ciągu 24h dla istotnych incydentów) umożliwia wczesne ostrzeżenie.",
            "tr": "NIS2 Md.23 / ISO 27001 cl.5.24 — zamanında tespit (önemli olaylar için 24 saat içinde) erken uyarı bildirimini sağlar.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Incidenti (M09) e inviato via ingest API.",
            "en": "Computed from the Incidents module (M09) and sent via API ingest.",
            "fr": "Calculé depuis le module Incidents (M09) et envoyé via l'API.",
            "pl": "Obliczane w module Incydenty (M09) i wysyłane przez API.",
            "tr": "Olaylar modülünden (M09) hesaplanır ve API ile gönderilir.",
        },
    },
    "incident_mttr_hours": {
        "name": {
            "it": "MTTR — Tempo medio di risoluzione",
            "en": "MTTR — Mean Time To Resolve",
            "fr": "MTTR — Temps moyen de résolution",
            "pl": "MTTR — Średni czas rozwiązania",
            "tr": "MTTR — Ortalama Çözüm Süresi",
        },
        "description": {
            "it": "Ore medie tra rilevazione e risoluzione di un incidente di sicurezza.",
            "en": "Average hours between detection and resolution of a security incident.",
            "fr": "Heures moyennes entre détection et résolution d'un incident de sécurité.",
            "pl": "Średnia liczba godzin między wykryciem a rozwiązaniem incydentu bezpieczeństwa.",
            "tr": "Bir güvenlik olayının tespiti ile çözümü arasındaki ortalama saat.",
        },
        "unit": "ore",
        "aggregation": "avg_value",
        "threshold_direction": "below",
        "threshold_warning": 72.0,
        "threshold_critical": 168.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["incident", "risoluzione", "resolve"],
        "rationale": {
            "it": "NIS2 Art.23 / ISO 27001 cl.5.26 — la risoluzione entro 72h supporta la notifica intermedia e limita l'impatto.",
            "en": "NIS2 Art.23 / ISO 27001 cl.5.26 — resolution within 72h supports the interim notification and limits impact.",
            "fr": "NIS2 Art.23 / ISO 27001 cl.5.26 — une résolution sous 72h soutient la notification intermédiaire et limite l'impact.",
            "pl": "NIS2 Art.23 / ISO 27001 cl.5.26 — rozwiązanie w ciągu 72h wspiera powiadomienie pośrednie i ogranicza skutki.",
            "tr": "NIS2 Md.23 / ISO 27001 cl.5.26 — 72 saat içinde çözüm ara bildirimi destekler ve etkiyi sınırlar.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Incidenti (M09) e inviato via ingest API.",
            "en": "Computed from the Incidents module (M09) and sent via API ingest.",
            "fr": "Calculé depuis le module Incidents (M09) et envoyé via l'API.",
            "pl": "Obliczane w module Incydenty (M09) i wysyłane przez API.",
            "tr": "Olaylar modülünden (M09) hesaplanır ve API ile gönderilir.",
        },
    },
    "incident_rca_completion_rate": {
        "name": {
            "it": "Completamento RCA incidenti",
            "en": "Incident RCA Completion Rate",
            "fr": "Taux d'achèvement des RCA d'incidents",
            "pl": "Wskaźnik ukończenia RCA incydentów",
            "tr": "Olay Kök Neden Analizi Tamamlama Oranı",
        },
        "description": {
            "it": "Percentuale di incidenti significativi con analisi della causa radice completata.",
            "en": "Percentage of significant incidents with a completed root-cause analysis.",
            "fr": "Pourcentage d'incidents significatifs avec une analyse des causes racines terminée.",
            "pl": "Odsetek istotnych incydentów z ukończoną analizą przyczyn źródłowych.",
            "tr": "Kök neden analizi tamamlanmış önemli olayların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["rca", "causa radice", "root cause"],
        "rationale": {
            "it": "ISO 27001 cl.10.2 / cl.5.27 — ogni incidente significativo richiede analisi della causa radice e azione correttiva.",
            "en": "ISO 27001 cl.10.2 / cl.5.27 — every significant incident requires root-cause analysis and corrective action.",
            "fr": "ISO 27001 cl.10.2 / cl.5.27 — chaque incident significatif exige une analyse des causes racines et une action corrective.",
            "pl": "ISO 27001 cl.10.2 / cl.5.27 — każdy istotny incydent wymaga analizy przyczyn źródłowych i działań korygujących.",
            "tr": "ISO 27001 cl.10.2 / cl.5.27 — her önemli olay kök neden analizi ve düzeltici faaliyet gerektirir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Incidenti/Lessons (M09/M12) via ingest API.",
            "en": "Computed from the Incidents/Lessons modules (M09/M12) via API ingest.",
            "fr": "Calculé depuis les modules Incidents/Lessons (M09/M12) via l'API.",
            "pl": "Obliczane z modułów Incydenty/Lekcje (M09/M12) przez API.",
            "tr": "Olaylar/Çıkarımlar modüllerinden (M09/M12) API ile hesaplanır.",
        },
    },
    "incident_recurrence_rate": {
        "name": {
            "it": "Tasso di ricorrenza incidenti",
            "en": "Incident Recurrence Rate",
            "fr": "Taux de récurrence des incidents",
            "pl": "Wskaźnik nawrotów incydentów",
            "tr": "Olay Tekrarlanma Oranı",
        },
        "description": {
            "it": "Percentuale di incidenti ricorrenti (stessa causa radice) sul totale del periodo.",
            "en": "Percentage of recurring incidents (same root cause) out of the period total.",
            "fr": "Pourcentage d'incidents récurrents (même cause racine) sur le total de la période.",
            "pl": "Odsetek nawracających incydentów (ta sama przyczyna) względem sumy w okresie.",
            "tr": "Dönem toplamına göre tekrarlayan (aynı kök neden) olayların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "count_fail",
        "threshold_direction": "below",
        "threshold_warning": 5.0,
        "threshold_critical": 15.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "incident",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["ricorrenza", "recurrence"],
        "rationale": {
            "it": "ISO 27001 cl.5.27 / cl.10.1 — incidenti ricorrenti indicano azioni correttive inefficaci e mancato apprendimento.",
            "en": "ISO 27001 cl.5.27 / cl.10.1 — recurring incidents indicate ineffective corrective actions and lack of learning.",
            "fr": "ISO 27001 cl.5.27 / cl.10.1 — les incidents récurrents révèlent des actions correctives inefficaces et un manque d'apprentissage.",
            "pl": "ISO 27001 cl.5.27 / cl.10.1 — nawracające incydenty wskazują na nieskuteczne działania korygujące i brak wniosków.",
            "tr": "ISO 27001 cl.5.27 / cl.10.1 — tekrarlayan olaylar etkisiz düzeltici faaliyetlere ve öğrenememeye işaret eder.",
        },
        "checklist_hint": {
            "it": "Calcolato dai moduli Incidenti/Lessons (M09/M12) via ingest API.",
            "en": "Computed from the Incidents/Lessons modules (M09/M12) via API ingest.",
            "fr": "Calculé depuis les modules Incidents/Lessons (M09/M12) via l'API.",
            "pl": "Obliczane z modułów Incydenty/Lekcje (M09/M12) przez API.",
            "tr": "Olaylar/Çıkarımlar modüllerinden (M09/M12) API ile hesaplanır.",
        },
    },
    # ───────────────────────── VULNERABILITY ───────────────────────────────
    "vuln_critical_open_count": {
        "name": {
            "it": "Vulnerabilità critiche aperte",
            "en": "Open Critical Vulnerabilities",
            "fr": "Vulnérabilités critiques ouvertes",
            "pl": "Otwarte krytyczne podatności",
            "tr": "Açık Kritik Açıklar",
        },
        "description": {
            "it": "Numero di vulnerabilità critiche attualmente aperte (non rimediate).",
            "en": "Number of critical vulnerabilities currently open (not remediated).",
            "fr": "Nombre de vulnérabilités critiques actuellement ouvertes (non corrigées).",
            "pl": "Liczba krytycznych podatności obecnie otwartych (nieusuniętych).",
            "tr": "Şu anda açık (giderilmemiş) kritik açık sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "vulnerability",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["vuln", "vulnerab"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — le vulnerabilità critiche devono essere rimediate entro tempi definiti (tipicamente 15gg).",
            "en": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — critical vulnerabilities must be remediated within defined timelines (typically 15 days).",
            "fr": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — les vulnérabilités critiques doivent être corrigées dans des délais définis (généralement 15 jours).",
            "pl": "ISO 27001 cl.8.8 / NIS2 Art.21(2)(e) — krytyczne podatności należy usuwać w określonym czasie (zwykle 15 dni).",
            "tr": "ISO 27001 cl.8.8 / NIS2 Md.21(2)(e) — kritik açıklar tanımlı sürelerde (genellikle 15 gün) giderilmelidir.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dallo scanner di vulnerabilità o dal modulo OSINT.",
            "en": "Populated via API ingest from the vulnerability scanner or the OSINT module.",
            "fr": "Alimenté via l'API depuis le scanner de vulnérabilités ou le module OSINT.",
            "pl": "Zasilane przez API ze skanera podatności lub modułu OSINT.",
            "tr": "Açık tarayıcısından veya OSINT modülünden API ile beslenir.",
        },
    },
    "vuln_critical_sla_compliance": {
        "name": {
            "it": "Conformità SLA vulnerabilità critiche",
            "en": "Critical Vulnerability SLA Compliance",
            "fr": "Conformité SLA des vulnérabilités critiques",
            "pl": "Zgodność SLA krytycznych podatności",
            "tr": "Kritik Açık SLA Uyumluluğu",
        },
        "description": {
            "it": "Percentuale di vulnerabilità critiche rimediate entro l'SLA definito.",
            "en": "Percentage of critical vulnerabilities remediated within the defined SLA.",
            "fr": "Pourcentage de vulnérabilités critiques corrigées dans le SLA défini.",
            "pl": "Odsetek krytycznych podatności usuniętych w ramach zdefiniowanego SLA.",
            "tr": "Tanımlı SLA içinde giderilen kritik açıkların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 85.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "vulnerability",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["vuln", "sla"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 — l'efficacia del processo di gestione vulnerabilità si misura sul rispetto degli SLA di remediation.",
            "en": "ISO 27001 cl.8.8 — the effectiveness of vulnerability management is measured by adherence to remediation SLAs.",
            "fr": "ISO 27001 cl.8.8 — l'efficacité de la gestion des vulnérabilités se mesure au respect des SLA de correction.",
            "pl": "ISO 27001 cl.8.8 — skuteczność zarządzania podatnościami mierzy się przestrzeganiem SLA usuwania.",
            "tr": "ISO 27001 cl.8.8 — açık yönetiminin etkinliği, giderme SLA'larına uyumla ölçülür.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dal sistema di vulnerability management.",
            "en": "Populated via API ingest from the vulnerability management system.",
            "fr": "Alimenté via l'API depuis le système de gestion des vulnérabilités.",
            "pl": "Zasilane przez API z systemu zarządzania podatnościami.",
            "tr": "Açık yönetim sisteminden API ile beslenir.",
        },
    },
    "vapt_age_days": {
        "name": {
            "it": "Anzianità ultimo VA/PT",
            "en": "Last VA/PT Age",
            "fr": "Ancienneté du dernier VA/PT",
            "pl": "Wiek ostatniego VA/PT",
            "tr": "Son VA/PT Yaşı",
        },
        "description": {
            "it": "Giorni trascorsi dall'ultimo Vulnerability Assessment / Penetration Test.",
            "en": "Days elapsed since the last Vulnerability Assessment / Penetration Test.",
            "fr": "Jours écoulés depuis le dernier Vulnerability Assessment / Penetration Test.",
            "pl": "Liczba dni od ostatniego testu VA/PT.",
            "tr": "Son Zafiyet Değerlendirmesi / Sızma Testinden bu yana geçen gün.",
        },
        "unit": "giorni",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 180.0,
        "threshold_critical": 365.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "vulnerability",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["vapt", "penetration", "pentest"],
        "rationale": {
            "it": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — i test di sicurezza (VA/PT) vanno eseguiti con cadenza almeno annuale.",
            "en": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — security testing (VA/PT) must be performed at least annually.",
            "fr": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — les tests de sécurité (VA/PT) doivent être réalisés au moins annuellement.",
            "pl": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — testy bezpieczeństwa (VA/PT) należy wykonywać co najmniej raz w roku.",
            "tr": "ISO 27001 cl.8.8 / cl.8.29 / TISAX ISA 5.2.2 — güvenlik testleri (VA/PT) en az yılda bir yapılmalıdır.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API o registrato in una checklist di pianificazione VA/PT.",
            "en": "Populated via API ingest or recorded in a VA/PT planning checklist.",
            "fr": "Alimenté via l'API ou enregistré dans une checklist de planification VA/PT.",
            "pl": "Zasilane przez API lub rejestrowane w liście kontrolnej planowania VA/PT.",
            "tr": "API ile beslenir veya VA/PT planlama kontrol listesinde kaydedilir.",
        },
    },
    # ───────────────────────── ACCESS & IDENTITY ───────────────────────────
    "zombie_accounts_count": {
        "name": {
            "it": "Account dormienti (zombie)",
            "en": "Zombie Accounts",
            "fr": "Comptes dormants (zombies)",
            "pl": "Konta uśpione (zombie)",
            "tr": "Atıl (Zombi) Hesaplar",
        },
        "description": {
            "it": "Numero di account attivi ma inutilizzati da oltre 90 giorni.",
            "en": "Number of accounts that are active but unused for more than 90 days.",
            "fr": "Nombre de comptes actifs mais inutilisés depuis plus de 90 jours.",
            "pl": "Liczba kont aktywnych, lecz nieużywanych od ponad 90 dni.",
            "tr": "Aktif ancak 90 günden fazla kullanılmayan hesap sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 5.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "access",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["account", "utenz", "zombie"],
        "rationale": {
            "it": "ISO 27001 cl.5.18 / cl.8.2 — i diritti di accesso vanno riesaminati; gli account inattivi >90gg vanno disabilitati.",
            "en": "ISO 27001 cl.5.18 / cl.8.2 — access rights must be reviewed; accounts inactive >90 days must be disabled.",
            "fr": "ISO 27001 cl.5.18 / cl.8.2 — les droits d'accès doivent être revus ; les comptes inactifs >90j doivent être désactivés.",
            "pl": "ISO 27001 cl.5.18 / cl.8.2 — prawa dostępu należy przeglądać; konta nieaktywne >90 dni należy wyłączyć.",
            "tr": "ISO 27001 cl.5.18 / cl.8.2 — erişim hakları gözden geçirilmeli; 90 günden fazla atıl hesaplar devre dışı bırakılmalıdır.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dall'IdP/AD (es. review accessi periodica).",
            "en": "Populated via API ingest from the IdP/AD (e.g. periodic access review).",
            "fr": "Alimenté via l'API depuis l'IdP/AD (ex. revue d'accès périodique).",
            "pl": "Zasilane przez API z IdP/AD (np. okresowy przegląd dostępu).",
            "tr": "IdP/AD'den API ile beslenir (ör. periyodik erişim incelemesi).",
        },
    },
    "offboarding_access_revocation_rate": {
        "name": {
            "it": "Revoca accessi a fine rapporto",
            "en": "Offboarding Access Revocation Rate",
            "fr": "Taux de révocation des accès au départ",
            "pl": "Wskaźnik odbierania dostępu przy offboardingu",
            "tr": "İşten Ayrılışta Erişim İptal Oranı",
        },
        "description": {
            "it": "Percentuale di offboarding con accessi revocati entro 24h dalla cessazione.",
            "en": "Percentage of offboardings with access revoked within 24h of termination.",
            "fr": "Pourcentage de départs avec accès révoqués sous 24h après la fin du contrat.",
            "pl": "Odsetek offboardingów z dostępem odebranym w ciągu 24h od zakończenia.",
            "tr": "İş ilişkisi bitiminden sonra 24 saat içinde erişimi iptal edilen ayrılışların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 95.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "checklist",
        "category": "access",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["offboarding", "cessazion", "revoca"],
        "rationale": {
            "it": "ISO 27001 cl.6.5 / cl.5.18 — alla cessazione del rapporto i diritti di accesso devono essere revocati tempestivamente.",
            "en": "ISO 27001 cl.6.5 / cl.5.18 — upon termination of employment, access rights must be revoked promptly.",
            "fr": "ISO 27001 cl.6.5 / cl.5.18 — à la fin du contrat, les droits d'accès doivent être révoqués sans délai.",
            "pl": "ISO 27001 cl.6.5 / cl.5.18 — po zakończeniu zatrudnienia prawa dostępu należy niezwłocznie odebrać.",
            "tr": "ISO 27001 cl.6.5 / cl.5.18 — iş ilişkisinin bitiminde erişim hakları derhal iptal edilmelidir.",
        },
        "checklist_hint": {
            "it": "Collega al template checklist di offboarding HR/IT se presente.",
            "en": "Link to the HR/IT offboarding checklist template if present.",
            "fr": "Lier au modèle de checklist d'offboarding RH/IT si présent.",
            "pl": "Połącz z szablonem listy kontrolnej offboardingu HR/IT, jeśli istnieje.",
            "tr": "Varsa İK/BT işten ayrılış kontrol listesi şablonuna bağlayın.",
        },
        "template_seed": {
            "frequency": "weekly",
            "name": {
                "it": "Offboarding — revoca accessi",
                "en": "Offboarding — access revocation",
                "fr": "Offboarding — révocation des accès",
                "pl": "Offboarding — odebranie dostępu",
                "tr": "İşten ayrılış — erişim iptali",
            },
            "items": [
                {
                    "item_type": "checkbox",
                    "is_mandatory": True,
                    "unit": "",
                    "text": {
                        "it": "Accessi revocati entro 24h dalla cessazione",
                        "en": "Access revoked within 24h of termination",
                        "fr": "Accès révoqués sous 24h après la fin du contrat",
                        "pl": "Dostęp odebrany w ciągu 24h od zakończenia",
                        "tr": "İş bitiminden sonra 24 saat içinde erişim iptal edildi",
                    },
                },
            ],
        },
    },
    "privileged_accounts_count": {
        "name": {
            "it": "Account privilegiati",
            "en": "Privileged Accounts",
            "fr": "Comptes à privilèges",
            "pl": "Konta uprzywilejowane",
            "tr": "Ayrıcalıklı Hesaplar",
        },
        "description": {
            "it": "Numero di account con privilegi amministrativi (monitoraggio del trend).",
            "en": "Number of accounts with administrative privileges (trend monitoring).",
            "fr": "Nombre de comptes à privilèges administratifs (suivi de tendance).",
            "pl": "Liczba kont z uprawnieniami administracyjnymi (monitorowanie trendu).",
            "tr": "Yönetici ayrıcalıklarına sahip hesap sayısı (eğilim izleme).",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": None,
        "threshold_critical": None,
        "notify_on_warning": False,
        "notify_on_critical": False,
        "source": "api",
        "category": "access",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["privileg", "admin"],
        "rationale": {
            "it": "ISO 27001 cl.8.2 — gli accessi privilegiati vanno limitati e monitorati nel tempo (least privilege).",
            "en": "ISO 27001 cl.8.2 — privileged access must be restricted and monitored over time (least privilege).",
            "fr": "ISO 27001 cl.8.2 — les accès à privilèges doivent être limités et suivis dans le temps (moindre privilège).",
            "pl": "ISO 27001 cl.8.2 — dostęp uprzywilejowany należy ograniczać i monitorować w czasie (najmniejsze uprawnienia).",
            "tr": "ISO 27001 cl.8.2 — ayrıcalıklı erişim kısıtlanmalı ve zaman içinde izlenmelidir (en az ayrıcalık).",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dall'IdP/PAM; soglie da personalizzare per plant.",
            "en": "Populated via API ingest from the IdP/PAM; thresholds to customize per plant.",
            "fr": "Alimenté via l'API depuis l'IdP/PAM ; seuils à personnaliser par site.",
            "pl": "Zasilane przez API z IdP/PAM; progi do dostosowania per zakład.",
            "tr": "IdP/PAM'den API ile beslenir; eşikler tesise göre özelleştirilir.",
        },
    },
    # ───────────────────────── COMPLIANCE & CONTROLS ───────────────────────
    "controls_compliance_rate": {
        "name": {
            "it": "Tasso di conformità controlli",
            "en": "Controls Compliance Rate",
            "fr": "Taux de conformité des contrôles",
            "pl": "Wskaźnik zgodności kontroli",
            "tr": "Kontrol Uyumluluk Oranı",
        },
        "description": {
            "it": "Percentuale di controlli in stato 'compliant' sul totale applicabile.",
            "en": "Percentage of controls in 'compliant' status out of total applicable.",
            "fr": "Pourcentage de contrôles « conformes » sur le total applicable.",
            "pl": "Odsetek kontroli w statusie „zgodny” względem wszystkich obowiązujących.",
            "tr": "Uygulanabilir toplam içinde 'uyumlu' durumdaki kontrollerin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "above",
        "threshold_warning": 85.0,
        "threshold_critical": 70.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["controll", "compliance"],
        "rationale": {
            "it": "ISO 27001 cl.9.1 — l'efficacia dell'ISMS richiede monitoraggio e misurazione continui della conformità dei controlli.",
            "en": "ISO 27001 cl.9.1 — ISMS effectiveness requires continuous monitoring and measurement of controls compliance.",
            "fr": "ISO 27001 cl.9.1 — l'efficacité du SMSI exige un suivi et une mesure continus de la conformité des contrôles.",
            "pl": "ISO 27001 cl.9.1 — skuteczność SZBI wymaga ciągłego monitorowania i pomiaru zgodności kontroli.",
            "tr": "ISO 27001 cl.9.1 — BGYS etkinliği, kontrol uyumunun sürekli izlenmesini ve ölçülmesini gerektirir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Controlli (M03) e inviato via ingest API.",
            "en": "Computed from the Controls module (M03) and sent via API ingest.",
            "fr": "Calculé depuis le module Contrôles (M03) et envoyé via l'API.",
            "pl": "Obliczane w module Kontrole (M03) i wysyłane przez API.",
            "tr": "Kontroller modülünden (M03) hesaplanır ve API ile gönderilir.",
        },
    },
    "evidence_expiry_rate": {
        "name": {
            "it": "Evidenze valide (non scadute)",
            "en": "Valid Evidence Rate",
            "fr": "Taux de preuves valides",
            "pl": "Wskaźnik ważnych dowodów",
            "tr": "Geçerli Kanıt Oranı",
        },
        "description": {
            "it": "Percentuale di evidenze di controllo ancora valide (non scadute) sul totale.",
            "en": "Percentage of control evidence still valid (not expired) out of total.",
            "fr": "Pourcentage de preuves de contrôle encore valides (non expirées) sur le total.",
            "pl": "Odsetek dowodów kontroli wciąż ważnych (nieprzeterminowanych) względem sumy.",
            "tr": "Toplam içinde hâlâ geçerli (süresi dolmamış) kontrol kanıtlarının yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 90.0,
        "threshold_critical": 75.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["eviden", "prove"],
        "rationale": {
            "it": "ISO 27001 cl.7.5 — le informazioni documentate (evidenze) devono essere aggiornate e non scadute per dimostrare la conformità.",
            "en": "ISO 27001 cl.7.5 — documented information (evidence) must be current and non-expired to demonstrate compliance.",
            "fr": "ISO 27001 cl.7.5 — les informations documentées (preuves) doivent être à jour et non expirées pour démontrer la conformité.",
            "pl": "ISO 27001 cl.7.5 — informacje udokumentowane (dowody) muszą być aktualne i nieprzeterminowane, by wykazać zgodność.",
            "tr": "ISO 27001 cl.7.5 — belgelenmiş bilgi (kanıt) uyumu göstermek için güncel ve süresi dolmamış olmalıdır.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Documenti/Evidenze (M07) via ingest API.",
            "en": "Computed from the Documents/Evidence module (M07) via API ingest.",
            "fr": "Calculé depuis le module Documents/Preuves (M07) via l'API.",
            "pl": "Obliczane z modułu Dokumenty/Dowody (M07) przez API.",
            "tr": "Belgeler/Kanıtlar modülünden (M07) API ile hesaplanır.",
        },
    },
    "open_pdca_over_90days": {
        "name": {
            "it": "PDCA aperti da oltre 90 giorni",
            "en": "PDCA Open Over 90 Days",
            "fr": "PDCA ouverts depuis plus de 90 jours",
            "pl": "PDCA otwarte ponad 90 dni",
            "tr": "90 Günden Uzun Açık PDCA",
        },
        "description": {
            "it": "Numero di cicli PDCA aperti da più di 90 giorni senza avanzamento.",
            "en": "Number of PDCA cycles open for more than 90 days without progress.",
            "fr": "Nombre de cycles PDCA ouverts depuis plus de 90 jours sans progression.",
            "pl": "Liczba cykli PDCA otwartych ponad 90 dni bez postępu.",
            "tr": "İlerleme olmadan 90 günden uzun açık PDCA döngüsü sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 3.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["pdca", "miglioramento"],
        "rationale": {
            "it": "ISO 27001 cl.10.1 — i PDCA bloccati indicano mancato miglioramento continuo del sistema di gestione.",
            "en": "ISO 27001 cl.10.1 — stalled PDCA cycles indicate a lack of continual improvement of the management system.",
            "fr": "ISO 27001 cl.10.1 — des cycles PDCA bloqués révèlent un défaut d'amélioration continue du système de management.",
            "pl": "ISO 27001 cl.10.1 — zablokowane cykle PDCA wskazują na brak ciągłego doskonalenia systemu zarządzania.",
            "tr": "ISO 27001 cl.10.1 — tıkanmış PDCA döngüleri yönetim sisteminin sürekli iyileştirilmediğini gösterir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo PDCA (M11) via ingest API.",
            "en": "Computed from the PDCA module (M11) via API ingest.",
            "fr": "Calculé depuis le module PDCA (M11) via l'API.",
            "pl": "Obliczane z modułu PDCA (M11) przez API.",
            "tr": "PDCA modülünden (M11) API ile hesaplanır.",
        },
    },
    "audit_findings_open_rate": {
        "name": {
            "it": "Quota finding di audit aperti",
            "en": "Open Audit Findings Rate",
            "fr": "Taux de constats d'audit ouverts",
            "pl": "Wskaźnik otwartych ustaleń audytu",
            "tr": "Açık Denetim Bulguları Oranı",
        },
        "description": {
            "it": "Percentuale di finding di audit ancora aperti sul totale registrato.",
            "en": "Percentage of audit findings still open out of the total recorded.",
            "fr": "Pourcentage de constats d'audit encore ouverts sur le total enregistré.",
            "pl": "Odsetek ustaleń audytu wciąż otwartych względem wszystkich zarejestrowanych.",
            "tr": "Kaydedilen toplam içinde hâlâ açık denetim bulgularının yüzdesi.",
        },
        "unit": "%",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 10.0,
        "threshold_critical": 25.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "compliance",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["audit", "finding", "rilievo"],
        "rationale": {
            "it": "ISO 27001 cl.9.2 / cl.10.2 — i finding di audit interno richiedono azioni correttive entro tempi definiti.",
            "en": "ISO 27001 cl.9.2 / cl.10.2 — internal audit findings require corrective actions within defined timelines.",
            "fr": "ISO 27001 cl.9.2 / cl.10.2 — les constats d'audit interne exigent des actions correctives dans des délais définis.",
            "pl": "ISO 27001 cl.9.2 / cl.10.2 — ustalenia audytu wewnętrznego wymagają działań korygujących w określonym czasie.",
            "tr": "ISO 27001 cl.9.2 / cl.10.2 — iç denetim bulguları tanımlı sürelerde düzeltici faaliyet gerektirir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Audit Readiness (M17) via ingest API.",
            "en": "Computed from the Audit Readiness module (M17) via API ingest.",
            "fr": "Calculé depuis le module Audit Readiness (M17) via l'API.",
            "pl": "Obliczane z modułu Audit Readiness (M17) przez API.",
            "tr": "Denetim Hazırlığı modülünden (M17) API ile hesaplanır.",
        },
    },
    # ───────────────────────── TRAINING & AWARENESS ────────────────────────
    "training_completion_rate": {
        "name": {
            "it": "Completamento formazione obbligatoria",
            "en": "Mandatory Training Completion",
            "fr": "Achèvement de la formation obligatoire",
            "pl": "Ukończenie obowiązkowych szkoleń",
            "tr": "Zorunlu Eğitim Tamamlama",
        },
        "description": {
            "it": "Percentuale di utenti che hanno completato la formazione obbligatoria nel periodo.",
            "en": "Percentage of users who completed mandatory training in the period.",
            "fr": "Pourcentage d'utilisateurs ayant terminé la formation obligatoire sur la période.",
            "pl": "Odsetek użytkowników, którzy ukończyli obowiązkowe szkolenie w okresie.",
            "tr": "Dönemde zorunlu eğitimi tamamlayan kullanıcıların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 95.0,
        "threshold_critical": 80.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["formazione", "training", "corso"],
        "rationale": {
            "it": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 6.1.1 / NIS2 Art.20 — formazione e consapevolezza obbligatorie almeno annuali.",
            "en": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 6.1.1 / NIS2 Art.20 — mandatory awareness training at least annually.",
            "fr": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 6.1.1 / NIS2 Art.20 — formation et sensibilisation obligatoires au moins annuelles.",
            "pl": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 6.1.1 / NIS2 Art.20 — obowiązkowe szkolenia świadomościowe co najmniej raz w roku.",
            "tr": "ISO 27001 A.6.3 / cl.7.2 / TISAX ISA 6.1.1 / NIS2 Md.20 — en az yılda bir zorunlu farkındalık eğitimi.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Training (M15) via ingest API.",
            "en": "Computed from the Training module (M15) via API ingest.",
            "fr": "Calculé depuis le module Formation (M15) via l'API.",
            "pl": "Obliczane z modułu Szkolenia (M15) przez API.",
            "tr": "Eğitim modülünden (M15) API ile hesaplanır.",
        },
    },
    "phishing_click_rate": {
        "name": {
            "it": "Tasso di click su phishing simulato",
            "en": "Simulated Phishing Click Rate",
            "fr": "Taux de clic au phishing simulé",
            "pl": "Wskaźnik kliknięć w symulowany phishing",
            "tr": "Simüle Oltalama Tıklama Oranı",
        },
        "description": {
            "it": "Percentuale di utenti che cliccano sui link nelle simulazioni di phishing.",
            "en": "Percentage of users clicking links in phishing simulations.",
            "fr": "Pourcentage d'utilisateurs cliquant sur les liens des simulations de phishing.",
            "pl": "Odsetek użytkowników klikających w linki w symulacjach phishingu.",
            "tr": "Oltalama simülasyonlarında bağlantılara tıklayan kullanıcıların yüzdesi.",
        },
        "unit": "%",
        "aggregation": "avg_value",
        "threshold_direction": "below",
        "threshold_warning": 5.0,
        "threshold_critical": 15.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "training",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3"],
        "match_keywords": ["phishing", "simulazion"],
        "rationale": {
            "it": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — l'efficacia della consapevolezza si misura con simulazioni di phishing periodiche.",
            "en": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — awareness effectiveness is measured via periodic phishing simulations.",
            "fr": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — l'efficacité de la sensibilisation se mesure par des simulations de phishing périodiques.",
            "pl": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — skuteczność świadomości mierzy się okresowymi symulacjami phishingu.",
            "tr": "ISO 27001 A.6.3 / TISAX ISA 6.1.2 — farkındalık etkinliği periyodik oltalama simülasyonlarıyla ölçülür.",
        },
        "checklist_hint": {
            "it": "Popolato via ingest API dalla piattaforma di awareness (es. KnowBe4).",
            "en": "Populated via API ingest from the awareness platform (e.g. KnowBe4).",
            "fr": "Alimenté via l'API depuis la plateforme de sensibilisation (ex. KnowBe4).",
            "pl": "Zasilane przez API z platformy świadomości (np. KnowBe4).",
            "tr": "Farkındalık platformundan (ör. KnowBe4) API ile beslenir.",
        },
    },
    # ───────────────────────── SUPPLIER ────────────────────────────────────
    "suppliers_assessed_rate": {
        "name": {
            "it": "Fornitori critici valutati",
            "en": "Critical Suppliers Assessed",
            "fr": "Fournisseurs critiques évalués",
            "pl": "Ocenieni dostawcy krytyczni",
            "tr": "Değerlendirilen Kritik Tedarikçiler",
        },
        "description": {
            "it": "Percentuale di fornitori critici con valutazione di sicurezza aggiornata.",
            "en": "Percentage of critical suppliers with an up-to-date security assessment.",
            "fr": "Pourcentage de fournisseurs critiques avec une évaluation de sécurité à jour.",
            "pl": "Odsetek dostawców krytycznych z aktualną oceną bezpieczeństwa.",
            "tr": "Güncel güvenlik değerlendirmesine sahip kritik tedarikçilerin yüzdesi.",
        },
        "unit": "%",
        "aggregation": "success_rate",
        "threshold_direction": "above",
        "threshold_warning": 100.0,
        "threshold_critical": 85.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "supplier",
        "frameworks": ["ISO27001", "TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["fornitor", "supplier"],
        "rationale": {
            "it": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — i fornitori critici vanno valutati per la sicurezza della catena di fornitura, almeno annualmente.",
            "en": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — critical suppliers must be assessed for supply-chain security, at least annually.",
            "fr": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — les fournisseurs critiques doivent être évalués pour la sécurité de la chaîne d'approvisionnement, au moins annuellement.",
            "pl": "ISO 27001 A.5.19–A.5.22 / NIS2 Art.21(2)(d) — dostawców krytycznych należy oceniać pod kątem bezpieczeństwa łańcucha dostaw, co najmniej raz w roku.",
            "tr": "ISO 27001 A.5.19–A.5.22 / NIS2 Md.21(2)(d) — kritik tedarikçiler tedarik zinciri güvenliği için en az yılda bir değerlendirilmelidir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Fornitori (M14) via ingest API.",
            "en": "Computed from the Suppliers module (M14) via API ingest.",
            "fr": "Calculé depuis le module Fournisseurs (M14) via l'API.",
            "pl": "Obliczane z modułu Dostawcy (M14) przez API.",
            "tr": "Tedarikçiler modülünden (M14) API ile hesaplanır.",
        },
    },
    "suppliers_critical_unassessed": {
        "name": {
            "it": "Fornitori critici non valutati",
            "en": "Unassessed Critical Suppliers",
            "fr": "Fournisseurs critiques non évalués",
            "pl": "Nieoceni dostawcy krytyczni",
            "tr": "Değerlendirilmemiş Kritik Tedarikçiler",
        },
        "description": {
            "it": "Numero di fornitori critici privi di valutazione di sicurezza valida.",
            "en": "Number of critical suppliers lacking a valid security assessment.",
            "fr": "Nombre de fournisseurs critiques sans évaluation de sécurité valide.",
            "pl": "Liczba dostawców krytycznych bez ważnej oceny bezpieczeństwa.",
            "tr": "Geçerli güvenlik değerlendirmesi olmayan kritik tedarikçi sayısı.",
        },
        "unit": "n°",
        "aggregation": "last_value",
        "threshold_direction": "below",
        "threshold_warning": 1.0,
        "threshold_critical": 3.0,
        "notify_on_warning": True,
        "notify_on_critical": True,
        "source": "api",
        "category": "supplier",
        "frameworks": ["TISAX_L2", "TISAX_L3", "NIS2"],
        "match_keywords": ["fornitor", "supplier"],
        "rationale": {
            "it": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — i fornitori critici non valutati rappresentano un rischio non gestito nella catena di fornitura.",
            "en": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — unassessed critical suppliers represent an unmanaged supply-chain risk.",
            "fr": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — les fournisseurs critiques non évalués constituent un risque non maîtrisé de la chaîne d'approvisionnement.",
            "pl": "TISAX ISA 7.x / NIS2 Art.21(2)(d) — nieocenieni dostawcy krytyczni stanowią niezarządzane ryzyko łańcucha dostaw.",
            "tr": "TISAX ISA 7.x / NIS2 Md.21(2)(d) — değerlendirilmemiş kritik tedarikçiler, yönetilmeyen bir tedarik zinciri riskidir.",
        },
        "checklist_hint": {
            "it": "Calcolato dal modulo Fornitori (M14) via ingest API.",
            "en": "Computed from the Suppliers module (M14) via API ingest.",
            "fr": "Calculé depuis le module Fournisseurs (M14) via l'API.",
            "pl": "Obliczane z modułu Dostawcy (M14) przez API.",
            "tr": "Tedarikçiler modülünden (M14) API ile hesaplanır.",
        },
    },
}


# I KPI dotati di connettore interno (kpi_connectors.INTERNAL_CONNECTORS) si
# popolano da soli leggendo i dati dei moduli GRC: il loro source è "internal"
# (auto-calcolo), non "api" (push esterno). Allineiamo qui source e checklist_hint
# usando il registry come unica fonte di verità, così catalogo, wizard di import
# e task settimanale restano coerenti senza duplicare l'elenco dei codici.
_INTERNAL_HINT = {
    "it": "Calcolato automaticamente dal modulo interno: nessun inserimento manuale o ingest API necessario.",
    "en": "Computed automatically from the internal module: no manual entry or API ingest required.",
    "fr": "Calculé automatiquement depuis le module interne : aucune saisie manuelle ni ingestion API requise.",
    "pl": "Obliczane automatycznie z modułu wewnętrznego: bez ręcznego wprowadzania ani ingestu API.",
    "tr": "Dahili modülden otomatik hesaplanır: manuel giriş veya API beslemesi gerekmez.",
}


def _apply_internal_sources():
    from .kpi_connectors import INTERNAL_CONNECTORS

    for code in INTERNAL_CONNECTORS:
        entry = KPI_CATALOG.get(code)
        if entry is not None:
            entry["source"] = "internal"
            entry["checklist_hint"] = dict(_INTERNAL_HINT)


_apply_internal_sources()


def _text(entry_field: dict, lang: str) -> str:
    """Estrae un campo localizzato con fallback IT → EN → primo disponibile."""
    if not isinstance(entry_field, dict):
        return entry_field or ""
    return (
        entry_field.get(lang)
        or entry_field.get("it")
        or entry_field.get("en")
        or next(iter(entry_field.values()), "")
    )


def localized_catalog(lang: str = "it") -> list:
    """
    Restituisce il catalogo con i testi risolti nella lingua richiesta,
    ordinato per categoria (ordine di CATEGORIES) e poi per nome.
    """
    if lang not in LANGS:
        lang = "it"

    items = []
    for code, entry in KPI_CATALOG.items():
        seed = entry.get("template_seed")
        items.append({
            "kpi_code": code,
            "name": _text(entry["name"], lang),
            "description": _text(entry["description"], lang),
            "unit": entry["unit"],
            "aggregation": entry["aggregation"],
            "threshold_direction": entry["threshold_direction"],
            "threshold_warning": entry["threshold_warning"],
            "threshold_critical": entry["threshold_critical"],
            "notify_on_warning": entry["notify_on_warning"],
            "notify_on_critical": entry["notify_on_critical"],
            "source": entry["source"],
            "category": entry["category"],
            "frameworks": entry["frameworks"],
            "rationale": _text(entry["rationale"], lang),
            "checklist_hint": _text(entry["checklist_hint"], lang),
            "match_keywords": entry.get("match_keywords", []),
            "has_template_seed": seed is not None,
            "template_seed_name": _text(seed["name"], lang) if seed else "",
        })

    cat_order = {c: i for i, c in enumerate(CATEGORIES)}
    items.sort(key=lambda x: (cat_order.get(x["category"], 99), x["name"].lower()))
    return items
