# Generated by Django 5.1.15 on 2026-06-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phishingsimulation',
            options={'ordering': ['-sent_at']},
        ),
    ]
