# Generated by Django 5.2.17 on 2026-09-21 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_controlinstance_next_review_date_and_more'),
        ('documents', '0006_document_code'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
        ('training', '0002_alter_phishingsimulation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='audience_kind',
            field=models.CharField(choices=[('generale', 'Personale'), ('ruoli_critici', 'Ruoli critici'), ('organo_gestione', 'Organo di gestione')], default='generale', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='training_courses', to='controls.control'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='kind',
            field=models.CharField(choices=[('corso', 'Corso'), ('awareness', 'Campagna di sensibilizzazione'), ('phishing', 'Simulazione di phishing')], default='corso', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='validity_months',
            field=models.PositiveSmallIntegerField(blank=True, default=12, null=True),
        ),
        migrations.CreateModel(
            name='TrainingAudience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('headcount', models.PositiveIntegerField()),
                ('headcount_updated_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_audiences', to='plants.plant')),
            ],
            options={
                'ordering': ['plant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='documents.document')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_plans', to='plants.plant')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('audiences', models.ManyToManyField(blank=True, related_name='plan_items', to='training.trainingaudience')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.trainingplan')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('held_on', models.DateField(db_index=True)),
                ('target_count', models.PositiveIntegerField(blank=True, null=True)),
                ('trained_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(blank=True, null=True)),
                ('clicked_count', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_count', models.PositiveIntegerField(blank=True, null=True)),
                ('legacy', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('audiences', models.ManyToManyField(blank=True, related_name='sessions', to='training.trainingaudience')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='documents.evidence')),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.trainingplanitem')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='plants.plant')),
            ],
            options={
                'ordering': ['-held_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plant', 'name'), name='uniq_training_audience_plant_name'),
        ),
        migrations.AddConstraint(
            model_name='trainingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plant', 'year'), name='uniq_training_plan_plant_year', nulls_distinct=False),
        ),
    ]
