# I controlli provati dalle erogazioni passano dal singolo corso a
# un'impostazione per tipo di destinatari. Per non perdere collegamenti, ogni
# controllo già collegato a un corso attivo diventa una regola per i
# destinatari di quel corso. I valori predefiniti si aggiungono con
# `load_training_evidence_controls`.

# Generated by Django 5.2.17 on 2026-09-21 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_course_controls(apps, schema_editor):
    TrainingCourse = apps.get_model("training", "TrainingCourse")
    TrainingEvidenceControl = apps.get_model("training", "TrainingEvidenceControl")
    pairs = set()
    for course in TrainingCourse.objects.filter(deleted_at__isnull=True, status="attivo"):
        for control_id in course.controls.values_list("pk", flat=True):
            pairs.add((course.audience_kind, control_id))
    for audience_kind, control_id in sorted(pairs, key=str):
        TrainingEvidenceControl.objects.create(audience_kind=audience_kind, control_id=control_id)


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_controlinstance_next_review_date_and_more'),
        ('training', '0005_training_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEvidenceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audience_kind', models.CharField(choices=[('generale', 'Personale'), ('ruoli_critici', 'Ruoli critici'), ('organo_gestione', 'Organo di gestione')], max_length=20)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_evidence_rules', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['audience_kind', 'control__external_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('audience_kind', 'control'), name='uniq_training_evidence_control')],
            },
        ),
        migrations.RunPython(copy_course_controls, migrations.RunPython.noop),
    ]
