# Elimina i dati per persona della vecchia formazione (iscrizioni ed esiti
# phishing per dipendente) e i collegamenti deprecati del corso
# (`framework_refs`, `controls`). I conteggi sono già stati portati nelle
# sessioni `legacy` dalla 0004 e i controlli nelle regole per destinatari dalla
# 0006, che girano prima nello stesso `migrate`. Anteprima prima del deploy:
# `manage.py check_training_migration_readiness`.

# Generated by Django 5.2.17 on 2026-09-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_training_evidence_controls'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trainingenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainingenrollment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trainingenrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='controls',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='framework_refs',
        ),
        migrations.DeleteModel(
            name='PhishingSimulation',
        ),
        migrations.DeleteModel(
            name='TrainingEnrollment',
        ),
    ]
