# Generated by Django 5.1.15 on 2026-03-14 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcacycle',
            name='act_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pdcacycle',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdcacycle',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_pdca_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pdcacycle',
            name='fase_corrente',
            field=models.CharField(choices=[('plan', 'PLAN'), ('do', 'DO'), ('check', 'CHECK'), ('act', 'ACT'), ('chiuso', 'Chiuso')], default='plan', max_length=10),
        ),
    ]
