# Generated by Django 5.1.15 on 2026-03-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_category_alter_document_document_type_and_more'),
        ('pdca', '0002_pdcacycle_act_description_pdcacycle_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcacycle',
            name='check_outcome',
            field=models.CharField(blank=True, help_text='Esito CHECK: ok/partial/ko — se ko apre nuovo ciclo', max_length=20),
        ),
        migrations.AddField(
            model_name='pdcacycle',
            name='reopened_as',
            field=models.ForeignKey(blank=True, help_text='Se CHECK=ko questo ciclo ha generato un nuovo PLAN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_from', to='pdca.pdcacycle'),
        ),
        migrations.AddField(
            model_name='pdcaphase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdcaphase',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pdca_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdcaphase',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text='Obbligatoria per fase DO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdca_phases', to='documents.evidence'),
        ),
        migrations.AddField(
            model_name='pdcaphase',
            name='outcome',
            field=models.CharField(blank=True, choices=[('ok', 'Efficace'), ('partial', 'Parzialmente efficace'), ('ko', 'Non efficace')], help_text='Obbligatorio per fase CHECK', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdcacycle',
            name='act_description',
            field=models.TextField(blank=True, help_text='Descrizione standardizzazione — obbligatoria per chiudere'),
        ),
    ]
