# Generated by Django 5.1.15 on 2026-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0003_pdcacycle_check_outcome_pdcacycle_reopened_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcacycle',
            name='audit_subtype',
            field=models.CharField(blank=True, choices=[('interno', 'Audit interno'), ('seconda_parte', 'Seconda parte'), ('terza_parte', 'Terza parte')], help_text='Tipo di audit sorgente (solo se trigger_type=audit)', max_length=20),
        ),
        migrations.AddField(
            model_name='pdcacycle',
            name='motivo_archiviazione',
            field=models.TextField(blank=True, help_text='Obbligatorio per archiviare: motivo per cui lo spunto non viene perseguito'),
        ),
        migrations.AddField(
            model_name='pdcacycle',
            name='riferimento_finding',
            field=models.CharField(blank=True, help_text='Numero/riferimento del finding di audit (es. NC-2026-04-01)', max_length=200),
        ),
        migrations.AlterField(
            model_name='pdcacycle',
            name='fase_corrente',
            field=models.CharField(choices=[('plan', 'PLAN'), ('do', 'DO'), ('check', 'CHECK'), ('act', 'ACT'), ('chiuso', 'Chiuso'), ('archiviato', 'Archiviato')], default='plan', max_length=10),
        ),
    ]
