# Generated by Django 5.1.15 on 2026-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0004_pdca_archivia_riferimento_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcacycle',
            name='descrizione',
            field=models.TextField(blank=True, help_text='Descrizione estesa del finding o dello spunto di miglioramento'),
        ),
    ]
