# Generated by Django 5.1.15 on 2026-06-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0005_pdca_descrizione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdcacycle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pdcaphase',
            options={'ordering': ['created_at']},
        ),
    ]
