# Generated by Django 5.2.17 on 2026-09-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0006_alter_pdcacycle_options_alter_pdcaphase_options'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdcacycle',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
    ]
