# Generated by Django 5.2.17 on 2026-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0008_sync_audit_subtype_from_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcacycle',
            name='action_owner',
            field=models.CharField(blank=True, help_text="Responsabile dell'azione (preferibilmente la funzione, es. HR Manager — sito)", max_length=200),
        ),
        migrations.AddField(
            model_name='pdcacycle',
            name='target_date',
            field=models.DateField(blank=True, help_text="Data prevista di completamento dell'azione", null=True),
        ),
    ]
