# Generated by Django 5.2.17 on 2026-09-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentapproval_version'),
        ('pdca', '0009_action_owner_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcacycle',
            name='archive_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdca_archived_cycles', to='documents.evidence'),
        ),
    ]
