# Generated by Django 5.1.15 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='nis2_notifiable',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no'), ('da_valutare', 'da_valutare')], db_index=True, default='da_valutare', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('bassa', 'bassa'), ('media', 'media'), ('alta', 'alta'), ('critica', 'critica')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('aperto', 'aperto'), ('in_analisi', 'in_analisi'), ('chiuso', 'chiuso')], db_index=True, default='aperto', max_length=20),
        ),
    ]
