# Generated by Django 5.1.15 on 2026-06-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_nis2_config_classification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-detected_at']},
        ),
    ]
