# Generated by Django 5.1.15 on 2026-06-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_alter_incident_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rca',
            options={'ordering': ['-created_at']},
        ),
    ]
