# Generated by Django 5.1.15 on 2026-03-13 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='IT', max_length=2)),
                ('risk_level', models.CharField(choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='medio', max_length=10)),
                ('status', models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('terminato', 'Terminato')], default='attivo', max_length=15)),
                ('framework_refs', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_suppliers', to=settings.AUTH_USER_MODEL)),
                ('plants', models.ManyToManyField(blank=True, related_name='suppliers', to='plants.plant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_date', models.DateField()),
                ('status', models.CharField(choices=[('pianificato', 'Pianificato'), ('completato', 'Completato')], default='pianificato', max_length=15)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
