# Generated by Django 5.1.15 on 2026-03-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierassessment',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierassessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supplier_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierassessment',
            name='score_bcp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierassessment',
            name='score_governance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierassessment',
            name='score_overall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierassessment',
            name='score_security',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierassessment',
            name='status',
            field=models.CharField(choices=[('pianificato', 'Pianificato'), ('in_corso', 'In corso'), ('completato', 'Completato'), ('approvato', 'Approvato'), ('rifiutato', 'Rifiutato')], default='pianificato', max_length=15),
        ),
    ]
