# Generated by Django 5.1.15 on 2026-04-10 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_questionnaire_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='body',
            field=models.TextField(help_text='Variabili: {supplier_name}, {questionnaire_link}'),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplierquestionnaire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
