# Generated by Django 5.1.15 on 2026-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_document_supplier_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cpv_codes',
            field=models.JSONField(blank=True, default=list, help_text='Lista di oggetti {code, label} — Codici CPV della fornitura'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nis2_relevance_criterion',
            field=models.CharField(blank=True, choices=[('ict', 'Fornitura ICT strutturale (criterio a)'), ('non_fungibile', 'Non fungibilità (criterio b)'), ('entrambi', 'Entrambi (a + b)')], help_text='Criterio di rilevanza NIS2: ICT strutturale (a), non fungibilità (b), o entrambi', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nis2_relevant',
            field=models.BooleanField(default=False, help_text='Fornitore rilevante ai fini NIS2 (ACN Delibera 127434)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_concentration_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% di concentrazione della fornitura — soglia TPRM: <20% bassa, 20-50% media, >50% critica', max_digits=5, null=True),
        ),
    ]
