# Generated by Django 5.1.15 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_acn_nis2_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierEvaluationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(default=dict, help_text='Pesi per ciascuno dei 6 parametri (somma = 1.00)')),
                ('parameter_labels', models.JSONField(default=dict, help_text='Nome parametro e label dei 5 livelli (1=basso rischio … 5=alto rischio)')),
                ('risk_thresholds', models.JSONField(default=dict, help_text='Soglie weighted_score per classificazione (>=)')),
                ('assessment_validity_months', models.PositiveSmallIntegerField(default=12, help_text='Mesi di validità di un assessment esterno approvato. Oltre, scade e non partecipa al risk_adj.')),
                ('nis2_concentration_bump', models.BooleanField(default=True, help_text='Se True, fornitori NIS2-rilevanti con concentrazione critica subiscono bump +1 classe sul risk_adj.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione valutazione fornitori',
                'verbose_name_plural': 'Configurazione valutazione fornitori',
            },
        ),
    ]
