# Generated by Django 5.1.15 on 2026-04-22 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplierevaluationconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInternalEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score_impatto', models.PositiveSmallIntegerField()),
                ('score_accesso', models.PositiveSmallIntegerField()),
                ('score_dati', models.PositiveSmallIntegerField()),
                ('score_dipendenza', models.PositiveSmallIntegerField()),
                ('score_integrazione', models.PositiveSmallIntegerField()),
                ('score_compliance', models.PositiveSmallIntegerField()),
                ('weighted_score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('risk_class', models.CharField(choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], max_length=10)),
                ('weights_snapshot', models.JSONField(default=dict)),
                ('thresholds_snapshot', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_evaluations', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['supplier', 'is_current'], name='suppliers_s_supplie_2f61a0_idx')],
            },
        ),
    ]
