# Generated by Django 5.1.15 on 2026-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_supplierinternalevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='internal_risk_level',
            field=models.CharField(blank=True, choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='', help_text='Classe di rischio da valutazione interna corrente (calcolato, read-only)', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='risk_adj',
            field=models.CharField(blank=True, choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='', help_text='Rischio aggiustato: max(interno, assessment esterno valido) + bump NIS2 se applicabile (calcolato, read-only)', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='risk_adj_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
