# Generated by Django 5.1.15 on 2026-04-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_supplier_internal_risk_level_supplier_risk_adj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierevaluationconfig',
            name='questionnaire_validity_months',
            field=models.PositiveSmallIntegerField(default=12, help_text="Mesi di validità di un questionario valutato. Determina l'expires_at al momento della registrazione della risposta."),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='risk_adj',
            field=models.CharField(blank=True, choices=[('basso', 'Basso'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='', help_text='Rischio aggiustato: max(interno, questionario valutato non scaduto, audit terze parti approvato entro validità) + bump NIS2 (calcolato, read-only)', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierevaluationconfig',
            name='assessment_validity_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Mesi di validità di un audit terze parti (SupplierAssessment approvato). Oltre la finestra, non partecipa al calcolo risk_adj.'),
        ),
    ]
