# Generated by Django 5.1.15 on 2026-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_add_questionnaire_validity_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text='Sito web / dominio principale del fornitore — usato dal modulo OSINT per monitoraggio passivo.', max_length=500),
        ),
    ]
