# Generated by Django 5.1.15 on 2026-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_supplier_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='additional_emails',
            field=models.JSONField(blank=True, default=list, help_text="Email aggiuntive (CC) usate all'invio questionari/notifiche. La email primaria resta in `email` (TO)."),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='sent_cc_snapshot',
            field=models.JSONField(blank=True, default=list, help_text="Snapshot delle email in CC al momento dell'invio (audit trail)."),
        ),
    ]
