# Generated by Django 5.1.15 on 2026-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_supplier_additional_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='concentration_notified_threshold',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
