# Generated by Django 5.1.15 on 2026-06-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_supplier_concentration_notified_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierassessment',
            options={'ordering': ['-assessment_date']},
        ),
    ]
