# Generated by Django 5.2.17 on 2026-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_alter_supplierassessment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tisax_relevant',
            field=models.BooleanField(default=False, help_text='Fornitore rilevante ai fini TISAX: tratta informazioni del perimetro TISAX (es. dati/prototipi dei clienti OEM) o accede ai sistemi in scope (VDA ISA 6.1.1)'),
        ),
    ]
