# Generated by Django 5.2.17 on 2026-09-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_supplier_uniq_vat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='service_urls',
            field=models.JSONField(blank=True, default=list, help_text="URL dei servizi del fornitore usati dall'azienda (es. https://portale.fornitore.it)"),
        ),
    ]
