# Generated by Django 5.1.15 on 2026-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source_module',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
