# Generated by Django 5.1.15 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_source_id_task_source_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], db_index=True, default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('aperto', 'Aperto'), ('in_corso', 'In corso'), ('completato', 'Completato'), ('annullato', 'Annullato'), ('scaduto', 'Scaduto')], db_index=True, default='aperto', max_length=15),
        ),
    ]
