# Generated by Django 5.1.15 on 2026-06-02 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_plant_additional_domains_plant_domain'),
        ('tasks', '0004_checklisttemplate_checklistrun_checklisttemplateitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrunitem',
            name='text_value',
            field=models.TextField(blank=True, help_text='Valorizzato solo se template_item.item_type=text'),
        ),
        migrations.AddField(
            model_name='checklistrunitem',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valorizzato solo se template_item.item_type=numeric', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='item_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('numeric', 'Numerico'), ('text', 'Testo libero')], default='checkbox', max_length=10),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='numeric_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='numeric_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valore minimo accettabile per item numeric', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Es: %, ore, GB, n° — solo per item_type=numeric', max_length=20),
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kpi_code', models.CharField(help_text='Es: backup_success_rate, vuln_critical_open', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='%, ore, n°', max_length=20)),
                ('source', models.CharField(choices=[('checklist', 'Checklist'), ('api', 'API esterna'), ('manual', 'Inserimento manuale')], db_index=True, default='checklist', max_length=15)),
                ('checklist_item_filter', models.CharField(blank=True, help_text='Testo parziale item da aggregare, blank=tutti', max_length=500)),
                ('aggregation', models.CharField(choices=[('success_rate', 'Tasso di successo (% run completati)'), ('avg_value', 'Media valori numerici'), ('last_value', 'Ultimo valore registrato'), ('count_ok', 'Conteggio item OK'), ('count_fail', 'Conteggio item KO')], default='success_rate', max_length=20)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('threshold_direction', models.CharField(choices=[('above', 'Sopra soglia=ok'), ('below', 'Sotto soglia=ok')], default='above', help_text='above: valore alto è buono (es success_rate). below: valore basso è buono (es vuln aperte)', max_length=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notify_on_warning', models.BooleanField(default=True)),
                ('notify_on_critical', models.BooleanField(default=True)),
                ('checklist_template', models.ForeignKey(blank=True, help_text='Template sorgente se source=checklist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_definitions', to='tasks.checklisttemplate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, help_text='null=KPI globale multi-plant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpi_definitions', to='plants.plant')),
            ],
            options={
                'ordering': ['kpi_code'],
            },
        ),
        migrations.CreateModel(
            name='OperationalKpiSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField(db_index=True, help_text='Lunedì della settimana')),
                ('value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critico'), ('no_data', 'Nessun dato')], db_index=True, default='no_data', max_length=10)),
                ('source', models.CharField(choices=[('checklist', 'Checklist'), ('api', 'API esterna'), ('manual', 'Inserimento manuale')], default='checklist', max_length=15)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0, help_text='N run analizzati per questo snapshot')),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kpi_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='tasks.kpidefinition')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_kpi_snapshots', to='plants.plant')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('kpi_definition', 'plant', 'week_start')},
            },
        ),
    ]
