# Generated by Django 5.1.15 on 2026-06-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_checklistrunitem_text_value_checklistrunitem_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['task_id', 'created_at']},
        ),
    ]
