# Generated by Django 5.1.15 on 2026-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Solo per frequenza giornaliera: giorni 0-6 (lun-dom). Vuoto=tutti.'),
        ),
    ]
