# Generated by Django 5.2.17 on 2026-08-24 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
        ('tasks', '0008_kpi_internal_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidefinition',
            name='kpi_code',
            field=models.CharField(db_index=True, help_text='Es: backup_success_rate, vuln_critical_open', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='kpidefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('plant__isnull', False)), fields=('kpi_code', 'plant'), name='uniq_active_kpi_code_per_plant'),
        ),
        migrations.AddConstraint(
            model_name='kpidefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('plant__isnull', True)), fields=('kpi_code',), name='uniq_active_kpi_code_global'),
        ),
    ]
