# Generated by Django 5.2.17 on 2026-08-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
        ('tasks', '0009_alter_kpidefinition_kpi_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidefinition',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='Sito che traccia questo KPI con le proprie soglie. null = definizione globale, usata come default dai siti che non hanno una definizione propria per lo stesso kpi_code.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpi_definitions', to='plants.plant'),
        ),
    ]
