# Generated by Django 5.2.17 on 2026-08-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_kpidefinition_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='day_of_month',
            field=models.IntegerField(default=1, help_text='Solo per frequenza mensile: giorno 1-28, oppure 0 = ultimo giorno del mese.'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Giornaliera: giorni 0-6 (lun-dom), vuoto=tutti. Settimanale: il primo giorno indicato, vuoto=lunedì.'),
        ),
    ]
