# Generated by Django 5.2.17 on 2026-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_checklisttemplate_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='start_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Trimestrale/semestrale/annuale: mese di partenza del ciclo (1-12).'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='day_of_month',
            field=models.IntegerField(default=1, help_text='Frequenze mensile/trimestrale/semestrale/annuale: giorno 1-28 del mese di apertura del periodo, oppure 0 = ultimo giorno del mese.'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Giornaliera'), ('weekly', 'Settimanale'), ('monthly', 'Mensile'), ('quarterly', 'Trimestrale'), ('semiannual', 'Semestrale'), ('annual', 'Annuale'), ('ad_hoc', 'Ad hoc')], db_index=True, default='daily', max_length=10),
        ),
    ]
