# Generated by Django 5.2.17 on 2026-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_checklisttemplate_start_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Nessuna'), ('daily', 'Giornaliera'), ('weekly', 'Settimanale'), ('monthly', 'Mensile'), ('quarterly', 'Trimestrale'), ('semiannual', 'Semestrale'), ('yearly', 'Annuale')], default='none', max_length=15),
        ),
    ]
