# Generated by Django 5.2.17 on 2026-08-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidefinition',
            name='checklist_item',
            field=models.ForeignKey(blank=True, help_text='Voce del template da aggregare; vuoto = tutte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_definitions', to='tasks.checklisttemplateitem'),
        ),
        migrations.AlterField(
            model_name='kpidefinition',
            name='checklist_item_filter',
            field=models.CharField(blank=True, help_text='Storico: testo parziale della voce da aggregare. Usato solo se `checklist_item` non è valorizzata.', max_length=500),
        ),
    ]
