# Generated by Django 5.2.17 on 2026-08-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_asset_type'),
        ('tasks', '0014_kpidefinition_checklist_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrun',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_runs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='facility_category',
            field=models.CharField(blank=True, help_text='Categoria di impianti su cui espandere la checklist (vuoto = una sola checklist per sito, non legata a un impianto).', max_length=20),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='records_maintenance',
            field=models.BooleanField(default=False, help_text="Al completamento aggiorna ultima manutenzione ed esito sull'impianto."),
        ),
    ]
