# Generated by Django 5.1.15 on 2026-03-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='source_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_from', to='controls.control'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='target_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_to', to='controls.control'),
        ),
        migrations.AddField(
            model_name='framework',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='controls.framework'),
        ),
        migrations.AddField(
            model_name='control',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='controls.framework'),
        ),
        migrations.AlterUniqueTogether(
            name='controlinstance',
            unique_together={('plant', 'control')},
        ),
        migrations.AlterUniqueTogether(
            name='controldomain',
            unique_together={('framework', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('framework', 'external_id')},
        ),
    ]
