# Generated by Django 5.1.15 on 2026-03-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmapping',
            name='relationship',
            field=models.CharField(choices=[('equivalente', 'Equivalente'), ('parziale', 'Parziale'), ('correlato', 'Correlato'), ('covers', 'Copre'), ('extends', 'Estende')], max_length=20),
        ),
    ]
