# Generated by Django 5.1.15 on 2026-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_alter_controlmapping_relationship'),
        ('documents', '0002_document_document_type_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='evidences',
            field=models.ManyToManyField(blank=True, related_name='control_instances', to='documents.evidence'),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='last_evaluated_note',
            field=models.TextField(blank=True),
        ),
    ]
