# Generated by Django 5.1.15 on 2026-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_controlinstance_evidences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_category',
            field=models.CharField(blank=True, choices=[('tecnico', 'Tecnico'), ('procedurale', 'Procedurale'), ('organizzativo', 'Organizzativo'), ('composito', 'Composito')], default='procedurale', max_length=20),
        ),
        migrations.AddField(
            model_name='control',
            name='evidence_requirement',
            field=models.JSONField(blank=True, default=dict, help_text='Struttura: {documents:[{type,mandatory,description}], evidences:[{type,mandatory,max_age_days,description}], min_documents, min_evidences, notes}'),
        ),
    ]
