# Generated by Django 5.1.15 on 2026-03-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_control_control_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='applicability',
            field=models.CharField(choices=[('applicabile', 'Applicabile'), ('escluso', 'Escluso'), ('non_pertinente', 'Non pertinente')], default='applicabile', max_length=20),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='approved_in_soa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='exclusion_justification',
            field=models.TextField(blank=True, help_text='Obbligatorio se applicability=escluso. Motivazione formale per SOA ISO 27001.'),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='maturity_level',
            field=models.IntegerField(blank=True, help_text='0=non implementato, 1=ad-hoc, 2=pianificato, 3=definito, 4=gestito, 5=ottimizzato', null=True),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='maturity_level_override',
            field=models.BooleanField(default=False, help_text='Se True il maturity_level è stato inserito manualmente e non viene ricalcolato automaticamente'),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='soa_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='soa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soa_approved_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
