# Generated by Django 5.1.15 on 2026-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_controlinstance_applicability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='needs_revaluation',
            field=models.BooleanField(default=False, help_text='True se un change recente richiede rivalutazione'),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='needs_revaluation_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
