# Generated by Django 5.1.15 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_controlinstance_needs_revaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlinstance',
            name='status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('parziale', 'Parziale'), ('gap', 'Gap'), ('na', 'N/A'), ('non_valutato', 'Non valutato')], db_index=True, default='non_valutato', max_length=20),
        ),
    ]
