# Generated by Django 5.1.15 on 2026-06-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetsw_vendor_url'),
        ('controls', '0008_alter_controlinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='control_instances', to='assets.asset'),
        ),
    ]
