# Generated by Django 5.1.15 on 2026-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0009_controlinstance_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='Sotto-requisiti normativi granulari (es. misure ACN NIS2). Struttura: [{punto, applies_to:[essential|important], ambiti_politiche, translations:{<lang>:{text}}}]'),
        ),
    ]
