# Generated by Django 5.1.15 on 2026-06-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0010_control_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['framework_id', 'external_id']},
        ),
        migrations.AlterModelOptions(
            name='controlinstance',
            options={'ordering': ['plant_id', 'control_id']},
        ),
    ]
