# Generated by Django 5.2.17 on 2026-08-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_alter_control_options_alter_controlinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='controlinstance',
            name='review_frequency_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cadenza di riverifica in mesi; vuoto = cadenza della policy del sito.', null=True),
        ),
    ]
