# Generated by Django 5.2.17 on 2026-09-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_controlinstance_next_review_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='implementation_description',
            field=models.TextField(blank=True),
        ),
    ]
