# Generated by Django 5.2.17 on 2026-09-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0013_controlinstance_implementation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='implementation_interview',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
