# Generated by Django 5.2.17 on 2026-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0014_controlinstance_implementation_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinstance',
            name='document_degraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
