# Generated by Django 5.1.15 on 2026-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalprocess',
            name='mbco_pct',
            field=models.IntegerField(blank=True, help_text='Minimum Business Continuity Objective — % of normal capacity', null=True),
        ),
        migrations.AddField(
            model_name='criticalprocess',
            name='mtpd_hours',
            field=models.IntegerField(blank=True, help_text='Maximum Tolerable Period of Disruption (hours)', null=True),
        ),
        migrations.AddField(
            model_name='criticalprocess',
            name='rpo_target_hours',
            field=models.IntegerField(blank=True, help_text='Recovery Point Objective target (hours)', null=True),
        ),
        migrations.AddField(
            model_name='criticalprocess',
            name='rto_target_hours',
            field=models.IntegerField(blank=True, help_text='Recovery Time Objective target (hours)', null=True),
        ),
    ]
