# Generated by Django 5.1.15 on 2026-06-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0003_criticalprocess_mbco_pct_criticalprocess_mtpd_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticalprocess',
            options={'ordering': ['plant_id', 'name']},
        ),
        migrations.AlterModelOptions(
            name='riskdecision',
            options={'ordering': ['-decided_at']},
        ),
        migrations.AlterModelOptions(
            name='treatmentoption',
            options={'ordering': ['-created_at']},
        ),
    ]
