# Generated by Django 5.2.17 on 2026-10-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bia', '0004_alter_criticalprocess_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentoption',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatmentoption',
            name='process',
        ),
        migrations.DeleteModel(
            name='RiskDecision',
        ),
        migrations.DeleteModel(
            name='TreatmentOption',
        ),
    ]
