# Generated by Django 5.1.15 on 2026-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL del logo per questo sito (usato in report/export).'),
        ),
    ]
