# Generated by Django 5.1.15 on 2026-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='logo_url',
            field=models.CharField(blank=True, help_text='URL del logo per questo sito (usato in report/export). Può essere assoluto o relativo (es. /media/...).', max_length=500),
        ),
    ]
