# Generated by Django 5.1.15 on 2026-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_nis2_entity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='nis2_subsector',
            field=models.CharField(blank=True, help_text='Sottosettore NIS2 — usato in notifiche CSIRT', max_length=100),
        ),
    ]
