# Generated by Django 5.1.15 on 2026-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_nis2_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='additional_domains',
            field=models.JSONField(blank=True, default=list, help_text='Domini aggiuntivi associati al sito (es. plant-milano.azienda.it). Array di stringhe. Letti dal modulo OSINT.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='domain',
            field=models.CharField(blank=True, help_text='Dominio internet principale del sito (es. azienda.it) — usato dal modulo OSINT per monitoraggio passivo.', max_length=255),
        ),
    ]
