# Generated by Django 5.1.15 on 2026-06-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_plant_additional_domains_plant_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['code']},
        ),
    ]
