# Generated by Django 5.1.15 on 2026-06-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_businessunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantframework',
            options={'ordering': ['plant_id', 'framework_id']},
        ),
    ]
