# Generated by Django 5.1.15 on 2026-03-14 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('policy', 'Policy'), ('procedura', 'Procedura'), ('manuale', 'Manuale ISMS'), ('contratto', 'Contratto/NDA'), ('registro', 'Registro'), ('altro', 'Altro')], default='policy', max_length=20),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('log', 'Log di sistema'), ('report', 'Report'), ('verbale', 'Verbale'), ('certificato', 'Certificato'), ('test_result', 'Risultato test'), ('altro', 'Altro')], default='altro', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='plants.plant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['valid_until'],
            },
        ),
    ]
