# Generated by Django 5.1.15 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document_type_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('politica', 'Politica'), ('procedura', 'Procedura'), ('istruzione', 'Istruzione operativa'), ('registro', 'Registro'), ('evidence', 'Evidence'), ('verbale', 'Verbale'), ('contratto', 'Contratto'), ('altro', 'Altro')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('policy', 'Policy'), ('procedura', 'Procedura'), ('manuale', 'Manuale ISMS'), ('contratto', 'Contratto/NDA'), ('registro', 'Registro'), ('altro', 'Altro')], db_index=True, default='policy', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='review_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('revisione', 'In revisione'), ('approvazione', 'In approvazione'), ('approvato', 'Approvato'), ('archiviato', 'Archiviato')], db_index=True, default='bozza', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='valid_until',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
