# Generated by Django 5.1.15 on 2026-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_category_alter_document_document_type_and_more'),
        ('plants', '0006_alter_plant_nis2_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_plants',
            field=models.ManyToManyField(blank=True, help_text='Plant aggiuntivi che possono vedere questo documento senza essere il proprietario', related_name='shared_documents', to='plants.plant'),
        ),
    ]
