# Generated by Django 5.1.15 on 2026-04-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_shared_plants'),
        ('suppliers', '0005_document_supplier_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nda_documents', to='suppliers.supplier'),
        ),
    ]
