# Generated by Django 5.1.15 on 2026-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_supplier_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_code',
            field=models.CharField(blank=True, db_index=True, help_text='Codice identificativo del documento (es. D-ITA-INF-001). Libero, unico per convenzione aziendale.', max_length=50),
        ),
    ]
