# Generated by Django 5.2.17 on 2026-09-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_code'),
        ('governance', '0013_documentworkflowpolicy_approval_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapproval',
            name='approval_mode',
            field=models.CharField(blank=True, choices=[('in_app', 'In applicazione'), ('delibera', "Delibera dell'organo")], max_length=10),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='governing_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to='governance.securitycommittee'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='resolution_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='review_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
