# Generated by Django 5.2.17 on 2026-09-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentapproval_approval_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='version_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
