# Generated by Django 5.2.17 on 2026-09-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentversion_version_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapproval',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='documents.documentversion'),
        ),
    ]
