# Generated by Django 5.2.17 on 2026-09-29 10:24

from django.db import migrations, models


def mark_existing_word_versions(apps, schema_editor):
    """Le versioni Word già caricate diventano "da generare": le converte il
    comando convert_document_pdfs (o il passaggio notturno), non la migrazione,
    che non deve dipendere dal servizio di conversione."""
    DocumentVersion = apps.get_model("documents", "DocumentVersion")
    qs = DocumentVersion.objects.filter(deleted_at__isnull=True).exclude(storage_path="")
    ids = [
        v.pk for v in qs.only("pk", "file_name", "storage_path")
        if (v.file_name or v.storage_path).lower().rsplit(".", 1)[-1] in ("doc", "docx")
    ]
    DocumentVersion.objects.filter(pk__in=ids).update(pdf_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentapproval_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='pdf_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='pdf_status',
            field=models.CharField(choices=[('na', 'Non prevista'), ('pending', 'Da generare'), ('ok', 'Disponibile'), ('failed', 'Conversione non riuscita')], default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='pdf_storage_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(mark_existing_word_versions, migrations.RunPython.noop),
    ]
