# Generated by Django 5.2.17 on 2026-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentversion_pdf'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='shared_plants',
            field=models.ManyToManyField(blank=True, help_text='Plant aggiuntivi che possono vedere e collegare questa evidenza senza esserne il proprietario', related_name='shared_evidences', to='plants.plant'),
        ),
    ]
