# Generated by Django 5.1.15 on 2026-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
