# Generated by Django 5.1.15 on 2026-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backuprecord_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('running', 'In corso'), ('completed', 'Completato'), ('failed', 'Fallito'), ('restoring', 'Ripristino in corso'), ('restored', 'Ripristinato')], db_index=True, default='pending', max_length=20),
        ),
    ]
