# Generated by Django 5.1.15 on 2026-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_alter_backuprecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('auto', 'Automatico'), ('manual', 'Manuale'), ('imported', 'Importato')], default='manual', max_length=10),
        ),
    ]
