# Generated by Django 5.1.15 on 2026-06-04 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=32, unique=True)),
                ('code', models.CharField(max_length=64)),
                ('module', models.CharField(blank=True, max_length=40)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(blank=True, max_length=10)),
                ('plant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('params_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Aperto'), ('snoozed', 'Rimandato'), ('accepted_risk', 'Rischio accettato'), ('resolved', 'Risolto')], default='open', max_length=15)),
                ('owner_role', models.CharField(blank=True, max_length=40)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('accepted_until', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='cockpit_ins_status_32e03e_idx'), models.Index(fields=['code', 'status'], name='cockpit_ins_code_d32bf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('taken_on', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('areas', models.JSONField(blank=True, default=dict)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_on'],
                'constraints': [models.UniqueConstraint(fields=('plant_id', 'taken_on'), name='cockpit_posture_one_per_day')],
            },
        ),
    ]
