# Generated by Django 5.1.15 on 2026-03-14 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreview',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approval_status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('in_review', 'In revisione'), ('approvato', 'Approvato'), ('rifiutato', 'Rifiutato')], default='bozza', max_length=20),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='snapshot_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='snapshot_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
