# Generated by Django 5.1.15 on 2026-06-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0002_managementreview_approval_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewaction',
            options={'ordering': ['due_date', 'created_at']},
        ),
    ]
