# Generated by Django 5.2.17 on 2026-09-17 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0003_alter_reviewaction_options'),
        ('pdca', '0006_alter_pdcacycle_options_alter_pdcaphase_options'),
        ('tasks', '0015_checklistrun_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreview',
            name='executive_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='executive_summary_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='executive_summary_draft_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='executive_summary_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='decision_type',
            field=models.CharField(choices=[('miglioramento', 'Opportunità di miglioramento'), ('modifica_sgsi', 'Modifica al SGSI'), ('risorse', 'Risorse'), ('altro', 'Altro')], default='miglioramento', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='pdca_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to='pdca.pdcacycle'),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='ReviewAgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default='custom', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('mandatory', models.BooleanField(default=False)),
                ('discussion', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='management_review.managementreview')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='agenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='management_review.reviewagendaitem'),
        ),
    ]
