# Generated by Django 5.2.17 on 2026-09-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_securityobjective_securityobjectivemeasurement_and_more'),
        ('management_review', '0005_seed_iso_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaction',
            name='security_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to='governance.securityobjective'),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='decision_type',
            field=models.CharField(choices=[('miglioramento', 'Opportunità di miglioramento'), ('modifica_sgsi', 'Modifica al SGSI'), ('risorse', 'Risorse'), ('obiettivo', 'Obiettivo di sicurezza'), ('altro', 'Altro')], default='miglioramento', max_length=20),
        ),
    ]
