# Generated by Django 5.2.17 on 2026-09-18 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _label(u):
    return f"{u.first_name} {u.last_name}".strip() or u.email or u.username


def forwards(apps, schema_editor):
    """Presidente e partecipanti (utenti) diventano righe di partecipazione,
    tutte «presente»: è ciò che il verbale dichiarava finora. Le approvazioni
    già registrate erano fatte dall'app."""
    Review = apps.get_model("management_review", "ManagementReview")
    Participant = apps.get_model("management_review", "ReviewParticipant")

    for r in Review.objects.all():
        order = 0
        seen = set()
        if r.chair_id:
            Participant.objects.create(
                review=r, user_id=r.chair_id, full_name=_label(r.chair),
                body_role="presidente", is_chair=True, attendance="presente", order=order,
            )
            seen.add(r.chair_id)
            order += 1
        for u in r.attendees.all():
            if u.pk in seen:
                continue
            Participant.objects.create(
                review=r, user=u, full_name=_label(u),
                body_role="membro", attendance="presente", order=order,
            )
            order += 1
        if r.approval_status == "approvato" and not r.approval_mode:
            r.approval_mode = "in_app"
            r.save(update_fields=["approval_mode"])


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_governing_bodies'),
        ('management_review', '0006_reviewaction_security_objective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreview',
            name='approval_document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approval_mode',
            field=models.CharField(blank=True, choices=[('in_app', 'In applicazione'), ('delibera', "Delibera dell'organo")], max_length=10),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approval_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approval_resolution_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='approved_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to='governance.committeemember'),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='governing_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_reviews', to='governance.securitycommittee'),
        ),
        migrations.CreateModel(
            name='ReviewParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('body_role', models.CharField(choices=[('presidente', 'Presidente'), ('membro', 'Membro'), ('segretario', 'Segretario'), ('ospite', 'Ospite')], default='membro', max_length=20)),
                ('is_chair', models.BooleanField(default=False)),
                ('attendance', models.CharField(choices=[('presente', 'Presente'), ('assente', 'Assente'), ('delegato', 'Rappresentato da delegato')], default='presente', max_length=10)),
                ('delegate_name', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_participations', to='governance.committeemember')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='management_review.managementreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='managementreview',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='managementreview',
            name='chair',
        ),
    ]
