# Generated by Django 5.2.17 on 2026-09-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0007_review_participants'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreview',
            name='report_logo_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plants.plant'),
        ),
    ]
