# Generated by Django 5.2.17 on 2026-09-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0008_report_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewagendaitem',
            name='discussion_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewagendaitem',
            name='discussion_draft_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewagendaitem',
            name='discussion_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
