# Generated by Django 5.2.17 on 2026-09-23 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentapproval_version'),
        ('governance', '0014_documentworkflowpolicy_require_distinct_reviewer'),
        ('management_review', '0009_reviewagendaitem_discussion_draft_and_more'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreview',
            name='kind',
            field=models.CharField(choices=[('completo', 'Completo (ISO 27001 §9.3)'), ('mirato', 'Mirato')], default='completo', max_length=10),
        ),
        migrations.AddField(
            model_name='reviewagendaitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='documents.document'),
        ),
        migrations.AddField(
            model_name='reviewagendaitem',
            name='document_outcome',
            field=models.CharField(blank=True, choices=[('approvato', 'Approvato'), ('rinviato', 'Rinviato'), ('respinto', 'Respinto')], max_length=10),
        ),
        migrations.AddField(
            model_name='reviewagendaitem',
            name='document_outcome_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewagendaitem',
            name='document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion'),
        ),
        migrations.AddIndex(
            model_name='managementreview',
            index=models.Index(fields=['plant', 'kind', 'status'], name='mr_plant_kind_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('document__isnull', False)), fields=('review', 'document'), name='uniq_review_document_item'),
        ),
    ]
