# Generated by Django 5.2.17 on 2026-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_review', '0010_targeted_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewagendaitem',
            name='document_outcome_error',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
