# Generated by Django 5.2.17 on 2026-10-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_evidence_shared_plants'),
        ('management_review', '0011_targeted_outcome_error'),
        ('risk', '0023_remote_access_single_asset_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewagendaitem',
            name='risk_acceptance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='risk.riskacceptance'),
        ),
        migrations.AddConstraint(
            model_name='reviewagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('risk_acceptance__isnull', False)), fields=('review', 'risk_acceptance'), name='uniq_review_risk_acceptance_item'),
        ),
    ]
