# Generated by Django 5.2.17 on 2026-10-07 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_evidence_shared_plants'),
        ('management_review', '0012_reviewagendaitem_risk_acceptance_and_more'),
        ('risk', '0025_plant_manager_not_accepting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewagendaitem',
            name='risk_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='risk.riskassessmentcycle'),
        ),
        migrations.AddConstraint(
            model_name='reviewagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('risk_cycle__isnull', False)), fields=('review', 'risk_cycle'), name='uniq_review_risk_cycle_item'),
        ),
    ]
