# Generated by Django 5.1.15 on 2026-03-13 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '__first__'),
        ('plants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLearned',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('incident', 'Incidente'), ('audit', 'Audit'), ('rischio', 'Rischio'), ('operativo', 'Operativo'), ('altro', 'Altro')], default='altro', max_length=20)),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('validato', 'Validato'), ('propagato', 'Propagato')], default='bozza', max_length=15)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_lessons', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='incidents.incident')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='plants.plant')),
                ('propagated_to_plants', models.ManyToManyField(blank=True, related_name='received_lessons', to='plants.plant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
