# Generated by Django 5.2.17 on 2026-09-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonlearned_source_id_lessonlearned_source_module'),
        ('plants', '0010_normalize_softdeleted_plantframework_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlearned',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='plants.plant'),
        ),
    ]
