# Generated by Django 5.1.15 on 2026-04-26 20:10
# Manually edited: existing rows must default to "v1" (legacy hash);
# new rows are written by log_action() which explicitly sets "v2".

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_id'),
    ]

    operations = [
        # Aggiungiamo la colonna con default 'v1' per i record esistenti.
        # Su Postgres 11+ questa è una operazione di metadata, non riscrive
        # le righe e non fa scattare il trigger audit_no_mutation.
        migrations.RunSQL(
            sql="ALTER TABLE audit_log ADD COLUMN hash_version VARCHAR(4) NOT NULL DEFAULT 'v1';",
            reverse_sql="ALTER TABLE audit_log DROP COLUMN hash_version;",
            state_operations=[
                migrations.AddField(
                    model_name='auditlog',
                    name='hash_version',
                    field=models.CharField(default='v2', max_length=4),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp_utc',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
